# Generated by Django 3.2.12 on 2022-10-18 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pivoting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_indicator', models.CharField(blank=True, max_length=250, null=True)),
                ('ai_id', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=5000)),
                ('label', models.CharField(blank=True, max_length=5000, null=True)),
                ('description', models.CharField(blank=True, max_length=1500, null=True)),
                ('awp_code', models.CharField(blank=True, max_length=1500, null=True, verbose_name='RWP')),
                ('type', models.CharField(blank=True, max_length=250, null=True)),
                ('units', models.CharField(blank=True, max_length=254, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_form_indicators', to='pivoting.activity')),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pivoting.database')),
            ],
        ),
    ]
