# Generated by Django 3.2.12 on 2022-10-18 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pivoting', '0002_formindicator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formindicator',
            name='ai_id',
        ),
        migrations.RemoveField(
            model_name='formindicator',
            name='database',
        ),
    ]
