# Generated by Django 3.2.12 on 2022-10-18 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # ('taggit', '0005_auto_20220424_2025'),
        ('pivoting', '0003_auto_20221018_1951'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='formindicator',
        #     name='tags',
        #     field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        # ),
    ]
