# Generated by Django 3.2.12 on 2022-10-19 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pivoting', '0005_formindicator_tag_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=5000)),
                ('type', models.CharField(blank=True, max_length=250, null=True)),
                ('units', models.CharField(blank=True, max_length=254, null=True)),
                ('target', models.PositiveIntegerField(default=0)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pivoting.database')),
            ],
        ),
        migrations.CreateModel(
            name='SubIndicators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pivoting.masterindicator')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pivoting.formindicator')),
            ],
        ),
        migrations.AddField(
            model_name='masterindicator',
            name='sub_indicators',
            field=models.ManyToManyField(through='pivoting.SubIndicators', to='pivoting.FormIndicator'),
        ),
    ]
