# Generated by Django 3.2.12 on 2022-10-20 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pivoting', '0006_auto_20221019_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5000)),
                ('reporting_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pivoting.reportingyear')),
            ],
        ),
        migrations.CreateModel(
            name='DashboardLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5000)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pivoting.dashboard')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='TagsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='IndicatorCategory',
        ),
        migrations.DeleteModel(
            name='PageBuilder',
        ),
        migrations.RemoveField(
            model_name='subindicators',
            name='master',
        ),
        migrations.RemoveField(
            model_name='subindicators',
            name='sub',
        ),
        # migrations.RemoveField(
        #     model_name='formindicator',
        #     name='tags',
        # ),
        migrations.RemoveField(
            model_name='masterindicator',
            name='sub_indicators',
        ),
        migrations.DeleteModel(
            name='Sites',
        ),
        migrations.DeleteModel(
            name='SubIndicators',
        ),
        migrations.AddField(
            model_name='tags',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pivoting.tagsgroup'),
        ),
        migrations.AddField(
            model_name='dashboardline',
            name='master_indicators',
            field=models.ManyToManyField(to='pivoting.MasterIndicator'),
        ),
        migrations.AlterField(
            model_name='formindicator',
            name='tag_set',
            field=models.ManyToManyField(to='pivoting.Tags'),
        ),
    ]
