# Generated by Django 3.2.12 on 2022-10-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pivoting', '0007_auto_20221020_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'ordering': ['group', 'name'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterModelOptions(
            name='tagsgroup',
            options={'ordering': ['name'], 'verbose_name': 'Tags Group', 'verbose_name_plural': 'Tags Groups'},
        ),
        migrations.RenameField(
            model_name='formindicator',
            old_name='tag_set',
            new_name='tags',
        ),
        migrations.AddField(
            model_name='masterindicator',
            name='indicators',
            field=models.ManyToManyField(to='pivoting.FormIndicator'),
        ),
    ]
