# Generated by Django 3.2.12 on 2022-10-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pivoting', '0008_auto_20221020_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterindicator',
            name='tags',
            field=models.ManyToManyField(to='pivoting.Tags'),
        ),
    ]
