# Generated by Django 3.2.12 on 2022-10-20 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pivoting', '0009_masterindicator_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeuroReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5000)),
            ],
        ),
        migrations.RenameModel(
            old_name='DashboardLine',
            new_name='ReportLine',
        ),
        migrations.DeleteModel(
            name='Dashboard',
        ),
        migrations.AlterField(
            model_name='reportline',
            name='dashboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pivoting.neuroreport'),
        ),
    ]
