# Generated by Django 3.2.12 on 2022-10-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pivoting', '0010_auto_20221020_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopMasterIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5000)),
                ('master_indicators', models.ManyToManyField(to='pivoting.MasterIndicator')),
                ('tags', models.ManyToManyField(to='pivoting.Tags')),
            ],
        ),
        migrations.DeleteModel(
            name='ReportLine',
        ),
        migrations.AddField(
            model_name='neuroreport',
            name='top_indicators',
            field=models.ManyToManyField(to='pivoting.TopMasterIndicator'),
        ),
    ]
