# Generated by Django 3.2.12 on 2022-10-21 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pivoting', '0011_auto_20221020_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeuroReportSubIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('target', models.PositiveIntegerField(default=0)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pivoting.database')),
                ('indicators', models.ManyToManyField(to='pivoting.FormIndicator', verbose_name='Activityinfo Indicators')),
                ('tags', models.ManyToManyField(to='pivoting.Tags')),
            ],
        ),
        migrations.DeleteModel(
            name='MasterIndicator',
        ),
        migrations.AlterField(
            model_name='topmasterindicator',
            name='master_indicators',
            field=models.ManyToManyField(to='pivoting.NeuroReportSubIndicator'),
        ),
    ]
