# Generated by Django 3.2.12 on 2022-10-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pivoting', '0013_rename_topmasterindicator_neuroreportmasterindicator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neuroreport',
            old_name='top_indicators',
            new_name='master_indicators',
        ),
        migrations.AddField(
            model_name='neuroreport',
            name='tags',
            field=models.ManyToManyField(to='pivoting.Tags'),
        ),
    ]
