# Generated by Django 3.2.12 on 2022-10-21 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pivoting', '0014_auto_20221021_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neuroreportmasterindicator',
            old_name='master_indicators',
            new_name='sub_indicators',
        ),
    ]
