# Generated by Django 3.2.12 on 2022-10-22 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pivoting', '0015_rename_master_indicators_neuroreportmasterindicator_sub_indicators'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormIndicator',
            new_name='IndicatorNew',
        ),
    ]
