# Generated by Django 3.2.12 on 2022-10-22 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pivoting', '0017_activityreportnew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityreportnew',
            name='day',
        ),
        migrations.RemoveField(
            model_name='activityreportnew',
            name='indicator_category',
        ),
        migrations.RemoveField(
            model_name='activityreportnew',
            name='indicator_details',
        ),
        migrations.RemoveField(
            model_name='activityreportnew',
            name='indicator_info',
        ),
        migrations.RemoveField(
            model_name='activityreportnew',
            name='indicator_master',
        ),
        migrations.RemoveField(
            model_name='activityreportnew',
            name='indicator_sub_value',
        ),
        migrations.RemoveField(
            model_name='activityreportnew',
            name='indicator_units',
        ),
        migrations.RemoveField(
            model_name='activityreportnew',
            name='lcrp_appeal',
        ),
        migrations.RemoveField(
            model_name='activityreportnew',
            name='location_cadastral',
        ),
        migrations.RemoveField(
            model_name='activityreportnew',
            name='location_caza',
        ),
        migrations.RemoveField(
            model_name='activityreportnew',
            name='location_governorate',
        ),
        migrations.RemoveField(
            model_name='activityreportnew',
            name='master_indicator',
        ),
        migrations.RemoveField(
            model_name='activityreportnew',
            name='master_indicator_sub',
        ),
        migrations.RemoveField(
            model_name='activityreportnew',
            name='order',
        ),
        migrations.RemoveField(
            model_name='activityreportnew',
            name='outreach_platform',
        ),
        migrations.RemoveField(
            model_name='activityreportnew',
            name='pending',
        ),
        migrations.RemoveField(
            model_name='activityreportnew',
            name='programme_document',
        ),
        migrations.RemoveField(
            model_name='activityreportnew',
            name='project_end_date',
        ),
        migrations.RemoveField(
            model_name='activityreportnew',
            name='project_start_date',
        ),
        migrations.RemoveField(
            model_name='activityreportnew',
            name='site_id',
        ),
        migrations.RemoveField(
            model_name='activityreportnew',
            name='site_type',
        ),
        migrations.RemoveField(
            model_name='activityreportnew',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='activityreportnew',
            name='year',
        ),
    ]
