# Generated by Django 3.2.12 on 2022-10-22 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pivoting', '0018_auto_20221022_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityreportnew',
            name='ai_indicator',
        ),
        migrations.RemoveField(
            model_name='activityreportnew',
            name='form_category',
        ),
        migrations.RemoveField(
            model_name='activityreportnew',
            name='partner_ai',
        ),
    ]
