# Generated by Django 3.2.12 on 2022-10-22 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pivoting', '0019_auto_20221022_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityreportnew',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='activityreportnew',
            name='governorate',
        ),
    ]
