# Generated by Django 3.2.12 on 2022-10-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pivoting', '0020_auto_20221022_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neuroreportmasterindicator',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='pivoting.Tags'),
        ),
    ]
