# Generated by Django 3.2.12 on 2022-10-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pivoting', '0021_alter_neuroreportmasterindicator_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neuroreportmasterindicator',
            name='sub_indicators',
            field=models.ManyToManyField(blank=True, to='pivoting.NeuroReportSubIndicator'),
        ),
        migrations.AlterField(
            model_name='neuroreportmasterindicator',
            name='tags',
            field=models.ManyToManyField(blank=True, to='pivoting.Tags'),
        ),
        migrations.AlterField(
            model_name='neuroreportsubindicator',
            name='indicators',
            field=models.ManyToManyField(blank=True, to='pivoting.IndicatorNew', verbose_name='Activityinfo Indicators'),
        ),
        migrations.AlterField(
            model_name='neuroreportsubindicator',
            name='tags',
            field=models.ManyToManyField(blank=True, to='pivoting.Tags'),
        ),
    ]
