# Generated by Django 3.2.12 on 2022-10-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pivoting', '0023_auto_20221024_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neuroreportsubindicator',
            name='age_group',
        ),
        migrations.RemoveField(
            model_name='neuroreportsubindicator',
            name='disability',
        ),
        migrations.RemoveField(
            model_name='neuroreportsubindicator',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='neuroreportsubindicator',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='neuroreportsubindicator',
            name='programme',
        ),
        migrations.AddField(
            model_name='indicatornew',
            name='age_group',
            field=models.CharField(blank=True, choices=[('0-4', '0-4'), ('5-9', '5-9'), ('10-14', '10-14'), ('15-19', '15-19'), ('20-24', '20-24'), ('25-29', '25-29'), ('30-34', '30-34'), ('35-39', '35-39'), ('40-44', '40-44'), ('45-49', '45-49'), ('50-54', '50-54'), ('55-59', '55-59'), ('60-64', '60-64'), ('65-69', '65-69'), ('70-74', '70-74'), ('75-79', '75-79'), ('Above 80', 'Above 80')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='indicatornew',
            name='disability',
            field=models.CharField(blank=True, choices=[('Speaking', 'Speaking'), ('Intellectual', 'Intellectual'), ('Hearing', 'Audio (Hearing)'), ('Seeing', 'Visual (Seeing)'), ('Mobility', 'Motor/Mobility')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='indicatornew',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='indicatornew',
            name='nationality',
            field=models.CharField(blank=True, choices=[('LEB', 'Lebanese'), ('PRL', 'Palestinian from Lebanon'), ('PRS', 'Palestinian from Syria'), ('SYR', 'Syrian'), ('OTH', 'Other Nationality')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='indicatornew',
            name='programme',
            field=models.CharField(blank=True, choices=[('ALP', 'ALP'), ('BLN', 'BLN'), ('CBECE', 'CBECE')], max_length=10, null=True),
        ),
    ]
