# Generated by Django 3.2.12 on 2022-10-25 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pivoting', '0024_auto_20221025_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neuroreportmasterindicator',
            name='tags',
        ),
    ]
