# Generated by Django 3.2.12 on 2022-10-25 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pivoting', '0025_remove_neuroreportmasterindicator_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neuroreport',
            name='tags',
        ),
        migrations.AddField(
            model_name='neuroreport',
            name='reporting_year',
            field=models.CharField(blank=True, choices=[('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='neuroreport',
            name='section',
            field=models.CharField(blank=True, choices=[('C4D', 'C4D'), ('Child Protection', 'Child Protection'), ('Education', 'Education'), ('Health and Nutrition', 'Health and Nutrition'), ('Humanitarian Coordination', 'Humanitarian Coordination'), ('Palestinian Programme', 'Palestinian Programme'), ('Seeing', 'Visual (Seeing)'), ('Social Policy', 'Social Policy'), ('WASH', 'WASH'), ('Youth & Adolescent', 'Youth & Adolescent')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='neuroreportmasterindicator',
            name='awp_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='RWP'),
        ),
        migrations.AddField(
            model_name='neuroreportmasterindicator',
            name='database',
            field=models.ForeignKey(default=101, on_delete=django.db.models.deletion.PROTECT, to='pivoting.database'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neuroreportsubindicator',
            name='awp_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='RWP'),
        ),
        migrations.AlterField(
            model_name='indicatornew',
            name='ai_indicator',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='indicatornew',
            name='awp_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='RWP'),
        ),
        migrations.AlterField(
            model_name='indicatornew',
            name='description',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='indicatornew',
            name='label',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='indicatornew',
            name='name',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='indicatornew',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='indicatornew',
            name='units',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
