# Generated by Django 3.2.12 on 2022-10-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pivoting', '0026_auto_20221025_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neuroreport',
            name='section',
            field=models.CharField(blank=True, choices=[('C4D', 'C4D'), ('Child Protection', 'Child Protection'), ('Education', 'Education'), ('Health and Nutrition', 'Health and Nutrition'), ('Humanitarian Coordination', 'Humanitarian Coordination'), ('Palestinian Programme', 'Palestinian Programme'), ('Social Policy', 'Social Policy'), ('WASH', 'WASH'), ('Youth & Adolescent', 'Youth & Adolescent')], max_length=30, null=True),
        ),
    ]
