# Generated by Django 3.2.12 on 2022-10-25 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pivoting', '0027_alter_neuroreport_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatornew',
            name='database',
            field=models.ForeignKey(default=104, on_delete=django.db.models.deletion.PROTECT, to='pivoting.database'),
            preserve_default=False,
        ),
    ]
