# Generated by Django 3.2.12 on 2022-10-25 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pivoting', '0028_indicatornew_database'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatornew',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_form_indicators', to='pivoting.activity'),
        ),
    ]
