# Generated by Django 3.2.12 on 2022-10-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pivoting', '0029_alter_indicatornew_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatornew',
            name='awp_code',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='RWP'),
        ),
        migrations.AlterField(
            model_name='indicatornew',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='indicatornew',
            name='units',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
