# Generated by Django 3.2.12 on 2022-10-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pivoting', '0030_auto_20221025_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatornew',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='indicatornew',
            name='label',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='indicatornew',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
