# Generated by Django 3.2.12 on 2022-10-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pivoting', '0031_auto_20221025_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neuroreportsubindicator',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
