# Generated by Django 3.2.12 on 2022-10-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pivoting', '0032_alter_neuroreportsubindicator_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neuroreportmasterindicator',
            name='awp_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='RWP'),
        ),
        migrations.AlterField(
            model_name='neuroreportsubindicator',
            name='awp_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='RWP'),
        ),
    ]
