# Generated by Django 3.2.12 on 2022-10-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pivoting', '0033_auto_20221025_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neuroreportmasterindicator',
            name='awp_code',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='RWP'),
        ),
        migrations.AlterField(
            model_name='neuroreportsubindicator',
            name='awp_code',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='RWP'),
        ),
    ]
