# Generated by Django 3.2.12 on 2022-10-25 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20220309_1103'),
        ('pivoting', '0034_auto_20221025_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neuroreport',
            name='section',
        ),
        migrations.AddField(
            model_name='neuroreport',
            name='usection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.section'),
        ),
    ]
