# Generated by Django 3.2.12 on 2022-10-28 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pivoting', '0035_auto_20221025_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='neuroreport',
            name='database',
            field=models.ForeignKey(default=128, on_delete=django.db.models.deletion.PROTECT, to='pivoting.database'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indicatornew',
            name='disability',
            field=models.CharField(blank=True, choices=[('Speaking', 'Speaking'), ('Intellectual', 'Intellectual'), ('Audio', 'Audio (Hearing)'), ('Visual', 'Visual (Seeing)'), ('Motor', 'Motor/Mobility')], max_length=15, null=True),
        ),
    ]
