# Generated by Django 3.2.12 on 2022-10-29 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pivoting', '0036_auto_20221028_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityreportnew',
            old_name='database',
            new_name='ai_folder',
        ),
    ]
