# Generated by Django 3.2.12 on 2022-10-29 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pivoting', '0037_rename_database_activityreportnew_ai_folder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityreportnew',
            old_name='database_id',
            new_name='database_ai_id',
        ),
    ]
