# Generated by Django 3.2.12 on 2022-10-29 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pivoting', '0038_rename_database_id_activityreportnew_database_ai_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityreportnew',
            name='dbase',
            field=models.ForeignKey(default=173, on_delete=django.db.models.deletion.CASCADE, to='pivoting.database'),
            preserve_default=False,
        ),
    ]
