# Generated by Django 3.2.12 on 2022-11-03 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pivoting', '0039_activityreportnew_dbase'),
    ]

    operations = [
        migrations.AddField(
            model_name='neuroreportmasterindicator',
            name='target',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='indicatornew',
            name='programme',
            field=models.CharField(blank=True, choices=[('ALP', 'ALP'), ('BLN', 'BLN'), ('ABLN', 'ABLN'), ('CBECE', 'CBECE')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='neuroreport',
            name='database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='neuroreports', to='pivoting.database'),
        ),
    ]
