# Generated by Django 3.2.12 on 2022-11-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pivoting', '0040_auto_20221103_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neuroreportmasterindicator',
            name='awp_code',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='RWP'),
        ),
        migrations.AlterField(
            model_name='neuroreportsubindicator',
            name='awp_code',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='RWP'),
        ),
    ]
