# Generated by Django 3.2.12 on 2022-11-22 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pivoting', '0041_auto_20221105_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddMasterIndicatorsWizard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_by', models.CharField(blank=True, choices=[('Tags', 'Tags'), ('Selection', 'Selection')], default='Tags', max_length=20, null=True, verbose_name='Add By')),
            ],
            options={
                'verbose_name': 'Select Master Indicators Wizard',
                'verbose_name_plural': 'Select Master Indicators Wizard',
            },
        ),
        migrations.CreateModel(
            name='AddSubIndicatorsWizard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect', models.CharField(blank=True, choices=[('TOTAL', 'TOTAL'), ('NUMERATOR', 'NUMERATOR'), ('DENOMINATOR', 'DENOMINATOR'), ('NO_EFFECT', 'NO_EFFECT')], default='TOTAL', max_length=254, null=True, verbose_name='Effect on Master value')),
            ],
            options={
                'verbose_name': 'Select Sub Indicators Wizard',
                'verbose_name_plural': 'Select Sub Indicators Wizard',
            },
        ),
        migrations.CreateModel(
            name='MasterIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5000)),
                ('awp_code', models.CharField(blank=True, max_length=500, null=True, verbose_name='RWP')),
                ('aggregation_method', models.CharField(blank=True, choices=[('SUM', 'SUM'), ('AVERAGE', 'AVERAGE'), ('MINIMUM', 'MINIMUM'), ('MAXIMUM', 'MAXIMUM'), ('SUM_OVER_SUM', 'SUM_OVER_SUM')], default='SUM', max_length=20, null=True)),
                ('awp_target', models.PositiveIntegerField(default=0)),
                ('indicator_type', models.CharField(blank=True, max_length=250, null=True)),
                ('reporting_level', models.CharField(blank=True, choices=[('DISTRICT', 'DISTRICT'), ('CADASTRAL', 'CADASTRAL'), ('GOVERNORATE', 'GOVERNORATE'), ('NATIONAL', 'NATIONAL'), ('GATEWAY', 'DISTRICT'), ('INSTITUTIONAL', 'INSTITUTIONAL')], max_length=254, null=True)),
                ('ram_result', models.PositiveIntegerField(default=0, verbose_name='RAM Result')),
                ('is_active', models.BooleanField(default=True)),
                ('old_id', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MasterIndicatorTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='MasterSubIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listed', models.BooleanField(default=True, verbose_name='Dashboard')),
                ('effect', models.CharField(blank=True, choices=[('TOTAL', 'TOTAL'), ('NUMERATOR', 'NUMERATOR'), ('DENOMINATOR', 'DENOMINATOR'), ('NO_EFFECT', 'NO_EFFECT')], default='TOTAL', max_length=254, null=True, verbose_name='Effect')),
                ('label', models.CharField(max_length=500)),
                ('target', models.PositiveIntegerField(default=0)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subindicators', to='pivoting.masterindicator', verbose_name='Master indicator')),
            ],
        ),
        migrations.CreateModel(
            name='SubIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('awp_code', models.CharField(blank=True, max_length=500, null=True, verbose_name='RWP')),
                ('target', models.PositiveIntegerField(default=0)),
                ('aggregation_method', models.CharField(blank=True, choices=[('SUM', 'SUM'), ('AVERAGE', 'AVERAGE')], default='SUM', max_length=20, null=True)),
                ('old_id', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='activityreport',
            name='ai_indicator',
        ),
        migrations.RemoveField(
            model_name='activityreport',
            name='location_cadastral',
        ),
        migrations.RemoveField(
            model_name='activityreport',
            name='location_caza',
        ),
        migrations.RemoveField(
            model_name='activityreport',
            name='location_governorate',
        ),
        migrations.RemoveField(
            model_name='activityreport',
            name='partner_ai',
        ),
        migrations.RemoveField(
            model_name='activityreport',
            name='programme_document',
        ),
        migrations.RemoveField(
            model_name='activityreportlive',
            name='activityreport_ptr',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='denominator_indicator',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='denominator_summation',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='main_master_indicator',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='numerator_indicator',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='numerator_summation',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='project',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='second_activity',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='sub_indicators',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='summation_sub_indicators',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='tag_age',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='tag_disability',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='tag_focus',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='tag_gender',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='tag_nationality',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='tag_programme',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='third_activity',
        ),
        migrations.RemoveField(
            model_name='indicatorpartner',
            name='ai_indicator',
        ),
        migrations.RemoveField(
            model_name='indicatorpartner',
            name='partner',
        ),
        migrations.DeleteModel(
            name='IndicatorTag',
        ),
        migrations.RemoveField(
            model_name='liveactivityreport',
            name='ai_indicator',
        ),
        migrations.RemoveField(
            model_name='liveactivityreport',
            name='partner_ai',
        ),
        migrations.RemoveField(
            model_name='neuroreportsubindicator',
            name='database',
        ),
        migrations.RemoveField(
            model_name='neuroreportsubindicator',
            name='indicators',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='group',
        ),
        migrations.RemoveField(
            model_name='neuroreport',
            name='database',
        ),
        migrations.RemoveField(
            model_name='neuroreport',
            name='master_indicators',
        ),
        migrations.RemoveField(
            model_name='neuroreport',
            name='reporting_year',
        ),
        migrations.RemoveField(
            model_name='neuroreport',
            name='usection',
        ),
        migrations.RemoveField(
            model_name='neuroreportmasterindicator',
            name='awp_code',
        ),
        migrations.RemoveField(
            model_name='neuroreportmasterindicator',
            name='database',
        ),
        migrations.RemoveField(
            model_name='neuroreportmasterindicator',
            name='name',
        ),
        migrations.RemoveField(
            model_name='neuroreportmasterindicator',
            name='sub_indicators',
        ),
        migrations.AddField(
            model_name='database',
            name='old_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='neuroreport',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='neuroreport',
            name='ryear',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pivoting.reportingyear'),
        ),
        migrations.AddField(
            model_name='neuroreportmasterindicator',
            name='label',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Label'),
        ),
        migrations.AddField(
            model_name='neuroreportmasterindicator',
            name='ram_result',
            field=models.PositiveIntegerField(default=0, verbose_name='RAM Result'),
        ),
        migrations.AddField(
            model_name='neuroreportmasterindicator',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pivoting.neuroreport'),
        ),
        migrations.AddField(
            model_name='reportingyear',
            name='old_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ActivityReport',
        ),
        migrations.DeleteModel(
            name='ActivityReportLive',
        ),
        migrations.DeleteModel(
            name='Indicator',
        ),
        migrations.DeleteModel(
            name='IndicatorPartner',
        ),
        migrations.DeleteModel(
            name='LiveActivityReport',
        ),
        migrations.DeleteModel(
            name='NeuroReportSubIndicator',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
        migrations.DeleteModel(
            name='TagsGroup',
        ),
        migrations.AddField(
            model_name='subindicator',
            name='database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pivoting.database'),
        ),
        migrations.AddField(
            model_name='subindicator',
            name='indicators',
            field=models.ManyToManyField(blank=True, to='pivoting.IndicatorNew', verbose_name='Activityinfo Indicators'),
        ),
        migrations.AddField(
            model_name='mastersubindicator',
            name='sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pivoting.subindicator', verbose_name='Sub indicator'),
        ),
        migrations.AddField(
            model_name='masterindicator',
            name='database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pivoting.database'),
        ),
        migrations.AddField(
            model_name='masterindicator',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='pivoting.MasterIndicatorTag'),
        ),
        migrations.AddField(
            model_name='addsubindicatorswizard',
            name='indicators',
            field=models.ManyToManyField(blank=True, to='pivoting.SubIndicator', verbose_name='Sub Indicators'),
        ),
        migrations.AddField(
            model_name='addsubindicatorswizard',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pivoting.masterindicator', verbose_name='Master Indicator'),
        ),
        migrations.AddField(
            model_name='addmasterindicatorswizard',
            name='indicators',
            field=models.ManyToManyField(blank=True, to='pivoting.MasterIndicator', verbose_name='Master Indicators'),
        ),
        migrations.AddField(
            model_name='addmasterindicatorswizard',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pivoting.neuroreport', verbose_name='Neuro Report'),
        ),
        migrations.AddField(
            model_name='addmasterindicatorswizard',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='pivoting.MasterIndicatorTag'),
        ),
        migrations.AddField(
            model_name='neuroreportmasterindicator',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pivoting.masterindicator'),
        ),
    ]
