# Generated by Django 3.2.12 on 2022-11-26 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pivoting', '0042_auto_20221122_1307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicatornew',
            options={'verbose_name': 'indicator', 'verbose_name_plural': 'indicators'},
        ),
        migrations.AlterModelOptions(
            name='masterindicator',
            options={'ordering': ['sequence']},
        ),
        migrations.AlterModelOptions(
            name='subindicator',
            options={'ordering': ['sequence']},
        ),
        migrations.AddField(
            model_name='activity',
            name='label',
            field=models.CharField(default='', max_length=1500, verbose_name='Form Name/Label'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activityreportnew',
            name='last_edited_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityreportnew',
            name='parent_form',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='masterindicator',
            name='sequence',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subindicator',
            name='sequence',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='ai_category_id',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='AI Folder ID'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='AI Folder'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=1500, verbose_name='Form Name'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='none_ai_database',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pivoting.database', verbose_name='TBD'),
        ),
        migrations.AlterField(
            model_name='indicatornew',
            name='awp_code',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='RWP Code'),
        ),
        migrations.AlterField(
            model_name='masterindicator',
            name='awp_code',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='RWP Code'),
        ),
        migrations.AlterField(
            model_name='subindicator',
            name='awp_code',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='RWP Code'),
        ),
        migrations.CreateModel(
            name='NeuroReportComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=5000, null=True)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pivoting.neuroreportmasterindicator')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pivoting.neuroreport')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
            },
        ),
    ]
