# Generated by Django 3.2.12 on 2022-11-26 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pivoting', '0043_auto_20221126_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pivoting.database'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='attribute_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pivoting.attributegroup'),
        ),
        migrations.AlterField(
            model_name='attributegroup',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pivoting.activity'),
        ),
        migrations.AlterField(
            model_name='indicatornew',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_form_indicators', to='pivoting.activity'),
        ),
        migrations.AlterField(
            model_name='indicatornew',
            name='database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pivoting.database'),
        ),
        migrations.AlterField(
            model_name='masterindicator',
            name='database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pivoting.database'),
        ),
        migrations.AlterField(
            model_name='subindicator',
            name='database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pivoting.database'),
        ),
    ]
