# Generated by Django 3.2.12 on 2022-12-04 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pivoting', '0044_auto_20221126_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='attribute_group',
        ),
        migrations.RemoveField(
            model_name='attributegroup',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='locations',
            name='entities',
        ),
        migrations.RemoveField(
            model_name='locations',
            name='type',
        ),
        migrations.RemoveField(
            model_name='locationtypes',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='database',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='partner_etools',
        ),
        migrations.DeleteModel(
            name='AdminLevelEntities',
        ),
        migrations.DeleteModel(
            name='AdminLevels',
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
        migrations.DeleteModel(
            name='AttributeGroup',
        ),
        migrations.DeleteModel(
            name='Locations',
        ),
        migrations.DeleteModel(
            name='LocationTypes',
        ),
        migrations.DeleteModel(
            name='Partner',
        ),
    ]
