# Generated by Django 3.2.12 on 2022-12-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pivoting', '0045_auto_20221204_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='neuroreport',
            name='is_hpm',
            field=models.BooleanField(default=False, help_text='HPM reports are viewed using HPM report template'),
        ),
        migrations.AddField(
            model_name='neuroreportcomment',
            name='related_month',
            field=models.CharField(choices=[('01', 'Jan'), ('02', 'Feb'), ('03', 'Mar'), ('04', 'Apr'), ('05', 'May'), ('06', 'Jun'), ('07', 'Jul'), ('08', 'Aug'), ('09', 'Sep'), ('10', 'Oct'), ('11', 'Nov'), ('12', 'Dec')], default='01', max_length=2),
        ),
    ]
