# Generated by Django 3.2.12 on 2022-12-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pivoting', '0046_auto_20221205_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='neuroreport',
            name='report_code',
            field=models.CharField(default='', help_text='Used to identify the similar reports that are defined for different reporting years', max_length=20),
        ),
    ]
