# Generated by Django 3.2.12 on 2022-11-11 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pivoting', '0047_neuroreport_report_code'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='mastersubindicator',
            name='effect',
            field=models.CharField(blank=True, choices=[('TOTAL', 'TOTAL'), ('NUMERATOR', 'NUMERATOR'), ('DENOMINATOR', 'DENOMINATOR'), ('NO_EFFECT', 'NO_EFFECT')], default='TOTAL', max_length=254, null=True, verbose_name='Effect on Master value'),
        ),
    ]
