# Generated by Django 3.2.12 on 2022-11-16 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pivoting', '0048_auto_20221112_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastersubindicator',
            name='sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subindicators', to='pivoting.subindicator', verbose_name='Sub indicator'),
        ),
    ]
