# Generated by Django 3.2.12 on 2022-11-17 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pivoting', '0049_alter_mastersubindicator_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastersubindicator',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subindicators', to='pivoting.masterindicator', verbose_name='Master indicator'),
        ),
        migrations.AlterField(
            model_name='mastersubindicator',
            name='sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pivoting.subindicator', verbose_name='Sub indicator'),
        ),
        # migrations.CreateModel(
        #     name='AddSubIndicatorsWizard',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('effect', models.CharField(blank=True, choices=[('TOTAL', 'TOTAL'), ('NUMERATOR', 'NUMERATOR'), ('DENOMINATOR', 'DENOMINATOR'), ('NO_EFFECT', 'NO_EFFECT')], default='TOTAL', max_length=254, null=True, verbose_name='Effect on Master value')),
        #         ('Indicators', models.ManyToManyField(blank=True, to='pivoting.SubIndicator', verbose_name='Sub Indicators')),
        #         ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pivoting.masterindicator', verbose_name='Master Indicator')),
        #     ],
        #     options={
        #         'verbose_name': 'Add Sub Indicators Wizard',
        #         'verbose_name_plural': 'Add Sub Indicators Wizard',
        #     },
        # ),
    ]
