# Generated by Django 3.2.12 on 2022-11-17 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pivoting', '0050_auto_20221117_1115'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='addsubindicatorswizard',
        #     old_name='Indicators',
        #     new_name='indicators',
        # ),
    ]
