# Generated by Django 4.1.5 on 2023-03-27 16:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etools", "0062_alter_actionpoint_id_alter_agreement_id_and_more"),
        ("pivoting", "0051_rename_indicators_addsubindicatorswizard_indicators"),
    ]

    operations = [
        migrations.CreateModel(
            name="CadasterLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=10)),
                ("gov_code", models.CharField(db_index=True, max_length=10)),
                ("dist_code", models.CharField(db_index=True, max_length=10)),
                ("name", models.CharField(db_index=True, max_length=100)),
                (
                    "polygon_coordinates",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=64500),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "fill_color",
                    models.CharField(
                        blank=True, db_index=True, max_length=10, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cadasters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("GOV_CODE", models.CharField(db_index=True, max_length=50)),
                ("DISTRICT_C", models.CharField(db_index=True, max_length=50)),
                ("CAS_CODE", models.CharField(db_index=True, max_length=50)),
                ("CADASTER_N", models.CharField(db_index=True, max_length=50)),
                ("GOV_N", models.CharField(db_index=True, max_length=50)),
                ("COUNTRY_N", models.CharField(db_index=True, max_length=50)),
                ("COUNTRY_C", models.CharField(db_index=True, max_length=50)),
                ("GOV_C", models.CharField(db_index=True, max_length=50)),
                ("DISTRICT_N", models.CharField(db_index=True, max_length=50)),
                ("MUNI_N", models.CharField(db_index=True, max_length=50)),
                ("MUNI_C", models.CharField(db_index=True, max_length=50)),
                ("MUNI_C_1", models.CharField(db_index=True, max_length=50)),
                ("MUNI_C_UPD", models.CharField(db_index=True, max_length=50)),
                ("NAME", models.CharField(db_index=True, max_length=200)),
                ("WKT", models.CharField(db_index=True, max_length=50)),
                (
                    "polygon",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=64500),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cadaster",
                "verbose_name_plural": "Cadasters",
            },
        ),
        migrations.CreateModel(
            name="DistrictLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=10)),
                ("gov_code", models.CharField(db_index=True, max_length=10)),
                ("name", models.CharField(db_index=True, max_length=100)),
                (
                    "polygon_coordinates",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=64500),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "fill_color",
                    models.CharField(
                        blank=True, db_index=True, max_length=10, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GovernorateLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=10)),
                ("name", models.CharField(db_index=True, max_length=100)),
                (
                    "polygon_coordinates",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=64500),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "fill_color",
                    models.CharField(
                        blank=True, db_index=True, max_length=10, null=True
                    ),
                ),
                ("ai_id", models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="activity",
            name="programme_documents",
            field=models.ManyToManyField(blank=True, related_name="+", to="etools.pca"),
        ),
        migrations.AlterField(
            model_name="mastersubindicator",
            name="effect",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TOTAL", "TOTAL"),
                    ("NUMERATOR", "NUMERATOR"),
                    ("DENOMINATOR", "DENOMINATOR"),
                    ("NO_EFFECT", "NO_EFFECT"),
                ],
                default="TOTAL",
                max_length=254,
                null=True,
                verbose_name="Effect",
            ),
        ),
    ]
