# Generated by Django 4.1.5 on 2023-05-08 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pivoting", "0052_cadasterlocation_cadasters_districtlocation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Resource Tag",
                "verbose_name_plural": "Resource Tags",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ResourceTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Resource Topic",
                "verbose_name_plural": "Resource Topics",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ResourceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Resource Type",
                "verbose_name_plural": "Resource Types",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The full title of the research",
                        max_length=500,
                        verbose_name="Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A brief narative on the resource objectives.",
                        max_length=1500,
                        null=True,
                        verbose_name="Description/Abstract",
                    ),
                ),
                (
                    "publication_year",
                    models.CharField(
                        help_text="The year the research was published or made available for public use",
                        max_length=10,
                        verbose_name="Year of publication",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("Child Protection", "Child Protection"),
                            ("Health and Nutrition", "Health and Nutrition"),
                            ("Education", "Education"),
                            ("WASH", "WASH"),
                            ("Social Policy", "Social Policy"),
                            (
                                "Cross-sectoral (Gender, Disability, Youth, etc.)",
                                "Cross-sectoral (Gender, Disability, Youth, etc.)",
                            ),
                        ],
                        max_length=100,
                        verbose_name="Program",
                    ),
                ),
                (
                    "resource_link",
                    models.URLField(
                        blank=True,
                        help_text="URL link to access the resource",
                        max_length=2500,
                        null=True,
                        verbose_name="Resource Link",
                    ),
                ),
                (
                    "resource_file",
                    models.BinaryField(
                        blank=True,
                        editable=True,
                        null=True,
                        verbose_name="Resource File",
                    ),
                ),
                (
                    "resource_file_name",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Resource File",
                    ),
                ),
                (
                    "resource_image",
                    models.BinaryField(
                        blank=True,
                        editable=True,
                        null=True,
                        verbose_name="Resource Cover Image",
                    ),
                ),
                (
                    "resource_image_name",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Resource Cover Image",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, null=True, to="pivoting.resourcetag"
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pivoting.resourcetopic",
                        verbose_name="Resource Topic",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pivoting.resourcetype",
                        verbose_name="Resource Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resource",
                "verbose_name_plural": "Resources",
                "ordering": ("-id",),
            },
        ),
    ]
