# Generated by Django 4.1.5 on 2023-06-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pivoting', '0053_resourcetag_resourcetopic_resourcetype_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityreportnew',
            name='project_plan',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
    ]
