# Generated by Django 4.1.5 on 2023-07-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pivoting', '0054_activityreportnew_project_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mastersubindicator',
            options={'ordering': ['sequence']},
        ),
        migrations.AddField(
            model_name='mastersubindicator',
            name='sequence',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
