# Generated by Django 4.2.3 on 2023-08-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pivoting", "0055_alter_mastersubindicator_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="masterindicator",
            name="sector_equivalent",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="masterindicator",
            name="unit",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="subindicator",
            name="sector_equivalent",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="masterindicator",
            name="awp_target",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="masterindicator",
            name="indicator_type",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Category"
            ),
        ),
        migrations.AlterField(
            model_name="masterindicator",
            name="ram_result",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="RAM Result"
            ),
        ),
        migrations.AlterField(
            model_name="mastersubindicator",
            name="sequence",
            field=models.PositiveIntegerField(default=0, verbose_name="Position"),
        ),
        migrations.AlterField(
            model_name="resource",
            name="section",
            field=models.CharField(
                choices=[
                    ("Basic Assistance", "Basic Assistance"),
                    ("Child Protection", "Child Protection"),
                    ("Communication", "Communication"),
                    ("Drivers", "Drivers"),
                    ("Education", "Education"),
                    ("Field Operations", "Field Operations"),
                    ("Field Ops", "Field Ops"),
                    ("Food Security", "Food Security"),
                    ("Health and Nutrition", "Health and Nutrition"),
                    ("Humanitarian Coordination", "Humanitarian Coordination"),
                    ("Livelihoods", "Livelihoods"),
                    ("Operations", "Operations"),
                    ("PRIME", "PRIME"),
                    ("Palestinian Programme", "Palestinian Programme"),
                    ("Representative Office", "Representative Office"),
                    ("SBC", "SBC"),
                    ("SGBV", "SGBV"),
                    ("Security", "Security"),
                    ("Social Policy", "Social Policy"),
                    ("Social Protection", "Social Protection"),
                    ("Social Stability", "Social Stability"),
                    ("WASH", "WASH"),
                    ("Winter", "Winter"),
                    ("Youth & Adolescent", "Youth & Adolescent"),
                    (
                        "Cross-sectoral (Gender, Disability, Youth, etc.)",
                        "Cross-sectoral (Gender, Disability, Youth, etc.)",
                    ),
                ],
                max_length=100,
                verbose_name="Program",
            ),
        ),
        migrations.AlterField(
            model_name="subindicator",
            name="target",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
