# Generated by Django 4.2.3 on 2023-08-02 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pivoting", "0056_masterindicator_sector_equivalent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subindicator",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pivoting.activity",
            ),
        ),
        migrations.AlterField(
            model_name="indicatornew",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="activity_form_indicators",
                to="pivoting.activity",
            ),
        ),
        migrations.AlterField(
            model_name="masterindicator",
            name="awp_code",
            field=models.CharField(default="", max_length=500, verbose_name="RWP Code"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mastersubindicator",
            name="target",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="neuroreportmasterindicator",
            name="ram_result",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="RAM Result"
            ),
        ),
        migrations.AlterField(
            model_name="neuroreportmasterindicator",
            name="target",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="subindicator",
            name="awp_code",
            field=models.CharField(default="", max_length=500, verbose_name="RWP Code"),
            preserve_default=False,
        ),
    ]
