# Generated by Django 4.2.3 on 2023-08-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pivoting", "0057_subindicator_activity_alter_indicatornew_activity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="neuroreportmasterindicator",
            name="category",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Category"
            ),
        ),
    ]
