# Generated by Django 4.2.3 on 2023-08-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pivoting", "0058_neuroreportmasterindicator_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimpleLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=254, verbose_name="Name")),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="Latitude"),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="Longitude"),
                ),
                (
                    "p_code",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="P Code"
                    ),
                ),
                (
                    "cas_code",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="Cas Code"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="database",
            name="display",
            field=models.BooleanField(default=True, verbose_name="Show on dashboard"),
        ),
    ]
