# Generated by Django 3.2.12 on 2023-09-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pivoting', '0059_simplelocation_alter_database_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterindicator',
            name='sector_equivalent',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='subindicator',
            name='sector_equivalent',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
