# Generated by Django 3.2.12 on 2023-10-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pivoting', '0060_auto_20230926_0843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='database',
            options={'ordering': ['name', '-ai_id']},
        ),
        migrations.AlterModelOptions(
            name='masterindicator',
            options={'ordering': ['awp_code']},
        ),
        migrations.AlterModelOptions(
            name='subindicator',
            options={'ordering': ['awp_code']},
        ),
        migrations.AlterField(
            model_name='mastersubindicator',
            name='label',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
