# Generated by Django 3.2.12 on 2023-10-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pivoting', '0061_auto_20231005_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subindicator',
            options={'ordering': ['awp_code', 'sequence']},
        ),
        migrations.AlterField(
            model_name='indicatornew',
            name='age_group',
            field=models.CharField(blank=True, choices=[('0-1', '0-1'), ('0-3', '0-3'), ('0-4', '0-4'), ('0-5', '0-5'), ('10-14', '10-14'), ('12-17', '12-17'), ('14-17', '14-17'), ('15-17', '15-17'), ('15-19', '15-19'), ('15-20', '15-20'), ('18 and above', '18 and above'), ('18-24', '18-24'), ('18-25', '18-25'), ('18-59', '18-59'), ('20-24', '20-24'), ('25-49', '25-49'), ('26-59', '26-59'), ('3-5', '3-5'), ('5-17', '5-17'), ('50-64', '50-64'), ('6-11', '6-11'), ('6-13', '6-13'), ('6-59 months', '6-59 months'), ('6-9', '6-9'), ('60 and above', '60 and above'), ('Above 18', 'Above 18'), ('Above 5', 'Above 5'), ('Above 60', 'Above 60'), ('Under 18', 'Under 18'), ('Under 5', 'Under 5'), ('Under 60Under 60', 'Under 60Under 60')], max_length=20, null=True),
        ),
    ]
