# Generated by Django 3.2.12 on 2023-11-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pivoting', '0062_auto_20231016_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityreportnew',
            name='emergency',
            field=models.CharField(blank=True, default='no', max_length=10, null=True),
        ),
    ]
