# Generated by Django 3.2.12 on 2024-03-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pivoting', '0063_activityreportnew_emergency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicatornew',
            options={'ordering': ['nationality', 'awp_code'], 'verbose_name': 'indicator', 'verbose_name_plural': 'indicators'},
        ),
        migrations.AddField(
            model_name='resource',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='masterindicator',
            name='aggregation_method',
            field=models.CharField(blank=True, choices=[('SUM', 'SUM'), ('AVERAGE', 'AVERAGE'), ('MINIMUM', 'MINIMUM'), ('MAXIMUM', 'MAXIMUM'), ('SUM_OVER_SUM', 'SUM_OVER_SUM'), ('COUNT', 'COUNT')], default='SUM', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subindicator',
            name='indicators',
            field=models.ManyToManyField(blank=True, to='pivoting.IndicatorNew', verbose_name='Indicators'),
        ),
    ]
