# Generated by Django 3.2.12 on 2024-05-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pivoting', '0064_auto_20240318_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityreportnew',
            name='project',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='indicatornew',
            name='age_group',
            field=models.CharField(blank=True, choices=[('0-1', '0-1'), ('0-3', '0-3'), ('0-4', '0-4'), ('0-5', '0-5'), ('10-14', '10-14'), ('12-17', '12-17'), ('14-17', '14-17'), ('15-17', '15-17'), ('15-19', '15-19'), ('15-20', '15-20'), ('>=18', '>=18'), ('18-24', '18-24'), ('18-25', '18-25'), ('18-59', '18-59'), ('20-24', '20-24'), ('25-49', '25-49'), ('26-59', '26-59'), ('3-5', '3-5'), ('5-17', '5-17'), ('50-64', '50-64'), ('6-11', '6-11'), ('6-13', '6-13'), ('6-59 months', '6-59 months'), ('6-9', '6-9'), ('>=60', '>=60'), ('>18', '>18'), ('>5', '>5'), ('>60', '>60'), ('<18', '<18'), ('<5', '<5'), ('<60<60', '<60<60')], max_length=20, null=True),
        ),
    ]
