# Generated by Django 5.0.7 on 2024-09-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pivoting", "0066_map"),
    ]

    operations = [
        migrations.AlterField(
            model_name="map",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Draft", "Draft"),
                    ("In progress", "In progress"),
                    ("Completed", "Completed"),
                    ("Archived", "Archived"),
                ],
                default="Draft",
                max_length=1500,
                null=True,
                verbose_name="Status",
            ),
        ),
    ]
