# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-24 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180724_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='powerbi_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
