# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-31 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_section_powerbi_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skype_account',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
