# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-06 01:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_skype_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='backup_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
