# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-01 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_backup_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='logo',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
