# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-13 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='etools',
            field=models.BooleanField(default=False),
        ),
    ]
