# Generated by Django 5.2.17 on 2026-09-22 19:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LocationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "name",
                    models.CharField(max_length=254, unique=True, verbose_name="Name"),
                ),
                (
                    "admin_level",
                    models.PositiveSmallIntegerField(
                        null=True, unique=True, verbose_name="Admin Level"
                    ),
                ),
            ],
            options={"managed": True, 
                "verbose_name": "Location Type",
                "verbose_name_plural": "Location Types",
                "db_table": "locations_locationtype",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=254, verbose_name="Name")),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="Latitude"),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="Longitude"),
                ),
                (
                    "p_code",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="P Code"
                    ),
                ),
                (
                    "cas_code",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="Cas Code"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, verbose_name="Active"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="locations.location",
                        verbose_name="Parent",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="locations.locationtype",
                        verbose_name="Location Type",
                    ),
                ),
            ],
            options={"managed": True, 
                "verbose_name": "location",
                "verbose_name_plural": "locations",
                "db_table": "locations_location",
                "unique_together": {("name", "type", "p_code")},
            },
        ),
    ]
