"""Create the location tables when the database never had them.

The location models map the v2 tables (``managed = False`` in production), so Django never creates
them; a database restored without the v2 ``locations`` app (as production was) has no
``locations_locationtype`` / ``locations_location`` / ``etools_pca_locations``, and every page or
sync touching locations fails. This creates them with the v2 columns when they are missing and
does nothing when they exist.
"""

from django.db import migrations

SQL = """
CREATE TABLE IF NOT EXISTS locations_locationtype (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created timestamp with time zone NOT NULL DEFAULT now(),
    modified timestamp with time zone NOT NULL DEFAULT now(),
    name varchar(254) NOT NULL UNIQUE,
    admin_level smallint NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS locations_location (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(254) NOT NULL,
    type_id bigint NULL,
    latitude double precision NULL,
    longitude double precision NULL,
    p_code varchar(32) NOT NULL DEFAULT '',
    cas_code varchar(32) NOT NULL DEFAULT '',
    parent_id bigint NULL,
    is_active boolean NOT NULL DEFAULT true,
    created timestamp with time zone NOT NULL DEFAULT now(),
    modified timestamp with time zone NOT NULL DEFAULT now(),
    lft integer NOT NULL DEFAULT 1,
    rght integer NOT NULL DEFAULT 2,
    tree_id integer NOT NULL DEFAULT 0,
    level integer NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS locations_location_p_code_idx ON locations_location (p_code);
CREATE INDEX IF NOT EXISTS locations_location_parent_id_idx ON locations_location (parent_id);
CREATE INDEX IF NOT EXISTS locations_location_type_id_idx ON locations_location (type_id);
CREATE TABLE IF NOT EXISTS etools_pca_locations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pca_id bigint NOT NULL,
    location_id bigint NOT NULL,
    UNIQUE (pca_id, location_id)
);
"""


class Migration(migrations.Migration):
    dependencies = [("locations", "0001_initial")]

    operations = [migrations.RunSQL(SQL, reverse_sql=migrations.RunSQL.noop)]
