# Generated by Django 5.2.17 on 2026-10-01 06:15

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.core.validators
import django.db.models.deletion
import neurodb.knowledge.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        max_length=300,
                        upload_to=neurodb.knowledge.models.document_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ("pdf", "docx", "txt", "md", "csv", "xlsx", "pptx")
                            ),
                            neurodb.knowledge.models.max_size,
                        ],
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True,
                        help_text="the text typed or pasted, or read from the file",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="where it comes from, e.g. 'Mid-term review, MEHE, 2026'",
                        max_length=300,
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="the year it is about", null=True
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                ("key_points", models.JSONField(blank=True, default=list)),
                ("document_date", models.DateField(blank=True, null=True)),
                ("pages", models.PositiveIntegerField(default=0)),
                ("characters", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Waiting to be read"),
                            ("indexing", "Being read"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("indexed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="users.section",
                    ),
                ),
            ],
            options={
                "verbose_name": "knowledge document",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Chunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("page", models.PositiveIntegerField(blank=True, null=True)),
                ("text", models.TextField()),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(null=True),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="knowledge.document",
                    ),
                ),
            ],
            options={
                "ordering": ("document", "position"),
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"], name="knowledge_chunk_search"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document", "position"), name="knowledge_chunk_position"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("partner", "Partner"),
                            ("programme_document", "Programme document"),
                            ("section", "Section"),
                            ("governorate", "Governorate"),
                            ("district", "District"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "object_id",
                    models.BigIntegerField(
                        help_text="the id of the partner, programme document, section or place"
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=300)),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("detected", "Found in the text"),
                            ("ai", "AI-suggested"),
                            ("manual", "Added by hand"),
                        ],
                        default="manual",
                        max_length=10,
                    ),
                ),
                ("mentions", models.PositiveIntegerField(default=0)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="knowledge.document",
                    ),
                ),
            ],
            options={
                "ordering": ("kind", "-mentions", "label"),
                "indexes": [
                    models.Index(
                        fields=["kind", "object_id"], name="knowledge_l_kind_74d4b4_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document", "kind", "object_id"),
                        name="knowledge_link_unique",
                    )
                ],
            },
        ),
    ]
