# Generated by Django 5.2.17 on 2026-10-01 14:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="origin",
            field=models.CharField(
                choices=[
                    ("added", "Added to the knowledge base"),
                    ("library", "Library publication"),
                    ("cpd", "Country programme document"),
                ],
                default="added",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="origin_id",
            field=models.PositiveIntegerField(
                blank=True, help_text="the publication or CPD document", null=True
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="origin_signature",
            field=models.CharField(
                blank=True, help_text="tells when the source changed", max_length=300
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.UniqueConstraint(
                condition=models.Q(("origin", "added"), _negated=True),
                fields=("origin", "origin_id"),
                name="knowledge_one_per_source",
            ),
        ),
    ]
