# Generated by Django 5.2.17 on 2026-10-02 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0002_document_origin_document_origin_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="the name without number and date",
                        max_length=200,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "periodic report",
                "verbose_name_plural": "periodic reports",
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="document",
            name="edition",
            field=models.PositiveIntegerField(
                blank=True, help_text="its number, e.g. 37", null=True
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="figures_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="document",
            name="figures_read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="figures_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not a periodic report"),
                    ("pending", "Figures waiting to be read"),
                    ("read", "Figures read"),
                    ("failed", "Figures could not be read"),
                ],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="issued_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="periodic",
            field=models.BooleanField(
                default=False,
                help_text="an edition of a report issued periodically: its figures are kept by date",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="series",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="editions",
                to="knowledge.reportseries",
            ),
        ),
        migrations.CreateModel(
            name="ReportFigure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="the same measure in every edition", max_length=300
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        blank=True,
                        help_text="heading or sector, e.g. Health",
                        max_length=200,
                    ),
                ),
                ("metric", models.CharField(max_length=300)),
                (
                    "breakdown",
                    models.CharField(
                        blank=True,
                        help_text="e.g. children; empty for the total",
                        max_length=150,
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=40)),
                ("is_percent", models.BooleanField(default=False)),
                ("value", models.DecimalField(decimal_places=4, max_digits=20)),
                (
                    "target",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                ("as_of", models.DateField(help_text="the date the figure is about")),
                ("period", models.CharField(blank=True, max_length=200)),
                ("source", models.CharField(blank=True, max_length=200)),
                (
                    "internal",
                    models.BooleanField(
                        default=False, help_text="marked for internal use in the report"
                    ),
                ),
                ("page", models.PositiveIntegerField(blank=True, null=True)),
                ("quote", models.CharField(blank=True, max_length=500)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("chart", "Read from a chart"),
                            ("text", "Read from the text (AI)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="figures",
                        to="knowledge.document",
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="figures",
                        to="knowledge.reportseries",
                    ),
                ),
            ],
            options={
                "verbose_name": "report figure",
                "ordering": ("series", "group", "metric", "breakdown", "as_of"),
                "indexes": [
                    models.Index(
                        fields=["series", "key", "as_of"],
                        name="knowledge_r_series__73c8f6_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document", "key", "as_of"),
                        name="knowledge_figure_once",
                    )
                ],
            },
        ),
    ]
