# Generated by Django 5.2.17 on 2026-10-06 20:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0003_periodic_reports"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "topic",
                "ordering": (
                    "subtopic__programme__order",
                    "subtopic__programme__name",
                    "subtopic__order",
                    "order",
                    "name",
                ),
            },
        ),
        migrations.CreateModel(
            name="TopicProgramme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "topic programme",
                "ordering": ("order", "name"),
            },
        ),
        migrations.AddField(
            model_name="document",
            name="review_progress_at",
            field=models.DateTimeField(
                blank=True,
                help_text="the last step of the analysis (none for 30 minutes: given up)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="review_stage_notes",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="per stage: yes, partly or failed, and why",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("not_in_review", "Not in the review"),
                    ("pending", "Waiting to be analysed"),
                    ("running", "Being analysed"),
                    ("done", "Analysed"),
                    ("partly", "Partly analysed"),
                    ("failed", "Analysis failed"),
                    ("reference", "Reference only"),
                ],
                db_index=True,
                default="not_in_review",
                max_length=14,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="reviewed_at",
            field=models.DateTimeField(
                blank=True, help_text="when the last analysis ended", null=True
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="reviewed_text_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name="DocumentFinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Not reviewed"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="unreviewed",
                        max_length=10,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("challenge", "Challenge"),
                            ("recommendation", "Recommendation"),
                            ("observation", "Observation"),
                            ("action_point", "Action point"),
                        ],
                        db_index=True,
                        max_length=14,
                    ),
                ),
                (
                    "tag_text",
                    models.CharField(
                        blank=True,
                        help_text="the tag as the AI wrote it",
                        max_length=200,
                    ),
                ),
                ("text", models.TextField()),
                ("quote", models.TextField(blank=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("reported", "Reported by the document"),
                            ("interpreted", "Interpreted from it"),
                        ],
                        default="reported",
                        max_length=12,
                    ),
                ),
                ("page_label", models.CharField(blank=True, max_length=80)),
                ("page_from", models.PositiveIntegerField(blank=True, null=True)),
                ("page_to", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "chunk_from",
                    models.PositiveIntegerField(
                        blank=True, help_text="the part's first page", null=True
                    ),
                ),
                ("chunk_to", models.PositiveIntegerField(blank=True, null=True)),
                ("quote_found", models.BooleanField(default=False)),
                ("exact_page", models.BooleanField(default=False)),
                ("place_text", models.CharField(blank=True, max_length=200)),
                (
                    "place_match",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "No place"),
                            ("general", "Lebanon (country-wide)"),
                            ("governorate", "Governorate"),
                            ("district", "District"),
                            ("unmatched", "Not recognised"),
                        ],
                        default="",
                        max_length=12,
                    ),
                ),
                ("governorate_id", models.BigIntegerField(blank=True, null=True)),
                ("governorate_name", models.CharField(blank=True, max_length=100)),
                ("district_id", models.BigIntegerField(blank=True, null=True)),
                ("district_name", models.CharField(blank=True, max_length=100)),
                ("finding_date", models.DateField(blank=True, null=True)),
                ("date_text", models.CharField(blank=True, max_length=100)),
                (
                    "evidence",
                    models.PositiveSmallIntegerField(db_index=True, default=0),
                ),
                (
                    "derived",
                    models.BooleanField(
                        default=False,
                        help_text="made by the enrichment for an action point no finding states",
                    ),
                ),
                (
                    "manual",
                    models.BooleanField(
                        default=False,
                        help_text="added by a person; re-analysis keeps it",
                    ),
                ),
                (
                    "model_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="the text and quote as the AI wrote them",
                        max_length=64,
                    ),
                ),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="knowledge.document",
                    ),
                ),
                (
                    "edited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="findings",
                        to="knowledge.topic",
                    ),
                ),
            ],
            options={
                "verbose_name": "document finding",
                "ordering": ("document", "position", "pk"),
            },
        ),
        migrations.CreateModel(
            name="DocumentReviewSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="off until an administrator turns it on: nothing is analysed meanwhile",
                    ),
                ),
                (
                    "tagging_prompt",
                    models.TextField(
                        default="",
                        help_text="stage 1: how the findings are found and tagged",
                    ),
                ),
                (
                    "summary_prompt",
                    models.TextField(
                        default="",
                        help_text="stage 2: how the key statements are written",
                    ),
                ),
                (
                    "enrichment_prompt",
                    models.TextField(
                        default="",
                        help_text="stage 3: how the action points are drawn from the findings",
                    ),
                ),
                (
                    "statements_per_document",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="at most (fewer for short documents, never under 5); 0 = the default, 20",
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "max_findings_per_chunk",
                    models.PositiveSmallIntegerField(
                        default=25,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "chunk_size",
                    models.PositiveIntegerField(
                        default=12000,
                        help_text="characters of the document read in one AI call",
                        validators=[
                            django.core.validators.MinValueValidator(2000),
                            django.core.validators.MaxValueValidator(60000),
                        ],
                    ),
                ),
                (
                    "daily_token_cap",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="tokens a day for the document review; 0 = DOC_REVIEW_DAILY_TOKEN_CAP",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "document review settings",
                "verbose_name_plural": "document review settings",
            },
        ),
        migrations.CreateModel(
            name="ReviewBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "archived",
                    models.BooleanField(
                        default=False,
                        help_text="kept, but no longer analysed or listed first",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "document review batch",
                "verbose_name_plural": "document review batches",
                "ordering": ("archived", "name"),
            },
        ),
        migrations.AddField(
            model_name="document",
            name="review_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="knowledge.reviewbatch",
            ),
        ),
        migrations.CreateModel(
            name="DocumentStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Not reviewed"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="unreviewed",
                        max_length=10,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("text", models.TextField()),
                ("urgency", models.PositiveSmallIntegerField(default=0)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("challenge", "Challenge"),
                            ("recommendation", "Recommendation"),
                            ("observation", "Observation"),
                            ("action_point", "Action point"),
                        ],
                        max_length=14,
                    ),
                ),
                ("place_text", models.CharField(blank=True, max_length=200)),
                ("date_text", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cites",
                    models.ManyToManyField(
                        blank=True,
                        related_name="statements",
                        to="knowledge.documentfinding",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statements",
                        to="knowledge.document",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        help_text="the topic most of its findings have",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="knowledge.topic",
                    ),
                ),
            ],
            options={
                "verbose_name": "document statement",
                "ordering": ("document", "-urgency", "position"),
            },
        ),
        migrations.CreateModel(
            name="DocumentActionPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("action", models.TextField()),
                (
                    "action_key",
                    models.CharField(
                        db_index=True,
                        help_text="the action's words, normalised",
                        max_length=64,
                    ),
                ),
                ("owner_text", models.CharField(default="Unassigned", max_length=200)),
                ("deadline_text", models.CharField(blank=True, max_length=100)),
                (
                    "deadline_date",
                    models.DateField(
                        blank=True,
                        help_text="a quarter or year: its last day",
                        null=True,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("unrated", "Not rated"),
                        ],
                        default="unrated",
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("done", "Done"),
                            ("dropped", "Dropped"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=8,
                    ),
                ),
                ("status_at", models.DateTimeField(blank=True, null=True)),
                (
                    "derived",
                    models.BooleanField(
                        default=False,
                        help_text="drawn from challenges or recommendations: no finding states it as such",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_action_points",
                        to="knowledge.document",
                    ),
                ),
                (
                    "status_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cites",
                    models.ManyToManyField(
                        blank=True,
                        related_name="action_points",
                        to="knowledge.documentfinding",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="knowledge.topic",
                    ),
                ),
            ],
            options={
                "verbose_name": "document action point",
                "ordering": ("document", "position"),
            },
        ),
        migrations.CreateModel(
            name="TopicSubtopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                (
                    "programme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtopics",
                        to="knowledge.topicprogramme",
                    ),
                ),
            ],
            options={
                "verbose_name": "topic subtopic",
                "ordering": ("programme__order", "programme__name", "order", "name"),
            },
        ),
        migrations.AddField(
            model_name="topic",
            name="subtopic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topics",
                to="knowledge.topicsubtopic",
            ),
        ),
        migrations.AddIndex(
            model_name="documentfinding",
            index=models.Index(
                fields=["document", "verdict"], name="knowledge_d_documen_a0a4b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentfinding",
            index=models.Index(
                fields=["topic", "category"], name="knowledge_d_topic_i_e6dedd_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="topicsubtopic",
            constraint=models.UniqueConstraint(
                fields=("programme", "name"), name="knowledge_subtopic_once"
            ),
        ),
        migrations.AddConstraint(
            model_name="topic",
            constraint=models.UniqueConstraint(
                fields=("subtopic", "name"), name="knowledge_topic_once"
            ),
        ),
    ]
