# Generated by Django 5.2.17 on 2026-10-07 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0005_review_topics"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewParagraph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Being written"),
                            ("done", "Written"),
                            ("failed", "Failed"),
                            ("limited", "Refused (quota or budget)"),
                        ],
                        db_index=True,
                        default="running",
                        max_length=8,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=200)),
                (
                    "findings",
                    models.PositiveIntegerField(default=0, help_text="findings sent"),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True, help_text="the paragraph, its citations written out"
                    ),
                ),
                ("model", models.CharField(blank=True, max_length=64)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="knowledge.topic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "theme paragraph",
                "verbose_name_plural": "theme paragraphs",
                "ordering": ("-created_at",),
            },
        ),
    ]
