# Generated by Django 5.2.17 on 2026-09-22 19:08

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("etools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityReportNew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "form",
                    models.CharField(
                        blank=True, db_index=True, max_length=1000, null=True
                    ),
                ),
                (
                    "indicator_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=250, null=True
                    ),
                ),
                (
                    "indicator_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=1000, null=True
                    ),
                ),
                (
                    "indicator_value",
                    models.FloatField(blank=True, null=True, verbose_name="Value"),
                ),
                (
                    "indicator_awp_code",
                    models.CharField(
                        blank=True, db_index=True, max_length=254, null=True
                    ),
                ),
                (
                    "location_adminlevel_cadastral_area",
                    models.CharField(
                        blank=True, db_index=True, max_length=250, null=True
                    ),
                ),
                (
                    "location_adminlevel_cadastral_area_code",
                    models.CharField(
                        blank=True, db_index=True, max_length=250, null=True
                    ),
                ),
                (
                    "location_adminlevel_caza",
                    models.CharField(
                        blank=True, db_index=True, max_length=250, null=True
                    ),
                ),
                (
                    "location_adminlevel_caza_code",
                    models.CharField(
                        blank=True, db_index=True, max_length=250, null=True
                    ),
                ),
                (
                    "location_adminlevel_governorate",
                    models.CharField(
                        blank=True, db_index=True, max_length=250, null=True
                    ),
                ),
                (
                    "location_adminlevel_governorate_code",
                    models.CharField(
                        blank=True, db_index=True, max_length=250, null=True
                    ),
                ),
                (
                    "location_alternate_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "location_latitude",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "location_longitude",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "location_name",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="Location"
                    ),
                ),
                (
                    "partner_description",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "partner_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=250, null=True
                    ),
                ),
                (
                    "partner_label",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=250,
                        null=True,
                        verbose_name="Partner",
                    ),
                ),
                (
                    "project_description",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "project_label",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=250,
                        null=True,
                        verbose_name="Project",
                    ),
                ),
                (
                    "funded_by",
                    models.CharField(
                        blank=True, db_index=True, max_length=250, null=True
                    ),
                ),
                (
                    "report_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=250, null=True
                    ),
                ),
                (
                    "database_ai_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=250, null=True
                    ),
                ),
                (
                    "ai_folder",
                    models.CharField(
                        blank=True, db_index=True, max_length=250, null=True
                    ),
                ),
                (
                    "month",
                    models.CharField(
                        blank=True, db_index=True, max_length=250, null=True
                    ),
                ),
                (
                    "month_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=250, null=True
                    ),
                ),
                (
                    "reporting_section",
                    models.CharField(
                        blank=True, db_index=True, max_length=250, null=True
                    ),
                ),
                ("support_covid", models.BooleanField(default=False)),
                ("last_edited_time", models.DateTimeField(blank=True, null=True)),
                (
                    "parent_form",
                    models.CharField(
                        blank=True, db_index=True, max_length=250, null=True
                    ),
                ),
                (
                    "project_plan",
                    models.CharField(
                        blank=True, db_index=True, max_length=250, null=True
                    ),
                ),
                (
                    "project",
                    models.CharField(
                        blank=True, db_index=True, max_length=250, null=True
                    ),
                ),
                (
                    "emergency",
                    models.CharField(
                        blank=True, default="no", max_length=10, null=True
                    ),
                ),
            ],
            options={"managed": settings.LEGACY_TABLES_MANAGED, 
                "verbose_name": "activity report new",
                "verbose_name_plural": "activity report news",
                "db_table": "pivoting_activityreportnew",
            },
        ),
        migrations.CreateModel(
            name="CadasterLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=10)),
                ("gov_code", models.CharField(db_index=True, max_length=10)),
                ("dist_code", models.CharField(db_index=True, max_length=10)),
                ("name", models.CharField(db_index=True, max_length=100)),
                (
                    "polygon_coordinates",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=64500),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "fill_color",
                    models.CharField(
                        blank=True, db_index=True, max_length=10, null=True
                    ),
                ),
            ],
            options={"managed": settings.LEGACY_TABLES_MANAGED, 
                "verbose_name": "cadaster location",
                "verbose_name_plural": "cadaster locations",
                "db_table": "pivoting_cadasterlocation",
            },
        ),
        migrations.CreateModel(
            name="Database",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ai_id", models.PositiveIntegerField(unique=True, verbose_name="ID")),
                (
                    "parent_id",
                    models.CharField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="ActivityInfo Parent ID",
                    ),
                ),
                (
                    "db_id",
                    models.CharField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="ActivityInfo ID",
                    ),
                ),
                ("name", models.CharField(max_length=254)),
                (
                    "sector_label",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                ("label", models.CharField(blank=True, max_length=254, null=True)),
                ("hpm_label", models.CharField(blank=True, max_length=254, null=True)),
                ("hpm_sequence", models.PositiveIntegerField(default=0)),
                ("username", models.CharField(max_length=254)),
                ("password", models.CharField(max_length=254)),
                ("description", models.CharField(max_length=1500, null=True)),
                ("country_name", models.CharField(max_length=254, null=True)),
                (
                    "dashboard_link",
                    models.URLField(blank=True, max_length=1500, null=True),
                ),
                ("ai_country_id", models.PositiveIntegerField(null=True)),
                ("mapped_db", models.BooleanField(default=True)),
                ("mapping_extraction1", models.JSONField(blank=True, null=True)),
                ("mapping_extraction2", models.JSONField(blank=True, null=True)),
                ("mapping_extraction3", models.JSONField(blank=True, null=True)),
                ("is_funded_by_unicef", models.BooleanField(default=False)),
                (
                    "display",
                    models.BooleanField(default=True, verbose_name="Show on dashboard"),
                ),
                ("is_sector", models.BooleanField(default=False)),
                ("is_current_extraction", models.BooleanField(default=False)),
                ("have_partners", models.BooleanField(default=True)),
                ("have_governorates", models.BooleanField(default=True)),
                ("have_covid", models.BooleanField(default=True)),
                ("have_offices", models.BooleanField(default=False)),
                ("have_internal_reporting", models.BooleanField(default=True)),
                ("support_covid", models.BooleanField(default=False)),
                ("have_sections", models.BooleanField(default=False)),
                ("configs", models.JSONField(blank=True, default=dict, null=True)),
                ("old_id", models.PositiveIntegerField(default=0)),
                (
                    "year",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("2017", "2017"),
                            ("2018", "2018"),
                            ("2019", "2019"),
                            ("2020", "2020"),
                            ("2021", "2021"),
                            ("2022", "2022"),
                            ("2023", "2023"),
                            ("2024", "2024"),
                            ("2025", "2025"),
                            ("2026", "2026"),
                            ("2027", "2027"),
                            ("2028", "2028"),
                            ("2029", "2029"),
                            ("2030", "2030"),
                        ],
                        max_length=250,
                        null=True,
                    ),
                ),
                ("last_update_date", models.DateField(blank=True, null=True)),
                ("last_live_update_date", models.DateTimeField(blank=True, null=True)),
                (
                    "last_monthly_update_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "last_weekly_update_date",
                    models.DateTimeField(blank=True, null=True),
                ),
            ],
            options={"managed": settings.LEGACY_TABLES_MANAGED, 
                "verbose_name": "database",
                "verbose_name_plural": "databases",
                "db_table": "pivoting_database",
                "ordering": ("name", "-ai_id"),
            },
        ),
        migrations.CreateModel(
            name="DistrictLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=10)),
                ("gov_code", models.CharField(db_index=True, max_length=10)),
                ("name", models.CharField(db_index=True, max_length=100)),
                (
                    "polygon_coordinates",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=64500),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "fill_color",
                    models.CharField(
                        blank=True, db_index=True, max_length=10, null=True
                    ),
                ),
            ],
            options={"managed": settings.LEGACY_TABLES_MANAGED, 
                "verbose_name": "district location",
                "verbose_name_plural": "district locations",
                "db_table": "pivoting_districtlocation",
            },
        ),
        migrations.CreateModel(
            name="GovernorateLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=10)),
                ("name", models.CharField(db_index=True, max_length=100)),
                (
                    "polygon_coordinates",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=64500),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "fill_color",
                    models.CharField(
                        blank=True, db_index=True, max_length=10, null=True
                    ),
                ),
                ("ai_id", models.PositiveSmallIntegerField()),
            ],
            options={"managed": settings.LEGACY_TABLES_MANAGED, 
                "verbose_name": "governorate location",
                "verbose_name_plural": "governorate locations",
                "db_table": "pivoting_governoratelocation",
            },
        ),
        migrations.CreateModel(
            name="IndicatorNew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "ai_indicator",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("name", models.CharField(max_length=500)),
                ("label", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "awp_code",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="RWP Code"
                    ),
                ),
                ("type", models.CharField(blank=True, max_length=50, null=True)),
                ("units", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "Male"), ("female", "Female")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "age_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("0-1", "0-1"),
                            ("0-3", "0-3"),
                            ("0-4", "0-4"),
                            ("0-5", "0-5"),
                            ("10-14", "10-14"),
                            ("12-17", "12-17"),
                            ("14-17", "14-17"),
                            ("15-17", "15-17"),
                            ("15-19", "15-19"),
                            ("15-20", "15-20"),
                            (">=18", ">=18"),
                            ("18-24", "18-24"),
                            ("18-25", "18-25"),
                            ("18-59", "18-59"),
                            ("20-24", "20-24"),
                            ("25-49", "25-49"),
                            ("26-59", "26-59"),
                            ("3-5", "3-5"),
                            ("5-17", "5-17"),
                            ("50-64", "50-64"),
                            ("6-11", "6-11"),
                            ("6-13", "6-13"),
                            ("6-59 months", "6-59 months"),
                            ("6-9", "6-9"),
                            (">=60", ">=60"),
                            (">18", ">18"),
                            (">5", ">5"),
                            (">60", ">60"),
                            ("<18", "<18"),
                            ("<5", "<5"),
                            ("<60<60", "<60<60"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "programme",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ALP", "ALP"),
                            ("BLN", "BLN"),
                            ("ABLN", "ABLN"),
                            ("CBECE", "CBECE"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "disability",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Speaking", "Speaking"),
                            ("Intellectual", "Intellectual"),
                            ("Audio", "Audio (Hearing)"),
                            ("Visual", "Visual (Seeing)"),
                            ("Motor", "Motor/Mobility"),
                        ],
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "nationality",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LEB", "Lebanese"),
                            ("PRL", "Palestinian from Lebanon"),
                            ("PRS", "Palestinian from Syria"),
                            ("SYR", "Syrian"),
                            ("OTH", "Other Nationality"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
            ],
            options={"managed": settings.LEGACY_TABLES_MANAGED, 
                "verbose_name": "indicator",
                "verbose_name_plural": "indicators",
                "db_table": "pivoting_indicatornew",
                "ordering": ("nationality", "awp_code"),
            },
        ),
        migrations.CreateModel(
            name="Map",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("name", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True, null=True)),
                ("link", models.URLField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Draft", "Draft"),
                            ("In progress", "In progress"),
                            ("Completed", "Completed"),
                            ("Archived", "Archived"),
                        ],
                        default="Draft",
                        max_length=1500,
                        null=True,
                        verbose_name="Status",
                    ),
                ),
            ],
            options={"managed": settings.LEGACY_TABLES_MANAGED, 
                "verbose_name": "map",
                "verbose_name_plural": "maps",
                "db_table": "pivoting_map",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="MasterIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=5000)),
                ("awp_code", models.CharField(max_length=500, verbose_name="RWP Code")),
                (
                    "aggregation_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SUM", "SUM"),
                            ("AVERAGE", "AVERAGE"),
                            ("MINIMUM", "MINIMUM"),
                            ("MAXIMUM", "MAXIMUM"),
                            ("SUM_OVER_SUM", "SUM_OVER_SUM"),
                            ("COUNT", "COUNT"),
                        ],
                        default="SUM",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "awp_target",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "indicator_type",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="Category"
                    ),
                ),
                (
                    "reporting_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DISTRICT", "DISTRICT"),
                            ("CADASTRAL", "CADASTRAL"),
                            ("GOVERNORATE", "GOVERNORATE"),
                            ("NATIONAL", "NATIONAL"),
                            ("GATEWAY", "DISTRICT"),
                            ("INSTITUTIONAL", "INSTITUTIONAL"),
                            ("SITE_LEVEL", "SITE_LEVEL"),
                            ("MUNICIPALITY", "MUNICIPALITY"),
                        ],
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "ram_result",
                    models.PositiveIntegerField(
                        blank=True, default=0, null=True, verbose_name="RAM Result"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("old_id", models.PositiveIntegerField(default=0)),
                ("sequence", models.PositiveIntegerField(default=0)),
                ("unit", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "sector_equivalent",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
            options={"managed": settings.LEGACY_TABLES_MANAGED, 
                "verbose_name": "master indicator",
                "verbose_name_plural": "master indicators",
                "db_table": "pivoting_masterindicator",
                "ordering": ("awp_code",),
            },
        ),
        migrations.CreateModel(
            name="MasterIndicatorTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=20)),
            ],
            options={"managed": settings.LEGACY_TABLES_MANAGED, 
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "db_table": "pivoting_masterindicatortag",
            },
        ),
        migrations.CreateModel(
            name="MasterSubIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("listed", models.BooleanField(default=True, verbose_name="Dashboard")),
                (
                    "effect",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TOTAL", "TOTAL"),
                            ("NUMERATOR", "NUMERATOR"),
                            ("DENOMINATOR", "DENOMINATOR"),
                            ("NO_EFFECT", "NO_EFFECT"),
                        ],
                        default="TOTAL",
                        max_length=254,
                        null=True,
                        verbose_name="Effect",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "target",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(default=0, verbose_name="Position"),
                ),
            ],
            options={"managed": settings.LEGACY_TABLES_MANAGED, 
                "verbose_name": "master sub indicator",
                "verbose_name_plural": "master sub indicators",
                "db_table": "pivoting_mastersubindicator",
                "ordering": ("sequence",),
            },
        ),
        migrations.CreateModel(
            name="NeuroReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=5000)),
                (
                    "report_code",
                    models.CharField(
                        default="",
                        help_text="Used to identify the similar reports that are defined for different reporting years",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_hpm",
                    models.BooleanField(
                        default=False,
                        help_text="HPM reports are viewed using HPM report template",
                    ),
                ),
            ],
            options={"managed": settings.LEGACY_TABLES_MANAGED, 
                "verbose_name": "neuro report",
                "verbose_name_plural": "neuro reports",
                "db_table": "pivoting_neuroreport",
            },
        ),
        migrations.CreateModel(
            name="NeuroReportComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("comment", models.CharField(blank=True, max_length=5000, null=True)),
                (
                    "related_month",
                    models.CharField(
                        choices=[
                            ("01", "Jan"),
                            ("02", "Feb"),
                            ("03", "Mar"),
                            ("04", "Apr"),
                            ("05", "May"),
                            ("06", "Jun"),
                            ("07", "Jul"),
                            ("08", "Aug"),
                            ("09", "Sep"),
                            ("10", "Oct"),
                            ("11", "Nov"),
                            ("12", "Dec"),
                        ],
                        default="01",
                        max_length=2,
                    ),
                ),
                ("entry_date", models.DateTimeField(auto_now_add=True)),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"managed": settings.LEGACY_TABLES_MANAGED, 
                "verbose_name": "comment",
                "verbose_name_plural": "comments",
                "db_table": "pivoting_neuroreportcomment",
            },
        ),
        migrations.CreateModel(
            name="NeuroReportMasterIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, max_length=5000, null=True, verbose_name="Label"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Category"
                    ),
                ),
                (
                    "target",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "ram_result",
                    models.PositiveIntegerField(
                        blank=True, default=0, null=True, verbose_name="RAM Result"
                    ),
                ),
            ],
            options={"managed": settings.LEGACY_TABLES_MANAGED, 
                "verbose_name": "neuro report master indicator",
                "verbose_name_plural": "neuro report master indicators",
                "db_table": "pivoting_neuroreportmasterindicator",
            },
        ),
        migrations.CreateModel(
            name="ReportingYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=254)),
                ("year", models.CharField(max_length=254, null=True)),
                ("current", models.BooleanField(default=False)),
                (
                    "database_id",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                ("form_id", models.CharField(blank=True, max_length=254, null=True)),
                ("old_id", models.PositiveIntegerField(default=0)),
            ],
            options={"managed": settings.LEGACY_TABLES_MANAGED, 
                "verbose_name": "reporting year",
                "verbose_name_plural": "reporting years",
                "db_table": "pivoting_reportingyear",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The full title of the research",
                        max_length=500,
                        verbose_name="Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A brief narative on the resource objectives.",
                        max_length=1500,
                        null=True,
                        verbose_name="Description/Abstract",
                    ),
                ),
                (
                    "publication_year",
                    models.CharField(
                        help_text="The year the research was published or made available for public use",
                        max_length=10,
                        verbose_name="Year of publication",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("Basic Assistance", "Basic Assistance"),
                            ("Child Protection", "Child Protection"),
                            ("Communication", "Communication"),
                            ("Drivers", "Drivers"),
                            ("Education", "Education"),
                            ("Field Operations", "Field Operations"),
                            ("Field Ops", "Field Ops"),
                            ("Food Security", "Food Security"),
                            ("Health and Nutrition", "Health and Nutrition"),
                            ("Humanitarian Coordination", "Humanitarian Coordination"),
                            ("Livelihoods", "Livelihoods"),
                            ("Operations", "Operations"),
                            ("PRIME", "PRIME"),
                            ("Palestinian Programme", "Palestinian Programme"),
                            ("Representative Office", "Representative Office"),
                            ("SBC", "SBC"),
                            ("SGBV", "SGBV"),
                            ("Security", "Security"),
                            ("Social Policy", "Social Policy"),
                            ("Social Protection", "Social Protection"),
                            ("Social Stability", "Social Stability"),
                            ("WASH", "WASH"),
                            ("Winter", "Winter"),
                            ("Youth & Adolescent", "Youth & Adolescent"),
                            (
                                "Cross-sectoral (Gender, Disability, Youth, etc.)",
                                "Cross-sectoral (Gender, Disability, Youth, etc.)",
                            ),
                        ],
                        max_length=100,
                        verbose_name="Program",
                    ),
                ),
                (
                    "resource_link",
                    models.URLField(
                        blank=True,
                        help_text="URL link to access the resource",
                        max_length=2500,
                        null=True,
                        verbose_name="Resource Link",
                    ),
                ),
                (
                    "resource_file",
                    models.BinaryField(
                        blank=True,
                        editable=True,
                        null=True,
                        verbose_name="Resource File",
                    ),
                ),
                (
                    "resource_file_name",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Resource File",
                    ),
                ),
                (
                    "resource_image",
                    models.BinaryField(
                        blank=True,
                        editable=True,
                        null=True,
                        verbose_name="Resource Cover Image",
                    ),
                ),
                (
                    "resource_image_name",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Resource Cover Image",
                    ),
                ),
                ("published", models.BooleanField(default=True)),
            ],
            options={"managed": settings.LEGACY_TABLES_MANAGED, 
                "verbose_name": "Resource",
                "verbose_name_plural": "Resources",
                "db_table": "pivoting_resource",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="ResourceTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={"managed": settings.LEGACY_TABLES_MANAGED, 
                "verbose_name": "Resource Tag",
                "verbose_name_plural": "Resource Tags",
                "db_table": "pivoting_resourcetag",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ResourceTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={"managed": settings.LEGACY_TABLES_MANAGED, 
                "verbose_name": "Resource Topic",
                "verbose_name_plural": "Resource Topics",
                "db_table": "pivoting_resourcetopic",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ResourceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={"managed": settings.LEGACY_TABLES_MANAGED, 
                "verbose_name": "Resource Type",
                "verbose_name_plural": "Resource Types",
                "db_table": "pivoting_resourcetype",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="SimpleLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=254, verbose_name="Name")),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="Latitude"),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="Longitude"),
                ),
                (
                    "p_code",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="P Code"
                    ),
                ),
                (
                    "cas_code",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="Cas Code"
                    ),
                ),
            ],
            options={"managed": settings.LEGACY_TABLES_MANAGED, 
                "verbose_name": "simple location",
                "verbose_name_plural": "simple locations",
                "db_table": "pivoting_simplelocation",
            },
        ),
        migrations.CreateModel(
            name="SubIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("awp_code", models.CharField(max_length=500, verbose_name="RWP Code")),
                ("target", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "aggregation_method",
                    models.CharField(
                        blank=True,
                        choices=[("SUM", "SUM"), ("AVERAGE", "AVERAGE")],
                        default="SUM",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("old_id", models.PositiveIntegerField(default=0)),
                ("sequence", models.PositiveIntegerField(default=0)),
                (
                    "sector_equivalent",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
            options={"managed": settings.LEGACY_TABLES_MANAGED, 
                "verbose_name": "sub indicator",
                "verbose_name_plural": "sub indicators",
                "db_table": "pivoting_subindicator",
                "ordering": ("awp_code", "sequence"),
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ai_id", models.PositiveIntegerField(blank=True, null=True)),
                ("ai_form_id", models.CharField(max_length=254, null=True)),
                ("name", models.CharField(max_length=1500, verbose_name="Form Name")),
                (
                    "label",
                    models.CharField(max_length=1500, verbose_name="Form Name/Label"),
                ),
                ("location_type", models.CharField(max_length=254, null=True)),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=254, null=True, verbose_name="AI Folder"
                    ),
                ),
                (
                    "ai_category_id",
                    models.CharField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="AI Folder ID",
                    ),
                ),
                (
                    "programme_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="etools.pca",
                    ),
                ),
                (
                    "programme_documents",
                    models.ManyToManyField(
                        blank=True,
                        db_table="pivoting_activity_programme_documents",
                        related_name="_pivoting_activity_programme_documents_+",
                        to="etools.pca",
                        verbose_name="programme documents",
                    ),
                ),
            ],
            options={"managed": settings.LEGACY_TABLES_MANAGED, 
                "verbose_name": "activity",
                "verbose_name_plural": "activities",
                "db_table": "pivoting_activity",
                "ordering": ("name",),
            },
        ),
    ]
