# Generated by Django 5.2.17 on 2026-09-22 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pivoting", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="database",
            name="focal_point",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="database",
            name="focal_point_sector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="database",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pdatabases",
                to="users.section",
            ),
        ),
        migrations.AddField(
            model_name="activityreportnew",
            name="dbase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pivoting.database"
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="database",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pivoting.database"
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="none_ai_database",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="pivoting.database",
                verbose_name="TBD",
            ),
        ),
        migrations.AddField(
            model_name="indicatornew",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="activity_form_indicators",
                to="pivoting.activity",
            ),
        ),
        migrations.AddField(
            model_name="indicatornew",
            name="database",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pivoting.database"
            ),
        ),
        migrations.AddField(
            model_name="masterindicator",
            name="database",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pivoting.database"
            ),
        ),
        migrations.AddField(
            model_name="masterindicator",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                db_table="pivoting_masterindicator_tags",
                to="pivoting.masterindicatortag",
                verbose_name="tags",
            ),
        ),
        migrations.AddField(
            model_name="mastersubindicator",
            name="master",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subindicators",
                to="pivoting.masterindicator",
                verbose_name="Master indicator",
            ),
        ),
        migrations.AddField(
            model_name="neuroreportcomment",
            name="report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pivoting.neuroreport",
            ),
        ),
        migrations.AddField(
            model_name="neuroreportmasterindicator",
            name="master",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pivoting.masterindicator",
            ),
        ),
        migrations.AddField(
            model_name="neuroreportmasterindicator",
            name="report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pivoting.neuroreport",
            ),
        ),
        migrations.AddField(
            model_name="neuroreportcomment",
            name="master",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pivoting.neuroreportmasterindicator",
            ),
        ),
        migrations.AddField(
            model_name="neuroreport",
            name="ryear",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pivoting.reportingyear",
            ),
        ),
        migrations.AddField(
            model_name="database",
            name="reporting_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pivoting.reportingyear",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                db_table="pivoting_resource_tags",
                to="pivoting.resourcetag",
                verbose_name="tags",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pivoting.resourcetopic",
                verbose_name="Resource Topic",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pivoting.resourcetype",
                verbose_name="Resource Type",
            ),
        ),
        migrations.AddField(
            model_name="subindicator",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pivoting.activity",
            ),
        ),
        migrations.AddField(
            model_name="subindicator",
            name="database",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pivoting.database"
            ),
        ),
        migrations.AddField(
            model_name="subindicator",
            name="indicators",
            field=models.ManyToManyField(
                blank=True,
                db_table="pivoting_subindicator_indicators",
                to="pivoting.indicatornew",
                verbose_name="Indicators",
            ),
        ),
        migrations.AddField(
            model_name="mastersubindicator",
            name="sub",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="pivoting.subindicator",
                verbose_name="Sub indicator",
            ),
        ),
    ]
