# Generated by Django 5.2.17 on 2026-10-02 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pivoting", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndicatorForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_id", models.IntegerField(blank=True, null=True)),
                ("year", models.PositiveSmallIntegerField()),
                (
                    "as_of_month",
                    models.PositiveSmallIntegerField(
                        help_text="the last settled month used (1-12)"
                    ),
                ),
                ("value_to_date", models.FloatField()),
                ("target", models.FloatField(blank=True, null=True)),
                (
                    "forecast",
                    models.FloatField(
                        blank=True, help_text="likely year-end value", null=True
                    ),
                ),
                ("low", models.FloatField(blank=True, null=True)),
                ("high", models.FloatField(blank=True, null=True)),
                (
                    "linear",
                    models.FloatField(
                        blank=True,
                        help_text="straight-line projection, for comparison",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("on_course", "On course"),
                            ("uncertain", "Uncertain"),
                            ("likely_short", "Likely to fall short"),
                            ("no_reports", "Nothing reported yet"),
                            ("too_early", "Too early to tell"),
                            ("no_target", "No target"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "basis",
                    models.CharField(
                        help_text="what the monthly pattern is based on", max_length=120
                    ),
                ),
                ("own_years", models.PositiveSmallIntegerField(default=0)),
                ("computed_at", models.DateTimeField()),
                (
                    "database",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="pivoting.database",
                    ),
                ),
                (
                    "master",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="pivoting.masterindicator",
                    ),
                ),
            ],
            options={
                "verbose_name": "indicator forecast",
                "ordering": ("database_id", "master_id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("master",), name="insights_one_forecast_per_master"
                    )
                ],
            },
        ),
    ]
