# Generated by Django 5.2.17 on 2026-09-24 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("etools", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Grant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datamart_id",
                    models.BigIntegerField(
                        help_text="the record's id in the Datamart", unique=True
                    ),
                ),
                (
                    "source_id",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="the record's id in eTools",
                        null=True,
                    ),
                ),
                (
                    "last_modify_date",
                    models.DateTimeField(
                        blank=True, help_text="changed in the Datamart", null=True
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True, default=dict, help_text="the record as received"
                    ),
                ),
                ("synced_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=128)),
                ("donor", models.CharField(blank=True, db_index=True, max_length=128)),
                ("expiry", models.DateField(blank=True, null=True)),
                ("description", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ("donor", "name"),
            },
        ),
        migrations.CreateModel(
            name="HACTAggregate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datamart_id",
                    models.BigIntegerField(
                        help_text="the record's id in the Datamart", unique=True
                    ),
                ),
                (
                    "source_id",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="the record's id in eTools",
                        null=True,
                    ),
                ),
                (
                    "last_modify_date",
                    models.DateTimeField(
                        blank=True, help_text="changed in the Datamart", null=True
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True, default=dict, help_text="the record as received"
                    ),
                ),
                ("synced_at", models.DateTimeField(auto_now=True)),
                ("year", models.IntegerField(db_index=True)),
                ("microassessments_total", models.IntegerField(default=0)),
                ("programmaticvisits_total", models.IntegerField(default=0)),
                ("followup_spotcheck", models.IntegerField(default=0)),
                ("completed_spotcheck", models.IntegerField(default=0)),
                ("completed_hact_audits", models.IntegerField(default=0)),
                ("completed_special_audits", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "HACT year",
                "ordering": ("-year",),
            },
        ),
        migrations.CreateModel(
            name="ActionPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datamart_id",
                    models.BigIntegerField(
                        help_text="the record's id in the Datamart", unique=True
                    ),
                ),
                (
                    "source_id",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="the record's id in eTools",
                        null=True,
                    ),
                ),
                (
                    "last_modify_date",
                    models.DateTimeField(
                        blank=True, help_text="changed in the Datamart", null=True
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True, default=dict, help_text="the record as received"
                    ),
                ),
                ("synced_at", models.DateTimeField(auto_now=True)),
                ("reference_number", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("status", models.CharField(blank=True, db_index=True, max_length=30)),
                ("high_priority", models.BooleanField(default=False)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("date_of_completion", models.DateTimeField(blank=True, null=True)),
                ("assigned_to_name", models.CharField(blank=True, max_length=200)),
                ("office", models.CharField(blank=True, max_length=64)),
                ("section", models.CharField(blank=True, max_length=64)),
                ("category", models.CharField(blank=True, max_length=300)),
                (
                    "related_module",
                    models.CharField(
                        blank=True, help_text="audit, tpm, fm, t2f, ...", max_length=64
                    ),
                ),
                (
                    "module_reference_number",
                    models.CharField(blank=True, max_length=300),
                ),
                ("partner_name", models.CharField(blank=True, max_length=300)),
                ("intervention_number", models.CharField(blank=True, max_length=64)),
                ("location_name", models.CharField(blank=True, max_length=254)),
                (
                    "intervention",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="datamart_action_points",
                        to="etools.pca",
                        verbose_name="programme document",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="datamart_action_points",
                        to="etools.partnerorganization",
                    ),
                ),
            ],
            options={
                "verbose_name": "action point",
                "ordering": ("-due_date",),
            },
        ),
        migrations.CreateModel(
            name="AuditEngagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datamart_id",
                    models.BigIntegerField(
                        help_text="the record's id in the Datamart", unique=True
                    ),
                ),
                (
                    "source_id",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="the record's id in eTools",
                        null=True,
                    ),
                ),
                (
                    "last_modify_date",
                    models.DateTimeField(
                        blank=True, help_text="changed in the Datamart", null=True
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True, default=dict, help_text="the record as received"
                    ),
                ),
                ("synced_at", models.DateTimeField(auto_now=True)),
                ("partner_name", models.CharField(blank=True, max_length=300)),
                (
                    "vendor_number",
                    models.CharField(blank=True, db_index=True, max_length=30),
                ),
                ("reference_number", models.CharField(blank=True, max_length=300)),
                (
                    "engagement_type",
                    models.CharField(blank=True, db_index=True, max_length=30),
                ),
                ("status", models.CharField(blank=True, db_index=True, max_length=30)),
                ("auditor", models.CharField(blank=True, max_length=255)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("date_of_field_visit", models.DateField(blank=True, null=True)),
                ("date_of_final_report", models.DateField(blank=True, null=True)),
                ("year_of_audit", models.IntegerField(blank=True, null=True)),
                (
                    "total_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "amount_tested",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "financial_findings",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("audit_opinion", models.CharField(blank=True, max_length=100)),
                ("rating", models.CharField(blank=True, max_length=100)),
                (
                    "interventions",
                    models.ManyToManyField(
                        blank=True,
                        db_constraint=False,
                        related_name="datamart_engagements",
                        to="etools.pca",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="datamart_engagements",
                        to="etools.partnerorganization",
                    ),
                ),
            ],
            options={
                "verbose_name": "audit engagement",
                "ordering": ("-start_date",),
            },
        ),
        migrations.CreateModel(
            name="FundsReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datamart_id",
                    models.BigIntegerField(
                        help_text="the record's id in the Datamart", unique=True
                    ),
                ),
                (
                    "source_id",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="the record's id in eTools",
                        null=True,
                    ),
                ),
                (
                    "last_modify_date",
                    models.DateTimeField(
                        blank=True, help_text="changed in the Datamart", null=True
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True, default=dict, help_text="the record as received"
                    ),
                ),
                ("synced_at", models.DateTimeField(auto_now=True)),
                ("pd_reference_number", models.CharField(blank=True, max_length=256)),
                (
                    "fr_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=20,
                        verbose_name="FR number",
                    ),
                ),
                ("line_item", models.IntegerField(blank=True, null=True)),
                ("line_item_text", models.CharField(blank=True, max_length=255)),
                ("fr_type", models.CharField(blank=True, max_length=50)),
                ("vendor_code", models.CharField(blank=True, max_length=20)),
                ("donor", models.CharField(blank=True, db_index=True, max_length=256)),
                ("donor_code", models.CharField(blank=True, max_length=30)),
                (
                    "grant_number",
                    models.CharField(blank=True, db_index=True, max_length=20),
                ),
                ("fund", models.CharField(blank=True, max_length=10)),
                (
                    "wbs",
                    models.CharField(blank=True, max_length=30, verbose_name="WBS"),
                ),
                ("currency", models.CharField(blank=True, max_length=50)),
                (
                    "overall_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="line amount (USD)",
                    ),
                ),
                (
                    "overall_amount_dc",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="line amount (document currency)",
                    ),
                ),
                (
                    "total_amt",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="FR total",
                    ),
                ),
                (
                    "intervention_amt",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="FR amount for the PD",
                    ),
                ),
                (
                    "actual_amt",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="FR actual (disbursed)",
                    ),
                ),
                (
                    "outstanding_amt",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="FR outstanding",
                    ),
                ),
                ("document_date", models.DateField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("completed_flag", models.BooleanField(default=False)),
                (
                    "intervention",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="funds_reservations",
                        to="etools.pca",
                        verbose_name="programme document",
                    ),
                ),
            ],
            options={
                "verbose_name": "funds reservation line",
                "ordering": ("fr_number", "line_item"),
            },
        ),
        migrations.CreateModel(
            name="MonitoringFinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datamart_id",
                    models.BigIntegerField(
                        help_text="the record's id in the Datamart", unique=True
                    ),
                ),
                (
                    "source_id",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="the record's id in eTools",
                        null=True,
                    ),
                ),
                (
                    "last_modify_date",
                    models.DateTimeField(
                        blank=True, help_text="changed in the Datamart", null=True
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True, default=dict, help_text="the record as received"
                    ),
                ),
                ("synced_at", models.DateTimeField(auto_now=True)),
                (
                    "vendor_number",
                    models.CharField(blank=True, db_index=True, max_length=30),
                ),
                ("entity", models.CharField(blank=True, max_length=255)),
                ("entity_type", models.CharField(blank=True, max_length=100)),
                ("monitoring_activity", models.CharField(blank=True, max_length=64)),
                ("reference_number", models.CharField(blank=True, max_length=100)),
                ("status", models.CharField(blank=True, max_length=20)),
                (
                    "overall_finding_rating",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                ("narrative_finding", models.TextField(blank=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("location_name", models.CharField(blank=True, max_length=254)),
                ("site", models.CharField(blank=True, max_length=254)),
                ("is_programmatic_visit", models.BooleanField(default=False)),
                ("is_remote_monitoring", models.BooleanField(default=False)),
                ("visit_lead", models.CharField(blank=True, max_length=254)),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="monitoring_findings",
                        to="etools.partnerorganization",
                    ),
                ),
            ],
            options={
                "verbose_name": "field monitoring finding",
                "ordering": ("-end_date",),
            },
        ),
        migrations.CreateModel(
            name="PartnerAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datamart_id",
                    models.BigIntegerField(
                        help_text="the record's id in the Datamart", unique=True
                    ),
                ),
                (
                    "source_id",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="the record's id in eTools",
                        null=True,
                    ),
                ),
                (
                    "last_modify_date",
                    models.DateTimeField(
                        blank=True, help_text="changed in the Datamart", null=True
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True, default=dict, help_text="the record as received"
                    ),
                ),
                ("synced_at", models.DateTimeField(auto_now=True)),
                ("partner_name", models.CharField(blank=True, max_length=300)),
                (
                    "vendor_number",
                    models.CharField(blank=True, db_index=True, max_length=30),
                ),
                ("type", models.CharField(blank=True, max_length=50)),
                ("rating", models.CharField(blank=True, max_length=50)),
                ("requested_date", models.DateField(blank=True, null=True)),
                ("planned_date", models.DateField(blank=True, null=True)),
                ("completed_date", models.DateField(blank=True, null=True)),
                ("current", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="datamart_assessments",
                        to="etools.partnerorganization",
                    ),
                ),
            ],
            options={
                "verbose_name": "partner assessment",
                "ordering": ("-completed_date",),
            },
        ),
        migrations.CreateModel(
            name="PDIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datamart_id",
                    models.BigIntegerField(
                        help_text="the record's id in the Datamart", unique=True
                    ),
                ),
                (
                    "source_id",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="the record's id in eTools",
                        null=True,
                    ),
                ),
                (
                    "last_modify_date",
                    models.DateTimeField(
                        blank=True, help_text="changed in the Datamart", null=True
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True, default=dict, help_text="the record as received"
                    ),
                ),
                ("synced_at", models.DateTimeField(auto_now=True)),
                (
                    "pd_reference_number",
                    models.CharField(blank=True, db_index=True, max_length=256),
                ),
                ("title", models.CharField(blank=True, max_length=1024)),
                ("unit", models.CharField(blank=True, max_length=10)),
                ("display_type", models.CharField(blank=True, max_length=10)),
                (
                    "baseline_numerator",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "baseline_denominator",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "target_numerator",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "target_denominator",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("section_name", models.CharField(blank=True, max_length=128)),
                (
                    "lower_result_name",
                    models.CharField(blank=True, max_length=500, verbose_name="output"),
                ),
                ("cluster_name", models.CharField(blank=True, max_length=512)),
                ("location_name", models.CharField(blank=True, max_length=254)),
                ("location_pcode", models.CharField(blank=True, max_length=32)),
                ("disaggregation_name", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("is_high_frequency", models.BooleanField(default=False)),
                (
                    "intervention",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pd_indicators",
                        to="etools.pca",
                        verbose_name="programme document",
                    ),
                ),
            ],
            options={
                "verbose_name": "PD indicator",
                "ordering": ("pd_reference_number", "title"),
            },
        ),
        migrations.CreateModel(
            name="PSEAAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datamart_id",
                    models.BigIntegerField(
                        help_text="the record's id in the Datamart", unique=True
                    ),
                ),
                (
                    "source_id",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="the record's id in eTools",
                        null=True,
                    ),
                ),
                (
                    "last_modify_date",
                    models.DateTimeField(
                        blank=True, help_text="changed in the Datamart", null=True
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True, default=dict, help_text="the record as received"
                    ),
                ),
                ("synced_at", models.DateTimeField(auto_now=True)),
                ("partner_name", models.CharField(blank=True, max_length=255)),
                (
                    "vendor_number",
                    models.CharField(blank=True, db_index=True, max_length=30),
                ),
                ("reference_number", models.CharField(blank=True, max_length=100)),
                ("overall_rating", models.IntegerField(blank=True, null=True)),
                ("assessment_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=30)),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="psea_assessments",
                        to="etools.partnerorganization",
                    ),
                ),
            ],
            options={
                "verbose_name": "PSEA assessment",
                "verbose_name_plural": "PSEA assessments",
                "ordering": ("-assessment_date",),
            },
        ),
        migrations.CreateModel(
            name="TPMVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datamart_id",
                    models.BigIntegerField(
                        help_text="the record's id in the Datamart", unique=True
                    ),
                ),
                (
                    "source_id",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="the record's id in eTools",
                        null=True,
                    ),
                ),
                (
                    "last_modify_date",
                    models.DateTimeField(
                        blank=True, help_text="changed in the Datamart", null=True
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True, default=dict, help_text="the record as received"
                    ),
                ),
                ("synced_at", models.DateTimeField(auto_now=True)),
                ("partner_name", models.CharField(blank=True, max_length=300)),
                (
                    "vendor_number",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("reference_number", models.CharField(blank=True, max_length=300)),
                ("status", models.CharField(blank=True, db_index=True, max_length=300)),
                (
                    "tpm_name",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="TPM partner"
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("date_of_unicef_approved", models.DateField(blank=True, null=True)),
                ("author_name", models.CharField(blank=True, max_length=120)),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tpm_visits",
                        to="etools.partnerorganization",
                    ),
                ),
            ],
            options={
                "verbose_name": "TPM visit",
                "ordering": ("-start_date",),
            },
        ),
    ]
