# Generated by Django 5.2.17 on 2026-09-24 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamart", "0002_more_datasets"),
        ("etools", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatamartDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset", models.CharField(db_index=True, max_length=64)),
                ("record_key", models.CharField(max_length=64)),
                (
                    "source_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                ("title", models.CharField(blank=True, max_length=500)),
                (
                    "date",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="the record's main date",
                        null=True,
                    ),
                ),
                ("data", models.JSONField(blank=True, default=dict)),
                ("synced_at", models.DateTimeField(auto_now=True)),
                (
                    "intervention",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="datamart_documents",
                        to="etools.pca",
                        verbose_name="programme document",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="datamart_documents",
                        to="etools.partnerorganization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Datamart record",
                "ordering": ("dataset", "-date"),
                "indexes": [
                    models.Index(
                        fields=["dataset", "partner"],
                        name="datamart_da_dataset_1784e5_idx",
                    ),
                    models.Index(
                        fields=["dataset", "intervention"],
                        name="datamart_da_dataset_8b8053_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dataset", "record_key"), name="datamart_document_key"
                    )
                ],
            },
        ),
    ]
