# Generated by Django 5.2.17 on 2026-09-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamart", "0003_documents"),
        ("etools", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdindicator",
            name="denominator_label",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name="pdindicator",
            name="location_level",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pdindicator",
            name="location_levelname",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="pdindicator",
            name="location_source_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pdindicator",
            name="means_of_verification",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="pdindicator",
            name="numerator_label",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name="pdindicator",
            name="tag_age_group",
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AddField(
            model_name="pdindicator",
            name="tag_disability",
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AddField(
            model_name="pdindicator",
            name="tag_gender",
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AddField(
            model_name="pdindicator",
            name="tag_nationality",
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AddField(
            model_name="reportedindicator",
            name="admin_level",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reportedindicator",
            name="calculation_across_locations",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="reportedindicator",
            name="calculation_across_periods",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="reportedindicator",
            name="disaggregation",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="reportedindicator",
            name="etools_indicator_id",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="reportedindicator",
            name="etools_pd_result_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="reportedindicator",
            name="high_frequency",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reportedindicator",
            name="narrative_assessment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="reportedindicator",
            name="previous_location_progress",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="reportedindicator",
            name="tag_age_group",
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AddField(
            model_name="reportedindicator",
            name="tag_disability",
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AddField(
            model_name="reportedindicator",
            name="tag_gender",
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AddField(
            model_name="reportedindicator",
            name="tag_nationality",
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AddIndex(
            model_name="pdindicator",
            index=models.Index(
                fields=["intervention", "title"], name="datamart_pd_interve_636441_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportedindicator",
            index=models.Index(
                fields=["intervention", "indicator"],
                name="datamart_re_interve_cc708f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reportedindicator",
            index=models.Index(
                fields=["report_type", "period_end"],
                name="datamart_re_report__bc862d_idx",
            ),
        ),
    ]
