# Generated by Django 5.2.17 on 2026-09-25 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamart", "0004_indicator_monitoring"),
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionpoint",
            name="engagement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="datamart_action_points",
                to="datamart.auditengagement",
            ),
        ),
        migrations.AddField(
            model_name="actionpoint",
            name="engagement_source_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="actionpoint",
            name="location",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="datamart_action_points",
                to="locations.location",
                verbose_name="eTools location",
            ),
        ),
        migrations.AddField(
            model_name="actionpoint",
            name="location_level",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="actionpoint",
            name="location_levelname",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="actionpoint",
            name="location_pcode",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="actionpoint",
            name="location_source_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="actionpoint",
            name="related_module_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="actionpoint",
            name="tpm_activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="action_points",
                to="datamart.tpmactivity",
            ),
        ),
        migrations.AddField(
            model_name="actionpoint",
            name="tpm_activity_source_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="actionpoint",
            name="travel_activity_source_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="monitoringfinding",
            name="location",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="monitoring_findings",
                to="locations.location",
                verbose_name="eTools location",
            ),
        ),
        migrations.AddField(
            model_name="monitoringfinding",
            name="location_pcode",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="monitoringfinding",
            name="location_source_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="monitoringfinding",
            name="monitoring_activity_id",
            field=models.BigIntegerField(
                blank=True, help_text="eTools activity id", null=True
            ),
        ),
        migrations.AddField(
            model_name="pdindicator",
            name="location",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pd_indicators",
                to="locations.location",
                verbose_name="eTools location",
            ),
        ),
        migrations.AddField(
            model_name="programmaticvisit",
            name="location",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="programmatic_visits",
                to="locations.location",
                verbose_name="eTools location",
            ),
        ),
        migrations.AddField(
            model_name="reportedindicator",
            name="location_ref",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reported_indicators",
                to="locations.location",
                verbose_name="eTools location",
            ),
        ),
        migrations.AddField(
            model_name="tpmactivity",
            name="location_links",
            field=models.ManyToManyField(
                blank=True,
                db_constraint=False,
                related_name="tpm_activities",
                to="locations.location",
            ),
        ),
        migrations.AddField(
            model_name="tpmactivity",
            name="location_pcodes",
            field=models.JSONField(
                blank=True, default=list, help_text="P-codes of the places monitored"
            ),
        ),
        migrations.AddField(
            model_name="tpmactivity",
            name="visit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activities",
                to="datamart.tpmvisit",
            ),
        ),
        migrations.CreateModel(
            name="MonitoringSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datamart_id",
                    models.BigIntegerField(
                        help_text="the record's id in the Datamart", unique=True
                    ),
                ),
                (
                    "source_id",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="the record's id in eTools",
                        null=True,
                    ),
                ),
                (
                    "last_modify_date",
                    models.DateTimeField(
                        blank=True, help_text="changed in the Datamart", null=True
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True, default=dict, help_text="the record as received"
                    ),
                ),
                ("synced_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=254)),
                ("p_code", models.CharField(blank=True, db_index=True, max_length=32)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("parent_pcode", models.CharField(blank=True, max_length=32)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="monitoring_sites",
                        to="locations.location",
                        verbose_name="eTools location",
                    ),
                ),
            ],
            options={
                "verbose_name": "monitoring site",
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="monitoringfinding",
            name="monitoring_site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="findings",
                to="datamart.monitoringsite",
            ),
        ),
    ]
