# Generated by Django 5.2.17 on 2026-09-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamart", "0005_etools_locations"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndicatorFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("etools", "eTools PD indicator"),
                            ("activityinfo", "ActivityInfo master indicator"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="eTools indicator id (source_id) or ActivityInfo master indicator id",
                        max_length=64,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="the indicator title, for the list",
                        max_length=1024,
                    ),
                ),
                ("counts_children", models.BooleanField(default=True)),
                ("note", models.CharField(blank=True, max_length=500)),
                ("updated_by", models.CharField(blank=True, max_length=150)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "children indicator flag",
                "verbose_name_plural": "children indicator flags",
                "ordering": ("source", "label"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "key"), name="datamart_indicatorflag_key"
                    )
                ],
            },
        ),
    ]
