# Generated by Django 5.2.17 on 2026-09-29 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datamart", "0006_indicator_flag"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="programmaticvisit",
            options={
                "ordering": ("-date",),
                "verbose_name": "staff trip activity",
                "verbose_name_plural": "staff trip activities",
            },
        ),
    ]
