# Generated by Django 5.2.17 on 2026-10-05 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamart", "0007_staff_trip_plural"),
        ("etools", "0003_partnerlink"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitoringfinding",
            name="intervention",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="monitoring_findings",
                to="etools.pca",
                verbose_name="programme document",
            ),
        ),
        migrations.AddField(
            model_name="monitoringfinding",
            name="pd_match",
            field=models.CharField(
                blank=True,
                help_text="how the programme document was found: exact, token, base, title, or blank",
                max_length=8,
            ),
        ),
    ]
