# Generated by Django 5.2.17 on 2026-10-01 15:05

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("partner", "Partner"),
                            ("programme_document", "Programme document"),
                            ("donor", "Donor"),
                            ("grant", "Grant"),
                            ("section", "Section"),
                            ("governorate", "Governorate"),
                            ("district", "District"),
                            ("database", "ActivityInfo database"),
                            ("master_indicator", "ActivityInfo master indicator"),
                            ("report", "Neuro / HPM report"),
                            ("cpd_cycle", "Country programme cycle"),
                            ("cpd_outcome", "Country programme outcome"),
                            ("cpd_output", "Country programme output"),
                            ("cpd_indicator", "Country programme indicator"),
                            ("youth_indicator", "Youth indicator (Compiler)"),
                            ("education_programme", "Education programme (Compiler)"),
                            ("makani_centre", "Makani centre"),
                            ("document", "Document (knowledge base, library, CPD)"),
                            ("map", "Map"),
                            ("review_finding", "Daily review finding"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "key",
                    models.CharField(help_text="the id in its source", max_length=120),
                ),
                ("name", models.CharField(max_length=500)),
                (
                    "aliases",
                    models.TextField(
                        blank=True,
                        help_text="other names, codes and numbers it is known by",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("url", models.CharField(blank=True, max_length=300)),
                (
                    "attrs",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="a few facts that identify it (year, status…)",
                    ),
                ),
                (
                    "lookup",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="the assistant lookup that gives its figures: {tool, args}",
                    ),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(null=True),
                ),
                ("built_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "knowledge hub entity",
                "verbose_name_plural": "knowledge hub entities",
                "ordering": ("kind", "name"),
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"], name="graph_entity_search"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "key"), name="graph_entity_kind_key"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Edge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relation",
                    models.CharField(
                        help_text="read as: source <relation> target", max_length=40
                    ),
                ),
                (
                    "origin",
                    models.CharField(help_text="the data that says so", max_length=40),
                ),
                (
                    "weight",
                    models.FloatField(
                        default=1, help_text="e.g. how many records or mentions"
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="out_edges",
                        to="graph.entity",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_edges",
                        to="graph.entity",
                    ),
                ),
            ],
            options={
                "verbose_name": "knowledge hub link",
                "indexes": [
                    models.Index(
                        fields=["target", "relation"],
                        name="graph_edge_target__44b374_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "target", "relation"),
                        name="graph_edge_unique",
                    )
                ],
            },
        ),
    ]
