# Generated by Django 5.2.17 on 2026-10-01 16:06

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_whats_new_job"),
        ("graph", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RefreshRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("reason", models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name="edge",
            name="builder",
            field=models.CharField(
                blank=True,
                help_text="the source that added it to the hub",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="builder",
            field=models.CharField(
                blank=True,
                help_text="the source that added it to the hub",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="snapshot",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="headline figures at the last build, kept to notice changes",
            ),
        ),
        migrations.CreateModel(
            name="Digest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("section_id", models.IntegerField(blank=True, null=True)),
                ("section_name", models.CharField(blank=True, max_length=200)),
                ("text", models.TextField()),
                (
                    "written_by",
                    models.CharField(help_text="the AI model, or template", max_length=100),
                ),
                ("changes", models.PositiveIntegerField(default=0)),
                ("emailed_to", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "what's new note",
                "ordering": ("-date", "section_name"),
                "constraints": [
                    models.UniqueConstraint(fields=("date", "section_id"), name="graph_digest_one_per_day"),
                    models.UniqueConstraint(
                        condition=models.Q(("section_id__isnull", True)),
                        fields=("date",),
                        name="graph_digest_one_overall",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DigestSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="digest",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "what's new email",
            },
        ),
        migrations.CreateModel(
            name="Change",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("detected_at", models.DateTimeField(db_index=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("partner", "Partner"),
                            ("programme_document", "Programme document"),
                            ("donor", "Donor"),
                            ("grant", "Grant"),
                            ("section", "Section"),
                            ("governorate", "Governorate"),
                            ("district", "District"),
                            ("database", "ActivityInfo database"),
                            ("master_indicator", "ActivityInfo master indicator"),
                            ("report", "Neuro / HPM report"),
                            ("cpd_cycle", "Country programme cycle"),
                            ("cpd_outcome", "Country programme outcome"),
                            ("cpd_output", "Country programme output"),
                            ("cpd_indicator", "Country programme indicator"),
                            ("youth_indicator", "Youth indicator (Compiler)"),
                            ("education_programme", "Education programme (Compiler)"),
                            ("makani_centre", "Makani centre"),
                            ("document", "Document (knowledge base, library, CPD)"),
                            ("map", "Map"),
                            ("review_finding", "Daily review finding"),
                        ],
                        max_length=24,
                    ),
                ),
                ("key", models.CharField(max_length=120)),
                ("name", models.CharField(max_length=500)),
                ("url", models.CharField(blank=True, max_length=300)),
                (
                    "op",
                    models.CharField(
                        choices=[
                            ("added", "New"),
                            ("changed", "Changed"),
                            ("removed", "Gone"),
                            ("linked", "Newly linked"),
                            ("unlinked", "No longer linked"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "fields",
                    models.JSONField(blank=True, default=dict, help_text="{field: [before, after]}"),
                ),
                (
                    "link",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="the link that appeared or went",
                    ),
                ),
                (
                    "sections",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        help_text="section ids it concerns",
                        size=None,
                    ),
                ),
                ("notable", models.BooleanField(db_index=True, default=False)),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="changes",
                        to="graph.entity",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.syncrun",
                    ),
                ),
            ],
            options={
                "ordering": ("-detected_at", "-id"),
                "indexes": [
                    models.Index(fields=["kind", "key"], name="graph_chang_kind_8bd18f_idx"),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["sections"], name="graph_change_sections"
                    ),
                ],
            },
        ),
    ]
