# Generated by Django 5.2.17 on 2026-10-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graph", "0002_whats_new"),
    ]

    operations = [
        migrations.AlterField(
            model_name="change",
            name="kind",
            field=models.CharField(
                choices=[
                    ("partner", "Partner"),
                    ("programme_document", "Programme document"),
                    ("donor", "Donor"),
                    ("grant", "Grant"),
                    ("section", "Section"),
                    ("governorate", "Governorate"),
                    ("district", "District"),
                    ("database", "ActivityInfo database"),
                    ("master_indicator", "ActivityInfo master indicator"),
                    ("report", "Neuro / HPM report"),
                    ("cpd_cycle", "Country programme cycle"),
                    ("cpd_outcome", "Country programme outcome"),
                    ("cpd_output", "Country programme output"),
                    ("cpd_indicator", "Country programme indicator"),
                    ("youth_indicator", "Youth indicator (Compiler)"),
                    ("education_programme", "Education programme (Compiler)"),
                    ("makani_centre", "Makani centre"),
                    ("document", "Document (knowledge base, library, CPD)"),
                    ("map", "Map"),
                    ("review_finding", "Daily review finding"),
                    ("fm_visit", "Field monitoring visit"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="kind",
            field=models.CharField(
                choices=[
                    ("partner", "Partner"),
                    ("programme_document", "Programme document"),
                    ("donor", "Donor"),
                    ("grant", "Grant"),
                    ("section", "Section"),
                    ("governorate", "Governorate"),
                    ("district", "District"),
                    ("database", "ActivityInfo database"),
                    ("master_indicator", "ActivityInfo master indicator"),
                    ("report", "Neuro / HPM report"),
                    ("cpd_cycle", "Country programme cycle"),
                    ("cpd_outcome", "Country programme outcome"),
                    ("cpd_output", "Country programme output"),
                    ("cpd_indicator", "Country programme indicator"),
                    ("youth_indicator", "Youth indicator (Compiler)"),
                    ("education_programme", "Education programme (Compiler)"),
                    ("makani_centre", "Makani centre"),
                    ("document", "Document (knowledge base, library, CPD)"),
                    ("map", "Map"),
                    ("review_finding", "Daily review finding"),
                    ("fm_visit", "Field monitoring visit"),
                ],
                max_length=24,
            ),
        ),
    ]
