# Generated by Django 5.2.17 on 2026-10-04 13:38

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DetectorSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "detector",
                    models.CharField(max_length=40, unique=True, verbose_name="check"),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("trial", "Trial: whole-country view only"),
                            ("on", "On: told to staff"),
                            ("off", "Off"),
                        ],
                        default="trial",
                        max_length=8,
                    ),
                ),
                (
                    "on_since",
                    models.DateField(
                        blank=True,
                        help_text="items found before this day were known already: not announced",
                        null=True,
                    ),
                ),
                (
                    "demoted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="when it went back to trial by itself",
                        null=True,
                    ),
                ),
                ("demoted_reason", models.CharField(blank=True, max_length=300)),
                ("updated_by", models.CharField(blank=True, max_length=150)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "NeuroDB Watch check",
                "verbose_name_plural": "NeuroDB Watch: checks",
                "ordering": ("detector",),
            },
        ),
        migrations.CreateModel(
            name="WatchRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("reason", models.CharField(max_length=120)),
            ],
            options={
                "ordering": ("pk",),
            },
        ),
        migrations.CreateModel(
            name="WatchState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_change_id",
                    models.BigIntegerField(
                        default=0,
                        help_text="the last What's new change read; moves only to the highest id read",
                    ),
                ),
                ("last_daily_on", models.DateField(blank=True, null=True)),
                ("quick_passes_on", models.DateField(blank=True, null=True)),
                ("quick_passes_count", models.PositiveSmallIntegerField(default=0)),
                ("ai_paused_until", models.DateTimeField(blank=True, null=True)),
                ("ai_pause_reason", models.CharField(blank=True, max_length=200)),
                ("consecutive_ai_errors", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "NeuroDB Watch state",
            },
        ),
        migrations.CreateModel(
            name="SectionMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "etools_name",
                    models.CharField(
                        max_length=300, unique=True, verbose_name="eTools section name"
                    ),
                ),
                (
                    "how",
                    models.CharField(
                        choices=[
                            ("exact", "Same name"),
                            ("code", "Same code"),
                            ("contains", "Name contains the other"),
                            ("manual", "Set by an administrator"),
                            ("none", "No match"),
                        ],
                        default="none",
                        max_length=16,
                    ),
                ),
                ("confirmed", models.BooleanField(default=False)),
                ("updated_by", models.CharField(blank=True, max_length=150)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="watch_matches",
                        to="users.section",
                        verbose_name="NeuroDB section",
                    ),
                ),
            ],
            options={
                "verbose_name": "eTools section name",
                "verbose_name_plural": "eTools section names",
                "ordering": ("etools_name",),
            },
        ),
        migrations.CreateModel(
            name="WatchItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="built from lasting identifiers",
                        max_length=320,
                        unique=True,
                    ),
                ),
                (
                    "detector",
                    models.CharField(
                        db_index=True,
                        help_text="the check that found it",
                        max_length=40,
                        verbose_name="check",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("deadline", "Deadline"),
                            ("concern", "Concern"),
                            ("system", "System"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("warning", "Warning"),
                            ("info", "To note"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "confidence",
                    models.CharField(
                        choices=[
                            ("sure", "Sure"),
                            ("likely", "Likely"),
                            ("check", "Please check"),
                        ],
                        default="sure",
                        max_length=16,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="carries dates, never day counts", max_length=300
                    ),
                ),
                ("detail", models.TextField(blank=True)),
                ("url", models.CharField(blank=True, max_length=500)),
                ("due_date", models.DateField(blank=True, db_index=True, null=True)),
                (
                    "etools_sections",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=300),
                        blank=True,
                        default=list,
                        help_text="the eTools section names",
                        size=None,
                    ),
                ),
                (
                    "section_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        help_text="NeuroDB sections, from the confirmed eTools section names",
                        size=None,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("section", "Its sections"),
                            ("country", "Whole country"),
                            ("admins", "Administrators"),
                        ],
                        default="section",
                        max_length=16,
                    ),
                ),
                (
                    "entity_kind",
                    models.CharField(
                        blank=True,
                        help_text="the knowledge hub kind it is about",
                        max_length=24,
                    ),
                ),
                (
                    "entity_key",
                    models.CharField(
                        blank=True,
                        help_text="the knowledge hub key it is about",
                        max_length=120,
                    ),
                ),
                (
                    "related",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="at most 8 of {kind, key, name, url}",
                    ),
                ),
                (
                    "situation_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="the situation it belongs to, e.g. partner:1234",
                        max_length=160,
                    ),
                ),
                (
                    "review_key",
                    models.CharField(
                        blank=True,
                        help_text="the daily review finding it hands over to",
                        max_length=300,
                    ),
                ),
                (
                    "evidence",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"source", "source_job", "synced_at", "records": [{label, date, value, url}], "numbers": {}}',
                    ),
                ),
                ("evidence_hash", models.CharField(blank=True, max_length=40)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("gone", "No longer seen"),
                            ("wrong", "Marked wrong"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=16,
                    ),
                ),
                ("close_reason", models.CharField(blank=True, max_length=300)),
                ("first_seen_on", models.DateField()),
                ("last_seen_on", models.DateField()),
                (
                    "changed_on",
                    models.DateField(
                        help_text="when its severity, due date or state last changed"
                    ),
                ),
                ("closed_on", models.DateField(blank=True, null=True)),
                (
                    "missed_runs",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="fresh daily runs in a row that did not find it",
                    ),
                ),
                (
                    "source_mark",
                    models.CharField(
                        blank=True,
                        help_text="how fresh its source was when last seen; compared as text (an ISO date or time)",
                        max_length=40,
                    ),
                ),
                (
                    "story",
                    models.JSONField(
                        blank=True, default=list, help_text="at most 30 of {on, text}"
                    ),
                ),
                ("has_owner", models.BooleanField(default=False)),
                ("assignment_status", models.CharField(blank=True, max_length=16)),
                (
                    "looked_up",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="what NeuroDB looked up (AI): {text, numbers, tools, at}",
                    ),
                ),
            ],
            options={
                "verbose_name": "thing followed",
                "verbose_name_plural": "NeuroDB Watch: things followed",
                "ordering": ("due_date", "key"),
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["section_ids"], name="watch_item_sections"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WatchNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "audience_key",
                    models.CharField(
                        help_text="section:<id> or country", max_length=40
                    ),
                ),
                ("audience_name", models.CharField(blank=True, max_length=200)),
                (
                    "sentences",
                    models.JSONField(
                        blank=True, default=list, help_text="[{text, keys}]"
                    ),
                ),
                ("text", models.TextField(blank=True)),
                (
                    "written_by",
                    models.CharField(
                        help_text="the AI model, or template", max_length=100
                    ),
                ),
                (
                    "ai_skipped_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "AI used"),
                            ("off", "AI switched off"),
                            ("budget", "Daily limit reached"),
                            ("paused", "AI paused"),
                            ("quota", "OpenAI credit ran out"),
                            ("error", "AI did not answer"),
                            ("no_change", "Nothing changed"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                ("input_hash", models.CharField(blank=True, max_length=64)),
                ("item_keys", models.JSONField(blank=True, default=list)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("cached_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "morning note",
                "verbose_name_plural": "Morning notes (For you)",
                "ordering": ("-date", "audience_name"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("date", "audience_key"),
                        name="watch_note_one_per_audience",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WatchDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "channel",
                    models.CharField(
                        choices=[("email_daily", "Morning email")],
                        default="email_daily",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.CharField(blank=True, max_length=500)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watch_deliveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "morning email sent",
                "ordering": ("-date", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "date", "channel"),
                        name="watch_delivery_once_a_day",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WatchReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_told_on", models.DateField()),
                ("last_told_on", models.DateField()),
                (
                    "told_step",
                    models.CharField(
                        help_text="known, new, a milestone (days left), overdue, worse, still_open or resolved",
                        max_length=16,
                    ),
                ),
                (
                    "milestone_count",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="milestones told, at most 3"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("needs_you", "Needs you"),
                            ("good_to_know", "Good to know"),
                        ],
                        default="good_to_know",
                        max_length=16,
                    ),
                ),
                ("seen_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reaction",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "No reaction"),
                            ("useful", "Useful"),
                            ("not_useful", "Not useful"),
                            ("done", "Done"),
                            ("not_mine", "Not mine"),
                            ("wrong", "Something's wrong"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                ("reacted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "comment",
                    models.CharField(
                        blank=True,
                        help_text="seen by administrators only; never sent to the AI or by email",
                        max_length=300,
                    ),
                ),
                ("snoozed_until", models.DateField(blank=True, null=True)),
                ("emailed_on", models.DateField(blank=True, null=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to="watch.watchitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watch_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "what a person was told",
                "verbose_name_plural": "NeuroDB Watch: what people were told",
                "ordering": ("-last_told_on", "id"),
                "indexes": [
                    models.Index(
                        fields=["user", "-last_told_on"], name="watch_receipt_user_told"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "item"), name="watch_receipt_one_per_person"
                    )
                ],
            },
        ),
    ]
