"""GENERATED by scripts/gen_legacy_models.py from the v2 schema. Do not edit by hand.

These models map onto the existing NeuroDB tables so that all historical data stays in
place. They are unmanaged in production (LEGACY_MANAGED=False): Django never creates,
alters or drops these tables. Tests set LEGACY_MANAGED=True so the test database can be
built from these definitions.
"""
from django.conf import settings
from django.contrib.postgres.fields import ArrayField
from django.db import models
from django.utils import timezone

LEGACY_MANAGED = getattr(settings, "LEGACY_TABLES_MANAGED", False)

class ActivityReportNew(models.Model):
    """Maps to the v2 table ``pivoting_activityreportnew`` (read/write, schema owned by the database)."""
    id = models.BigAutoField(verbose_name='ID', primary_key=True)
    created = models.DateTimeField(default=timezone.now, editable=False, verbose_name='created')
    modified = models.DateTimeField(auto_now=True, editable=False, verbose_name='modified')
    form = models.CharField(max_length=1000, blank=True, null=True, db_index=True)
    indicator_id = models.CharField(max_length=250, blank=True, null=True, db_index=True)
    indicator_name = models.CharField(max_length=1000, blank=True, null=True, db_index=True)
    indicator_value = models.FloatField(verbose_name='Value', blank=True, null=True)
    indicator_awp_code = models.CharField(max_length=254, blank=True, null=True, db_index=True)
    location_adminlevel_cadastral_area = models.CharField(max_length=250, blank=True, null=True, db_index=True)
    location_adminlevel_cadastral_area_code = models.CharField(max_length=250, blank=True, null=True, db_index=True)
    location_adminlevel_caza = models.CharField(max_length=250, blank=True, null=True, db_index=True)
    location_adminlevel_caza_code = models.CharField(max_length=250, blank=True, null=True, db_index=True)
    location_adminlevel_governorate = models.CharField(max_length=250, blank=True, null=True, db_index=True)
    location_adminlevel_governorate_code = models.CharField(max_length=250, blank=True, null=True, db_index=True)
    location_alternate_name = models.CharField(max_length=250, blank=True, null=True)
    location_latitude = models.CharField(max_length=250, blank=True, null=True)
    location_longitude = models.CharField(max_length=250, blank=True, null=True)
    location_name = models.CharField(verbose_name='Location', max_length=250, blank=True, null=True)
    partner_description = models.CharField(max_length=250, blank=True, null=True)
    partner_id = models.CharField(max_length=250, blank=True, null=True, db_index=True)
    partner_label = models.CharField(verbose_name='Partner', max_length=250, blank=True, null=True, db_index=True)
    project_description = models.CharField(max_length=250, blank=True, null=True)
    project_label = models.CharField(verbose_name='Project', max_length=250, blank=True, null=True, db_index=True)
    funded_by = models.CharField(max_length=250, blank=True, null=True, db_index=True)
    report_id = models.CharField(max_length=250, blank=True, null=True, db_index=True)
    database_ai_id = models.CharField(max_length=250, blank=True, null=True, db_index=True)
    dbase = models.ForeignKey('pivoting.Database', on_delete=models.CASCADE)
    ai_folder = models.CharField(max_length=250, blank=True, null=True, db_index=True)
    month = models.CharField(max_length=250, blank=True, null=True, db_index=True)
    month_name = models.CharField(max_length=250, blank=True, null=True, db_index=True)
    reporting_section = models.CharField(max_length=250, blank=True, null=True, db_index=True)
    support_covid = models.BooleanField(default=False)
    last_edited_time = models.DateTimeField(blank=True, null=True)
    parent_form = models.CharField(max_length=250, blank=True, null=True, db_index=True)
    project_plan = models.CharField(max_length=250, blank=True, null=True, db_index=True)
    project = models.CharField(max_length=250, blank=True, null=True, db_index=True)
    emergency = models.CharField(max_length=10, blank=True, null=True, default='no')

    class Meta:
        app_label = 'pivoting'
        db_table = 'pivoting_activityreportnew'
        managed = LEGACY_MANAGED
        verbose_name = 'activity report new'
        verbose_name_plural = 'activity report news'

    def __str__(self):
        return f'ActivityReportNew {self.pk}'
