# Generated by Django 5.2.17 on 2026-09-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EducationFigures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "programme",
                    models.CharField(
                        help_text="Compiler's programme key, e.g. mscc", max_length=32
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        help_text="the year (Makani) or round (Bridging)", max_length=64
                    ),
                ),
                (
                    "counted_at",
                    models.DateTimeField(
                        blank=True, help_text="when Compiler counted", null=True
                    ),
                ),
                ("fetched_at", models.DateTimeField()),
                ("payload", models.JSONField()),
            ],
            options={
                "verbose_name": "education figures",
                "verbose_name_plural": "education figures",
                "ordering": ("programme", "-year"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("programme", "year"), name="education_figures_unique"
                    )
                ],
            },
        ),
    ]
