# Generated by Django 5.2.17 on 2026-09-28 19:13

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DonorAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="shown as the page title",
                        max_length=200,
                        verbose_name="donor name",
                    ),
                ),
                (
                    "donors",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=256),
                        help_text="the donor names as eTools writes them on funds reservation lines",
                        size=None,
                    ),
                ),
                (
                    "grants",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=30),
                        blank=True,
                        default=list,
                        help_text="only these grant numbers; empty: every grant of the donors above",
                        size=None,
                    ),
                ),
                (
                    "show_partner_names",
                    models.BooleanField(
                        default=True,
                        help_text="off: partners appear as 'Partner 1 (civil society)' and so on",
                    ),
                ),
                (
                    "contact",
                    models.CharField(
                        blank=True,
                        help_text="the focal point shown on the page",
                        max_length=200,
                        verbose_name="UNICEF contact",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "expires_on",
                    models.DateField(
                        blank=True,
                        help_text="the account stops working after this day",
                        null=True,
                    ),
                ),
                (
                    "must_change_password",
                    models.BooleanField(
                        default=True,
                        help_text="set when a temporary password is issued; cleared when the donor changes it",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.CharField(blank=True, editable=False, max_length=150),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donor_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "donor account",
                "ordering": ("name",),
            },
        ),
    ]
