# Generated by Django 5.2.17 on 2026-09-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="donoraccount",
            name="owns_user",
            field=models.BooleanField(
                default=True,
                editable=False,
                help_text="the sign-in was created with this account (deleting the account deletes it); off: an existing user was linked (deleting the account switches the sign-in off)",
            ),
        ),
    ]
