# Generated by Django 5.2.17 on 2026-09-22 19:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PopulationFigure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(db_index=True)),
                (
                    "nationality",
                    models.CharField(
                        choices=[
                            ("LEB", "Lebanese"),
                            ("SYR", "Syrian"),
                            ("PRS", "Palestinian refugees from Syria"),
                            ("PRL", "Palestinian refugees in Lebanon"),
                            ("OTH", "Other"),
                            ("ALL", "All"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("national", "National"),
                            ("governorate", "Governorate"),
                            ("district", "District"),
                            ("cadaster", "Cadaster"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "area_code",
                    models.CharField(blank=True, db_index=True, max_length=20),
                ),
                ("area_name", models.CharField(blank=True, max_length=120)),
                (
                    "parent_name",
                    models.CharField(
                        blank=True,
                        help_text="governorate of a district, etc.",
                        max_length=120,
                    ),
                ),
                (
                    "age_group",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 0-4, 5-17, 18-59, 60+ ; empty = all ages",
                        max_length=20,
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        blank=True, help_text="male/female; empty = both", max_length=6
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        default="total",
                        help_text="total | children | vulnerable",
                        max_length=24,
                    ),
                ),
                ("vulnerability_level", models.CharField(blank=True, max_length=24)),
                ("value", models.BigIntegerField()),
                ("source", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["year", "category", "level"],
                        name="core_popula_year_124b05_idx",
                    )
                ],
                "unique_together": {
                    (
                        "year",
                        "category",
                        "nationality",
                        "level",
                        "area_code",
                        "age_group",
                        "sex",
                        "vulnerability_level",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="SyncRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job",
                    models.CharField(
                        choices=[
                            ("ai_structure", "ActivityInfo structure import"),
                            ("ai_data", "ActivityInfo data import"),
                            ("etools", "eTools sync"),
                            ("locations", "Locations sync"),
                            ("population", "Population figures load"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        blank=True,
                        help_text="e.g. the database id or entity name",
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("partial", "Succeeded with errors"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="running",
                        max_length=16,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("rows_in", models.PositiveIntegerField(default=0)),
                ("rows_written", models.PositiveIntegerField(default=0)),
                ("rows_failed", models.PositiveIntegerField(default=0)),
                ("error", models.TextField(blank=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "triggered_by",
                    models.CharField(
                        blank=True, help_text="schedule or the username", max_length=150
                    ),
                ),
            ],
            options={
                "ordering": ("-started_at",),
                "indexes": [
                    models.Index(
                        fields=["job", "status", "-started_at"],
                        name="core_syncru_job_c8eb31_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SavedView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "page",
                    models.CharField(
                        db_index=True,
                        help_text="route name, e.g. reports:database_analytical",
                        max_length=64,
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True, help_text="e.g. the database id", null=True
                    ),
                ),
                (
                    "query",
                    models.JSONField(
                        blank=True, default=dict, help_text="query-string parameters"
                    ),
                ),
                (
                    "layout",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="pivot rows/cols/aggregator/renderer",
                    ),
                ),
                (
                    "is_shared",
                    models.BooleanField(
                        default=False, help_text="visible to every signed-in user"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "unique_together": {("owner", "page", "object_id", "name")},
            },
        ),
    ]
