# Generated by Django 5.2.17 on 2026-09-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_daily_review_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="populationfigure",
            name="nationality",
            field=models.CharField(
                choices=[
                    ("LEB", "Lebanese"),
                    ("SYR", "Syrian"),
                    ("PRS", "Palestinian refugees from Syria"),
                    ("PRL", "Palestinian refugees in Lebanon"),
                    ("PAL", "Palestinians (PRL + PRS)"),
                    ("OTH", "Other"),
                    ("ALL", "All"),
                ],
                max_length=3,
            ),
        ),
    ]
