# Generated by Django 5.2.17 on 2026-09-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_populationfigure_nationality"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="a short name, e.g. etools-nightly",
                        max_length=40,
                        unique=True,
                    ),
                ),
                (
                    "command",
                    models.CharField(help_text="what the job runs", max_length=40),
                ),
                (
                    "schedule",
                    models.CharField(
                        help_text="When it runs, in Beirut time, as five cron fields: minute hour day-of-month month day-of-week. Examples: '30 20 * * *' every day at 20:30; '0 18 1-22 * *' at 18:00 on days 1 to 22; '15 * * * *' every hour at :15; '0 4 * * 0' Sundays at 04:00.",
                        max_length=100,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "next_run_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "last_started_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "last_outcome",
                    models.CharField(blank=True, editable=False, max_length=200),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.CharField(blank=True, editable=False, max_length=150),
                ),
            ],
            options={
                "verbose_name": "scheduled job",
                "ordering": ("key",),
            },
        ),
        migrations.CreateModel(
            name="SchedulerState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("host", models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
