# Generated by Django 5.2.17 on 2026-09-29 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_default_schedules"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="syncrun",
            options={
                "ordering": ("-started_at",),
                "verbose_name": "import and sync run",
            },
        ),
    ]
