# Generated by Django 5.2.17 on 2026-10-01 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flags_modified_since", models.CharField(blank=True, max_length=40)),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("kinds", models.JSONField(blank=True, default=dict)),
                ("results", models.JSONField(blank=True, default=dict)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "wellbeing sync state",
            },
        ),
        migrations.CreateModel(
            name="CenterSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("center_id", models.PositiveIntegerField()),
                ("center_name", models.CharField(max_length=200)),
                ("governorate", models.CharField(blank=True, max_length=100)),
                ("partner_id", models.PositiveIntegerField(blank=True, null=True)),
                ("partner_name", models.CharField(blank=True, max_length=200)),
                ("round_id", models.PositiveIntegerField(blank=True, null=True)),
                ("round_name", models.CharField(blank=True, max_length=100)),
                ("month", models.DateField()),
                ("figures", models.JSONField(default=dict)),
                ("computed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ("-month", "center_name"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("center_id", "round_id", "month"),
                        name="wellbeing_summary_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Flag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bma_id", models.PositiveIntegerField(unique=True)),
                (
                    "registration",
                    models.PositiveIntegerField(
                        db_index=True, help_text="BMA registration number"
                    ),
                ),
                ("kind", models.CharField(max_length=4)),
                ("kind_label", models.CharField(max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("followed_up", "Followed up"),
                            ("resolved", "Resolved by itself"),
                        ],
                        db_index=True,
                        max_length=12,
                    ),
                ),
                ("urgent", models.BooleanField(default=False)),
                ("priority", models.BooleanField(default=False)),
                ("reason", models.TextField()),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("as_of", models.DateField(blank=True, null=True)),
                ("opened_on", models.DateField()),
                ("last_seen_on", models.DateField(blank=True, null=True)),
                ("resolved_on", models.DateField(blank=True, null=True)),
                ("followed_up_on", models.DateField(blank=True, null=True)),
                ("follow_up_type", models.CharField(blank=True, max_length=40)),
                ("result", models.CharField(blank=True, max_length=20)),
                ("result_label", models.CharField(blank=True, max_length=120)),
                ("note", models.TextField(blank=True)),
                ("followed_up_by_name", models.CharField(blank=True, max_length=150)),
                (
                    "center_id",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                ("center_name", models.CharField(blank=True, max_length=200)),
                (
                    "partner_id",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                ("partner_name", models.CharField(blank=True, max_length=200)),
                ("round_name", models.CharField(blank=True, max_length=100)),
                ("child_gender", models.CharField(blank=True, max_length=20)),
                ("child_age_band", models.CharField(blank=True, max_length=20)),
                ("child_nationality", models.CharField(blank=True, max_length=100)),
                ("bma_path", models.CharField(blank=True, max_length=200)),
                ("bma_modified", models.DateTimeField(blank=True, null=True)),
                ("synced_at", models.DateTimeField(auto_now=True)),
                (
                    "followed_up_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-urgent", "-priority", "opened_on", "bma_id"),
                "indexes": [
                    models.Index(
                        fields=["status", "kind"], name="wellbeing_f_status_2ea1e7_idx"
                    )
                ],
            },
        ),
    ]
