# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-26 15:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('agreement_type', models.CharField(choices=[('PCA', 'Programme Cooperation Agreement'), ('SSFA', 'Small Scale Funding Agreement'), ('MOU', 'Memorandum of Understanding'), ('IC', 'Institutional Contract'), ('AWP', 'Work Plan')], max_length=10)),
                ('agreement_number', models.CharField(blank=True, max_length=45, verbose_name='Reference Number')),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('signed_by_unicef_date', models.DateField(blank=True, null=True)),
                ('signed_by_partner_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_type', models.CharField(choices=[('Bilateral / Multilateral', 'Bilateral / Multilateral'), ('Civil Society Organization', 'Civil Society Organization'), ('Government', 'Government'), ('UN Agency', 'UN Agency')], max_length=50)),
                ('cso_type', models.CharField(blank=True, choices=[('International', 'International'), ('National', 'National'), ('Community Based Organisation', 'Community Based Organisation'), ('Academic Institution', 'Academic Institution')], max_length=50, null=True, verbose_name='CSO Type')),
                ('name', models.CharField(help_text='Please make sure this matches the name you enter in VISION', max_length=255, verbose_name='Full Name')),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('shared_partner', models.CharField(blank=True, choices=[('No', 'No'), ('with UNDP', 'with UNDP'), ('with UNFPA', 'with UNFPA'), ('with UNDP & UNFPA', 'with UNDP & UNFPA')], default='No', help_text='Partner shared with UNDP or UNFPA?', max_length=50)),
                ('address', models.TextField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=32, null=True)),
                ('vendor_number', models.CharField(blank=True, max_length=30, null=True)),
                ('alternate_id', models.IntegerField(blank=True, null=True)),
                ('alternate_name', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.CharField(blank=True, max_length=50, null=True, verbose_name='Risk Rating')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartnerStaffMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.CharField(blank=True, max_length=128)),
                ('phone', models.CharField(max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etools.PartnerOrganization')),
            ],
        ),
        migrations.CreateModel(
            name='PCA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('document_type', models.CharField(blank=True, choices=[('PD', 'Programme Document'), ('SHPD', 'Simplified Humanitarian Programme Document'), ('AWP', 'Cash Transfers to Government'), ('SSFA', 'SSFA TOR'), ('IC', 'IC TOR')], default='PD', max_length=255, null=True, verbose_name='Document type')),
                ('country_programme', models.CharField(blank=True, help_text='Which result structure does this partnership report under?', max_length=32, null=True)),
                ('number', models.CharField(blank=True, max_length=45, null=True, verbose_name='Reference Number')),
                ('title', models.CharField(max_length=256)),
                ('project_type', models.CharField(blank=True, choices=[('Bulk Procurement', 'Bulk Procurement'), ('Construction Project', 'Construction Project')], max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('in_process', 'In Process'), ('active', 'Active'), ('implemented', 'Implemented'), ('cancelled', 'Cancelled')], default='in_process', help_text='In Process = In discussion with partner, Active = Currently ongoing, Implemented = completed, Cancelled = cancelled or not approved', max_length=32)),
                ('start', models.DateField(blank=True, help_text='The date the Intervention will start', null=True, verbose_name='Partnership start date')),
                ('end', models.DateField(blank=True, help_text='The date the Intervention will end', null=True, verbose_name='Partnership end date')),
                ('initiation_date', models.DateField(blank=True, help_text='The date the partner submitted complete partnership documents to Unicef', null=True, verbose_name='Submission Date')),
                ('submission_date', models.DateField(blank=True, help_text='The date the documents were submitted to the PRC', null=True, verbose_name='Submission Date to PRC')),
                ('review_date', models.DateField(blank=True, help_text='The date the PRC reviewed the partnership', null=True, verbose_name='Review date by PRC')),
                ('signed_by_unicef_date', models.DateField(blank=True, null=True)),
                ('signed_by_partner_date', models.DateField(blank=True, null=True)),
                ('fr_number', models.CharField(blank=True, max_length=50, null=True)),
                ('planned_visits', models.IntegerField(default=0)),
                ('sectors', models.CharField(blank=True, max_length=255, null=True)),
                ('current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='etools.Agreement')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='etools.PartnerOrganization')),
                ('partner_focal_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_partnerships', to='etools.PartnerStaffMember')),
                ('partner_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signed_partnerships', to='etools.PartnerStaffMember', verbose_name='Signed by partner')),
                ('unicef_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_partnerships', to=settings.AUTH_USER_MODEL, verbose_name='Signed by')),
                ('unicef_managers', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Unicef focal points')),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Intervention',
                'verbose_name_plural': 'Interventions',
            },
        ),
        migrations.AlterUniqueTogether(
            name='partnerorganization',
            unique_together=set([('name', 'vendor_number')]),
        ),
        migrations.AddField(
            model_name='agreement',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='etools.PartnerOrganization'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='partner_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='etools.PartnerStaffMember', verbose_name='Signed by partner'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signed_pcas', to=settings.AUTH_USER_MODEL),
        ),
    ]
