# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-12-08 21:25
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
from etools.models import determine_file_upload_path

class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_section_powerbi_url'),
        ('etools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=255, verbose_name='Origin')),
                ('destination', models.CharField(max_length=255, verbose_name='Destination')),
                ('departure_date', models.DateTimeField(verbose_name='Departure Date')),
                ('arrival_date', models.DateTimeField(verbose_name='Arrival Date')),
                ('overnight_travel', models.BooleanField(default=False, verbose_name='Overnight Travel')),
                ('mode_of_travel', models.CharField(blank=True, choices=[('Plane', 'Plane'), ('Bus', 'Bus'), ('Car', 'Car'), ('Boat', 'Boat'), ('Rail', 'Rail')], default='', max_length=5, verbose_name='Mode of Travel')),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='Canceled At')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submitted At')),
                ('first_submission_date', models.DateTimeField(blank=True, null=True, verbose_name='First Submission Date')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='Rejected At')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('rejection_note', models.TextField(blank=True, default='', verbose_name='Rejection Note')),
                ('cancellation_note', models.TextField(blank=True, default='', verbose_name='Cancellation Note')),
                ('certification_note', models.TextField(blank=True, default='', verbose_name='Certification Note')),
                ('report_note', models.TextField(blank=True, default='', verbose_name='Report Note')),
                ('misc_expenses', models.TextField(blank=True, default='', verbose_name='Misc Expenses')),
                ('status', django_fsm.FSMField(choices=[('planned', 'Planned'), ('submitted', 'Submitted'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('sent_for_payment', 'Sent for payment'), ('certification_submitted', 'Certification submitted'), ('certification_approved', 'Certification approved'), ('certification_rejected', 'Certification rejected'), ('certified', 'Certified'), ('completed', 'Completed')], default='planned', max_length=50, protected=True, verbose_name='Status')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('purpose', models.CharField(blank=True, default='', max_length=500, verbose_name='Purpose')),
                ('additional_note', models.TextField(blank=True, default='', verbose_name='Additional Note')),
                ('international_travel', models.NullBooleanField(default=False, verbose_name='International Travel')),
                ('ta_required', models.NullBooleanField(default=True, verbose_name='TA Required')),
                ('reference_number', models.CharField(max_length=12, unique=True, verbose_name='Reference Number')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hidden')),
                ('mode_of_travel', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Plane', 'Plane'), ('Bus', 'Bus'), ('Car', 'Car'), ('Boat', 'Boat'), ('Rail', 'Rail')], max_length=5), blank=True, null=True, size=None, verbose_name='Mode of Travel')),
                ('estimated_travel_cost', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='Estimated Travel Cost')),
                ('is_driver', models.BooleanField(default=False, verbose_name='Is Driver')),
                ('preserved_expenses_local', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=20, null=True, verbose_name='Preserved Expenses (Local)')),
                ('preserved_expenses_usd', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=20, null=True, verbose_name='Preserved Expenses (USD)')),
                ('approved_cost_traveler', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=20, null=True, verbose_name='Approved Cost Traveler')),
                ('approved_cost_travel_agencies', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=20, null=True, verbose_name='Approved Cost Travel Agencies')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.Section', verbose_name='Section')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor')),
                ('traveler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travels', to=settings.AUTH_USER_MODEL, verbose_name='Travellert')),
            ],
        ),
        migrations.CreateModel(
            name='TravelActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_type', models.CharField(blank=True, choices=[('Programmatic Visit', 'Programmatic Visit'), ('Spot Check', 'Spot Check'), ('Advocacy', 'Advocacy'), ('Technical Support', 'Technical Support'), ('Meeting', 'Meeting'), ('Staff Development', 'Staff Development'), ('Staff Entitlement', 'Staff Entitlement')], default='Programmatic Visit', max_length=64, verbose_name='Travel Type')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Date')),
                ('locations', models.ManyToManyField(related_name='_travelactivity_locations_+', to='locations.Location', verbose_name='Locations')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='etools.PartnerOrganization', verbose_name='Partner')),
                ('partnership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travel_activities', to='etools.PCA', verbose_name='Partnership')),
                ('primary_traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Primary Traveler')),
                ('travels', models.ManyToManyField(related_name='activities', to='etools.Travel', verbose_name='Travels')),
            ],
            options={
                'verbose_name_plural': 'Travel Activities',
            },
        ),
        migrations.CreateModel(
            name='TravelAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64, verbose_name='Type')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('file', models.FileField(max_length=255, upload_to=determine_file_upload_path, verbose_name='File')),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='etools.Travel', verbose_name='Travel')),
            ],
        ),
        migrations.AddField(
            model_name='itineraryitem',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='etools.Travel', verbose_name='Travel'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='itineraryitem',
            order_with_respect_to='travel',
        ),
    ]
