# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-03 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etools', '0002_auto_20181208_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerorganization',
            name='etl_id',
            field=models.PositiveIntegerField(default=None, unique=True, verbose_name='eTools ID'),
            preserve_default=False,
        ),
    ]
