# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-03 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etools', '0003_partnerorganization_etl_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerorganization',
            name='etl_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='eTools ID'),
        ),
    ]
