# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-03 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etools', '0004_auto_20190303_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='etl_id',
            field=models.CharField(default=None, max_length=50, unique=True, verbose_name='eTools ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pca',
            name='etl_id',
            field=models.CharField(default=None, max_length=50, unique=True, verbose_name='eTools ID'),
            preserve_default=False,
        ),
    ]
