# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-04 08:25
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etools', '0007_auto_20190304_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='pca',
            name='planned_visits_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
