# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-06 20:54
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_fsm

class Migration(migrations.Migration):

    dependencies = [
        ('etools', '0009_auto_20190304_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=250, null=True)),
                ('assigned_by', models.CharField(blank=True, max_length=250, null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=250, null=True)),
                ('status', django_fsm.FSMField(choices=[('open', 'Open'), ('completed', 'Completed')], default='open', max_length=10, protected=True, verbose_name='Status')),
                ('category', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(verbose_name='Description')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('high_priority', models.BooleanField(default=False, verbose_name='High Priority')),
                ('section', models.CharField(blank=True, max_length=250, null=True)),
                ('office', models.CharField(blank=True, max_length=250, null=True)),
                ('location', models.CharField(blank=True, max_length=250, null=True)),
                ('partner', models.CharField(blank=True, max_length=250, null=True)),
                ('cp_output', models.CharField(blank=True, max_length=250, null=True)),
                ('intervention', models.CharField(blank=True, max_length=250, null=True)),
                ('tpm_activity', models.CharField(blank=True, max_length=250, null=True)),
                ('travel_activity', models.CharField(blank=True, max_length=250, null=True)),
                ('date_of_completion', models.CharField(blank=True, max_length=250, null=True)),
                ('comments', models.CharField(blank=True, max_length=250, null=True)),
                ('history', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'ordering': ('id',),
                'verbose_name': 'Action Point',
                'verbose_name_plural': 'Action Points',
            },
        ),
        migrations.CreateModel(
            name='DetailedFindingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding', models.TextField(verbose_name='Description of Finding')),
                ('recommendation', models.TextField(verbose_name='Recommendation and IP Management Response')),
            ],
            options={
                'ordering': ('id',),
                'verbose_name': 'Detailed Finding Info',
                'verbose_name_plural': 'Detailed Findings Info',
            },
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django_fsm.FSMField(choices=[('partner_contacted', 'IP Contacted'), ('report_submitted', 'Report Submitted'), ('final', 'Final Report'), ('cancelled', 'Cancelled')], default='partner_contacted', max_length=30, protected=True, verbose_name='Status')),
                ('partner_contacted_at', models.DateField(blank=True, null=True, verbose_name='Date IP was contacted')),
                ('engagement_type', models.CharField(choices=[('audit', 'Audit'), ('ma', 'Micro Assessment'), ('sc', 'Spot Check'), ('sa', 'Special Audit')], max_length=10, verbose_name='Engagement Type')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Period Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Period End Date')),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='Total value of selected FACE form(s)')),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='Exchange Rate')),
                ('engagement_attachments', models.CharField(blank=True, max_length=250, null=True)),
                ('report_attachments', models.CharField(blank=True, max_length=250, null=True)),
                ('date_of_field_visit', models.DateField(blank=True, null=True, verbose_name='Date of Field Visit')),
                ('date_of_draft_report_to_ip', models.DateField(blank=True, null=True, verbose_name='Date Draft Report Issued to IP')),
                ('date_of_comments_by_ip', models.DateField(blank=True, null=True, verbose_name='Date Comments Received from IP')),
                ('date_of_draft_report_to_unicef', models.DateField(blank=True, null=True, verbose_name='Date Draft Report Issued to UNICEF')),
                ('date_of_comments_by_unicef', models.DateField(blank=True, null=True, verbose_name='Date Comments Received from UNICEF')),
                ('date_of_report_submit', models.DateField(blank=True, null=True, verbose_name='Date Report Submitted')),
                ('date_of_final_report', models.DateField(blank=True, null=True, verbose_name='Date Report Finalized')),
                ('date_of_cancel', models.DateField(blank=True, null=True, verbose_name='Date Report Cancelled')),
                ('amount_refunded', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='Amount Refunded')),
                ('additional_supporting_documentation_provided', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='Additional Supporting Documentation Provided')),
                ('justification_provided_and_accepted', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='Justification Provided and Accepted')),
                ('write_off_required', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='Impairment')),
                ('explanation_for_additional_information', models.TextField(blank=True, verbose_name='Provide explanation for additional information received from the IP or add attachments')),
                ('joint_audit', models.BooleanField(default=False, verbose_name='Joint Audit')),
                ('shared_ip_with', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('DPKO', 'DPKO'), ('ECA', 'ECA'), ('ECLAC', 'ECLAC'), ('ESCWA', 'ESCWA'), ('FAO', 'FAO'), ('ILO', 'ILO'), ('IOM', 'IOM'), ('OHCHR', 'OHCHR'), ('UN', 'UN'), ('UN Women', 'UN Women'), ('UNAIDS', 'UNAIDS'), ('UNDP', 'UNDP'), ('UNESCO', 'UNESCO'), ('UNFPA', 'UNFPA'), ('UN - Habitat', 'UN - Habitat'), ('UNHCR', 'UNHCR'), ('UNODC', 'UNODC'), ('UNOPS', 'UNOPS'), ('UNRWA', 'UNRWA'), ('UNSC', 'UNSC'), ('UNU', 'UNU'), ('WB', 'WB'), ('WFP', 'WFP'), ('WHO', 'WHO')], max_length=20), blank=True, default=list, size=None, verbose_name='Shared Audit with')),
                ('cancel_comment', models.TextField(blank=True, verbose_name='Cancel Comment')),
                ('total_amount_tested', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='Total Amount Tested')),
                ('total_amount_of_ineligible_expenditure', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='Total Amount of Ineligible Expenditure')),
                ('internal_controls', models.TextField(blank=True, verbose_name='Internal Controls')),
                ('final_report', models.CharField(blank=True, max_length=250, null=True)),
                ('audited_expenditure', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='Audited Expenditure $')),
                ('financial_findings', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='Financial Findings $')),
                ('audit_opinion', models.CharField(blank=True, choices=[('unqualified', 'Unqualified'), ('qualified', 'Qualified'), ('disclaimer_opinion', 'Disclaimer opinion'), ('adverse_opinion', 'Adverse opinion')], default='', max_length=20, verbose_name='Audit Opinion')),
                ('description', models.TextField()),
                ('finding', models.TextField(blank=True)),
                ('active_pd', models.ManyToManyField(to='etools.PCA', verbose_name='Active PDs')),
                ('authorized_officers', models.ManyToManyField(blank=True, related_name='engagement_authorizations', to='etools.PartnerStaffMember', verbose_name='Authorized Officers')),
            ],
            options={
                'ordering': ('id',),
                'verbose_name': 'Engagement',
                'verbose_name_plural': 'Engagements',
            },
        ),
        migrations.CreateModel(
            name='FinancialFinding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('no-supporting-documentation', 'No supporting documentation'), ('insufficient-supporting-documentation', 'Insufficient supporting documentation'), ('cut-off-error', 'Cut-off error'), ('expenditure-not-for-project-purposes', 'Expenditure not for project purposes'), ('no-proof-of-payment', 'No proof of payment'), ('no-proof-of-goods-services-received', 'No proof of goods / services received'), ('vat-incorrectly-claimed', 'VAT incorrectly claimed'), ('dsa-rates-exceeded', 'DSA rates exceeded'), ('unreasonable-price', 'Unreasonable price'), ('bank-interest-not-reported', 'Bank interest not reported'), ('support-costs-incorrectly-calculated', 'Support costs incorrectly calculated'), ('expenditure-claimed-but-activities-not-undertaken', 'Expenditure claimed but activities not undertaken'), ('advance-claimed-as-expenditure', 'Advance claimed as expenditure'), ('commitments-treated-as-expenditure', 'Commitments treated as expenditure'), ('ineligible-salary-costs', 'Ineligible salary costs'), ('ineligible-costs-other', 'Ineligible costs (other)')], max_length=255, verbose_name='Title (Category)')),
                ('local_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Amount (local)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Amount (USD)')),
                ('description', models.TextField(verbose_name='Description')),
                ('recommendation', models.TextField(blank=True, verbose_name='Recommendation')),
                ('ip_comments', models.TextField(blank=True, verbose_name='IP Comments')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='etools.Engagement', verbose_name='Audit')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('high', 'High'), ('low', 'Low')], max_length=4, verbose_name='Priority')),
                ('category_of_observation', models.CharField(choices=[('expenditure_not_for_programme_purposes', 'Expenditure not for programme purposes'), ('expenditure_claimed_but_activities_not_undertaken', 'Expenditure claimed but activities not undertaken'), ('expenditure_exceeds_the_approved_budget_rate_or_amount', 'Expenditure exceeds the approved budget rate or amount'), ('expenditure_not_recorded_in_the_correct_period_or_face_form', 'Expenditure not recorded in the correct period or FACE form'), ('advance_claimed_as_expenditure', 'Advance claimed as expenditure'), ('commitments_treated_as_expenditure', 'Commitments treated as expenditure'), ('signatories_on_face_forms_different_from_ip_agreement', 'Signatories on FACE forms different from those in the IP Agreement'), ('no_supporting_documentation', 'No supporting documentation'), ('insufficient_supporting_documentation', 'Insufficient supporting documentation'), ('no_proof_of_payment', 'No proof of payment'), ('no_proof_of_goods_received', 'No proof of goods / services received'), ('poor_record_keeping', 'Poor record keeping'), ('lack_of_audit_trail', "Lack of audit trail (FACE forms do not reconcile with IPs and UNICEF's accounting records)"), ('lack_of_bank_reconciliations', 'Lack of bank reconciliations'), ('lack_of_segregation_of_duties', 'Lack of segregation of duties'), ('vat_incorrectly_claimed', 'VAT incorrectly claimed'), ('ineligible_salary_cost', 'Ineligible salary cost'), ('dsa_rates_exceeded', 'DSA rates exceeded'), ('support_costs_incorrectly_calculated', 'Support costs incorrectly calculated'), ('no_competitive_procedures_for_the_award_of_contracts', 'No competitive procedures for the award of contracts'), ('suppliers_invoices_not_approved', "Supplier's invoices not approved"), ('no_evaluation_of_goods_received', 'No evaluation of goods received'), ('lack_of_procedures_for_verification_of_assets', 'Lack of procedures for verification of assets'), ('goods_/_assets_not_used_for_the_intended_purposes', 'Goods / Assets not used for the intended purposes'), ('lack_of_written_agreement_between_ip_and_sub-contractee', 'Lack of written agreement between IP and sub-contractee'), ('lack_of_sub-contractee_financial', 'Lack of sub-contractee financial / substantive progress reporting on file'), ('failure_to_implement_prior_assurance_activity_recommendations', 'Failure to implement prior assurance activity recommendations'), ('other', 'Other')], max_length=100, verbose_name='Category of Observation')),
                ('recommendation', models.TextField(blank=True, verbose_name='Finding and Recommendation')),
                ('agreed_action_by_ip', models.TextField(blank=True, verbose_name='Agreed Action by IP')),
                ('deadline_of_action', models.DateField(blank=True, null=True, verbose_name='Deadline of Action')),
                ('spot_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='etools.Engagement', verbose_name='Spot Check')),
            ],
            options={
                'ordering': ('id',),
                'verbose_name': 'Finding',
                'verbose_name_plural': 'Findings',
            },
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='shared_with',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('DPKO', 'DPKO'), ('ECA', 'ECA'), ('ECLAC', 'ECLAC'), ('ESCWA', 'ESCWA'), ('FAO', 'FAO'), ('ILO', 'ILO'), ('IOM', 'IOM'), ('OHCHR', 'OHCHR'), ('UN', 'UN'), ('UN Women', 'UN Women'), ('UNAIDS', 'UNAIDS'), ('UNDP', 'UNDP'), ('UNESCO', 'UNESCO'), ('UNFPA', 'UNFPA'), ('UN - Habitat', 'UN - Habitat'), ('UNHCR', 'UNHCR'), ('UNODC', 'UNODC'), ('UNOPS', 'UNOPS'), ('UNRWA', 'UNRWA'), ('UNSC', 'UNSC'), ('UNU', 'UNU'), ('WB', 'WB'), ('WFP', 'WFP'), ('WHO', 'WHO')], max_length=20), blank=True, null=True, size=None, verbose_name='Shared Partner'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etools.PartnerOrganization', verbose_name='Partner'),
        ),
        migrations.AddField(
            model_name='detailedfindinginfo',
            name='micro_assesment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='etools.Engagement', verbose_name='Micro Assessment'),
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='engagement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_points', to='etools.Engagement', verbose_name='Engagement'),
        ),
    ]
