# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-07 12:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etools', '0010_auto_20190406_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='agreement',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
