# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-07 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etools', '0011_engagement_agreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='etools.PartnerOrganization', verbose_name='Partner'),
        ),
    ]
