# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-07 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etools', '0013_auto_20190407_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='unique_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
