# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-07 19:29
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etools', '0015_auto_20190407_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='findings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10000), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='engagement',
            name='pending_unsupported_amount',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='authorized_officers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2500), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='staff_members',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2500), blank=True, null=True, size=None),
        ),
    ]
