# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-08 20:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etools', '0017_auto_20190408_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelactivity',
            name='primary_traveler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Primary Traveler'),
        ),
    ]
