# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-13 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etools', '0018_auto_20190408_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='travel_type',
            field=models.CharField(blank=True, choices=[('Programmatic Visit', 'Programmatic Visit'), ('Spot Check', 'Spot Check'), ('Advocacy', 'Advocacy'), ('Technical Support', 'Technical Support'), ('Meeting', 'Meeting'), ('Staff Development', 'Staff Development'), ('Staff Entitlement', 'Staff Entitlement')], default='Programmatic Visit', max_length=64, verbose_name='Travel Type'),
        ),
    ]
