# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-14 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etools', '0021_auto_20190414_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelactivity',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travelactivity_set', to='etools.PartnerOrganization', verbose_name='Partner'),
        ),
    ]
