# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-15 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etools', '0022_auto_20190414_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerorganization',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='deleted_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engagement_set', to='etools.PartnerOrganization', verbose_name='Partner'),
        ),
    ]
