# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-16 09:40
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etools', '0023_auto_20190415_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='findings_sets',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
