# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-23 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etools', '0025_travel_attachments_sets'),
    ]

    operations = [
        migrations.AddField(
            model_name='pca',
            name='end_date',
            field=models.DateField(blank=True, help_text='The date the Intervention will end', null=True, verbose_name='Partnership end date'),
        ),
    ]
