# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-05-01 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20190501_2242'),
        ('etools', '0027_engagement_displayed_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pca',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='_pca_locations_+', to='locations.Location'),
        ),
    ]
