# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-05-06 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etools', '0029_auto_20190506_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerorganization',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
