# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-12 22:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etools', '0028_pca_locations'),
        ('etools', '0031_auto_20190507_1322'),
    ]

    operations = [
    ]
