# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-13 23:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('etools', '0032_merge_20190512_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('module', models.CharField(choices=[('apd', 'Action Points'), ('t2f', 'Trip Management'), ('tpm', 'Third Party Monitoring'), ('audit', 'Financial Assurance')], max_length=10, verbose_name='Module')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'ordering': ('module', 'order'),
                'verbose_name': 'Action point category',
                'verbose_name_plural': 'Action point categories',
            },
        ),
        migrations.RemoveField(
            model_name='actionpoint',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='actionpoint',
            name='cp_output',
        ),
        migrations.RemoveField(
            model_name='actionpoint',
            name='history',
        ),
        migrations.RemoveField(
            model_name='actionpoint',
            name='tpm_activity',
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='actionpoint',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By'),
        ),
        migrations.AlterField(
            model_name='actionpoint',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_action_points', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To'),
        ),
        migrations.AlterField(
            model_name='actionpoint',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_action_points', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='actionpoint',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='etools.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='actionpoint',
            name='intervention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='etools.PCA', verbose_name='PD/SSFA'),
        ),
        migrations.AlterField(
            model_name='actionpoint',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='actionpoint',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Office', verbose_name='Office'),
        ),
        migrations.AlterField(
            model_name='actionpoint',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='etools.PartnerOrganization', verbose_name='Partner'),
        ),
        migrations.AlterField(
            model_name='actionpoint',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Section', verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='actionpoint',
            name='travel_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='etools.TravelActivity', verbose_name='Travel'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set([('description', 'module')]),
        ),
    ]
