# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-13 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etools', '0033_auto_20190513_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionpoint',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
