# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etools', '0034_actionpoint_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionpoint',
            name='assigned_by_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='assigned_to_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='author_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='related_module',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
