# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etools', '0037_actionpoint_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionpoint',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('completed', 'Completed')], default='open', max_length=10, verbose_name='Status'),
        ),
    ]
