# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etools', '0038_auto_20190514_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionpoint',
            name='status_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
