# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etools', '0041_auto_20190514_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionpoint',
            name='category_name',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
