# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-15 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etools', '0043_auto_20190515_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerorganization',
            name='assessments',
        ),
        migrations.RemoveField(
            model_name='partnerorganization',
            name='core_values_assessments',
        ),
        migrations.RemoveField(
            model_name='partnerorganization',
            name='flags',
        ),
        migrations.RemoveField(
            model_name='partnerorganization',
            name='hact_min_requirements',
        ),
        migrations.RemoveField(
            model_name='partnerorganization',
            name='hact_values',
        ),
        migrations.RemoveField(
            model_name='partnerorganization',
            name='planned_engagement',
        ),
        migrations.RemoveField(
            model_name='partnerorganization',
            name='planned_visits',
        ),
        migrations.RemoveField(
            model_name='partnerorganization',
            name='staff_members',
        ),
    ]
