# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-15 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etools', '0046_auto_20190515_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerorganization',
            name='core_values_assessment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partnerorganization',
            name='last_assessment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travelactivity',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
