# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-15 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etools', '0047_auto_20190515_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='status',
            field=models.CharField(default='planned', max_length=500, verbose_name='Status'),
        ),
    ]
