# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-22 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etools', '0048_auto_20190515_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='reference_number',
            field=models.CharField(max_length=12, verbose_name='Reference Number'),
        ),
    ]
