# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-31 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etools', '0049_auto_20190522_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='have_hact',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
