# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-06-02 21:01
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etools', '0050_travel_have_hact'),
    ]

    operations = [
        migrations.AddField(
            model_name='pca',
            name='donors_set',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AddField(
            model_name='pca',
            name='frs_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
    ]
