# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-11 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0097_auto_20190603_1158'),
        ('etools', '0051_auto_20190602_2101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pca',
            options={'ordering': ['-partner_name'], 'verbose_name': 'Intervention', 'verbose_name_plural': 'Interventions'},
        ),
        migrations.AddField(
            model_name='pca',
            name='activities',
            field=models.ManyToManyField(blank=True, related_name='interventions', to='activityinfo.Activity'),
        ),
    ]
