# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-20 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_section_etools'),
        ('etools', '0052_auto_20190611_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorFunding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor', models.CharField(blank=True, max_length=255, null=True)),
                ('grant', models.CharField(blank=True, max_length=255, null=True)),
                ('total_contribution', models.FloatField(blank=True, null=True)),
                ('programmable', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=1500, null=True)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.Section')),
            ],
        ),
    ]
