# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-23 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etools', '0053_donorfunding'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorfunding',
            name='year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
