# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-06-06 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etools', '0054_donorfunding_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorfunding',
            name='donor_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
