# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-06-07 18:17
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etools', '0055_donorfunding_donor_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='pca',
            name='offices_set',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
