# Generated by Django 3.2.12 on 2022-03-09 09:03

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20220309_1103'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etools', '0056_pca_offices_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='etools.partnerorganization'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='partner_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='etools.partnerstaffmember', verbose_name='Signed by partner'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_pcas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donorfunding',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.section'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='joint_audit',
            field=models.BooleanField(blank=True, default=False, verbose_name='Joint Audit'),
        ),
        migrations.AlterField(
            model_name='partnerstaffmember',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='etools.partnerorganization'),
        ),
        migrations.AlterField(
            model_name='pca',
            name='agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to='etools.agreement'),
        ),
        migrations.AlterField(
            model_name='pca',
            name='donors_set',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='pca',
            name='frs_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='pca',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to='etools.partnerorganization'),
        ),
        migrations.AlterField(
            model_name='pca',
            name='partner_focal_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_partnerships', to='etools.partnerstaffmember'),
        ),
        migrations.AlterField(
            model_name='pca',
            name='partner_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_partnerships', to='etools.partnerstaffmember', verbose_name='Signed by partner'),
        ),
        migrations.AlterField(
            model_name='pca',
            name='unicef_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_partnerships', to=settings.AUTH_USER_MODEL, verbose_name='Signed by'),
        ),
        migrations.AlterField(
            model_name='travelactivity',
            name='travel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travels', to='etools.travel', verbose_name='Travels'),
        ),
    ]
