# Generated by Django 3.2.12 on 2022-03-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etools', '0057_auto_20220309_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='agreement',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='findings_sets',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='po_item',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partnerorganization',
            name='assessments',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partnerorganization',
            name='core_values_assessments',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partnerorganization',
            name='flags',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partnerorganization',
            name='hact_min_requirements',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partnerorganization',
            name='hact_values',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partnerorganization',
            name='planned_engagement',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partnerorganization',
            name='planned_visits',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partnerorganization',
            name='staff_members',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pca',
            name='donors_set',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='pca',
            name='frs_details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='attachments_sets',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
