# Generated by Django 3.2.12 on 2022-03-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etools', '0058_auto_20220323_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='ta_required',
            field=models.BooleanField(default=True, verbose_name='TA Required'),
        ),
    ]
