# Generated by Django 3.2.12 on 2022-03-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etools', '0059_alter_travel_ta_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='international_travel',
            field=models.BooleanField(default=False, verbose_name='International Travel'),
        ),
    ]
