# Generated by Django 5.0.7 on 2024-09-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etools", "0062_alter_actionpoint_id_alter_agreement_id_and_more"),
        ("pivoting", "0067_alter_map_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pca",
            name="activities",
            field=models.ManyToManyField(
                blank=True, related_name="interventions", to="pivoting.activity"
            ),
        ),
    ]
