# Generated by Django 5.2.17 on 2026-09-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SectionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(db_index=True)),
                (
                    "section",
                    models.CharField(
                        help_text="the eTools section name, as on the PD indicators",
                        max_length=128,
                    ),
                ),
                (
                    "children_target",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="children to reach in the year (Country Programme target)",
                        null=True,
                    ),
                ),
                (
                    "required_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="funds required in the year (USD)",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="the source of the figures",
                        max_length=500,
                    ),
                ),
                ("updated_by", models.CharField(blank=True, max_length=150)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "section plan",
                "verbose_name_plural": "section plans (CP targets and requirements)",
                "ordering": ("-year", "section"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("year", "section"), name="section_plan_per_year"
                    )
                ],
            },
        ),
    ]
