# Generated by Django 5.2.17 on 2026-09-29 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("etools", "0003_partnerlink"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="YouthFigures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        help_text="Compiler's reporting year",
                        max_length=16,
                        unique=True,
                    ),
                ),
                ("fetched_at", models.DateTimeField()),
                (
                    "payload",
                    models.JSONField(
                        help_text="counts of young people per grouping, as Compiler sent them"
                    ),
                ),
            ],
            options={
                "verbose_name": "youth figures",
                "verbose_name_plural": "youth figures",
                "ordering": ("-year",),
            },
        ),
        migrations.CreateModel(
            name="YouthIndicatorLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(db_index=True, max_length=16)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("master", "Master indicator"),
                            ("sub", "Sub indicator"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "youth_indicator_id",
                    models.PositiveIntegerField(
                        help_text="the indicator's id in Compiler"
                    ),
                ),
                (
                    "youth_indicator",
                    models.CharField(
                        help_text="number and name, as Compiler sent them",
                        max_length=300,
                    ),
                ),
                ("compiler_pd_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "compiler_pd_code",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Compiler project code"
                    ),
                ),
                (
                    "etools_key",
                    models.CharField(
                        max_length=32, verbose_name="eTools indicator key"
                    ),
                ),
                (
                    "etools_title",
                    models.CharField(max_length=512, verbose_name="eTools indicator"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("suggested", "Suggested"),
                            ("confirmed", "Confirmed"),
                        ],
                        default="suggested",
                        max_length=16,
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        blank=True,
                        help_text="how closely the titles match (0-1)",
                        null=True,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=300)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pd",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="youth_links",
                        to="etools.pca",
                        verbose_name="eTools programme document",
                    ),
                ),
            ],
            options={
                "verbose_name": "youth indicator link",
                "ordering": ("year", "compiler_pd_code", "level", "youth_indicator"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "year",
                            "level",
                            "youth_indicator_id",
                            "compiler_pd_id",
                            "pd",
                            "etools_key",
                        ),
                        name="youth_link_unique",
                    )
                ],
            },
        ),
    ]
