# Generated by Django 5.2.17 on 2026-10-05 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KeyProbe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset", models.CharField(max_length=64)),
                ("key", models.CharField(max_length=120)),
                ("records", models.PositiveIntegerField()),
                ("total", models.PositiveIntegerField()),
                ("types", models.JSONField(default=dict)),
                ("examples", models.JSONField(default=list)),
                ("refreshed_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "key found in the data",
                "verbose_name_plural": "keys found in the data",
                "ordering": ("dataset", "key"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dataset", "key"), name="fmm_key_probe"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FieldMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset", models.CharField(max_length=64)),
                ("field", models.CharField(max_length=40)),
                ("chosen_key", models.CharField(blank=True, max_length=120)),
                ("coverage", models.FloatField(default=0)),
                ("candidates", models.JSONField(default=list)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("found", "Found"),
                            ("override", "Set by an administrator"),
                            ("override_missing", "Set key not in the data"),
                            ("ambiguous", "Found, another key is fuller"),
                            ("missing", "Not found"),
                        ],
                        default="missing",
                        max_length=16,
                    ),
                ),
                (
                    "override_key",
                    models.CharField(
                        blank=True, help_text="pin a key the data shows", max_length=120
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "field found",
                "verbose_name_plural": "fields found",
                "ordering": ("dataset", "field"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dataset", "field"), name="fmm_field_mapping"
                    )
                ],
            },
        ),
    ]
