# Generated by Django 5.2.17 on 2026-10-05 10:47

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamart", "0008_monitoringfinding_pd_link"),
        ("etools", "0003_partnerlink"),
        ("fmm", "0001_initial"),
        ("locations", "0002_location_tables_when_missing"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RefreshRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scores_requested_at", models.DateTimeField(blank=True, null=True)),
                ("full_requested_at", models.DateTimeField(blank=True, null=True)),
                ("requested_by", models.CharField(blank=True, max_length=150)),
            ],
            options={
                "verbose_name": "refresh request",
                "verbose_name_plural": "refresh requests",
            },
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(max_length=40, unique=True)),
                (
                    "activity_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "reference",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("reference_number", models.CharField(blank=True, max_length=100)),
                ("label", models.CharField(max_length=110)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, db_index=True, null=True)),
                ("last_modified", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=24)),
                ("status_raw", models.CharField(blank=True, max_length=40)),
                (
                    "status_group",
                    models.CharField(db_index=True, default="unknown", max_length=12),
                ),
                (
                    "rating",
                    models.CharField(
                        db_index=True, default="not_monitored", max_length=16
                    ),
                ),
                ("rating_counts", models.JSONField(default=dict)),
                ("hact_q1", models.CharField(blank=True, db_index=True, max_length=16)),
                ("psea_flag", models.BooleanField(null=True)),
                ("is_programmatic", models.BooleanField(default=False)),
                ("is_remote", models.BooleanField(default=False)),
                ("entities", models.PositiveSmallIntegerField(default=0)),
                ("entities_rated", models.PositiveSmallIntegerField(default=0)),
                (
                    "entity_kinds",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=12),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "partner_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), default=list, size=None
                    ),
                ),
                (
                    "pd_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.BigIntegerField(), default=list, size=None
                    ),
                ),
                (
                    "pd_numbers",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=64),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "cp_outputs",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=300),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "programme_activities",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=300),
                        default=list,
                        size=None,
                    ),
                ),
                ("place_name", models.CharField(blank=True, max_length=254)),
                ("place_pcode", models.CharField(blank=True, max_length=32)),
                ("governorate_name", models.CharField(blank=True, max_length=254)),
                (
                    "governorate_key",
                    models.CharField(blank=True, db_index=True, max_length=40),
                ),
                ("district_name", models.CharField(blank=True, max_length=254)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("located_by", models.CharField(blank=True, max_length=10)),
                (
                    "located_level",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("point_precise", models.BooleanField(default=False)),
                ("approximate", models.BooleanField(default=False)),
                ("approximate_from", models.CharField(blank=True, max_length=254)),
                (
                    "section_names",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "section_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), default=list, size=None
                    ),
                ),
                ("sections_from", models.CharField(blank=True, max_length=14)),
                (
                    "offices",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        default=list,
                        size=None,
                    ),
                ),
                ("offices_from", models.CharField(blank=True, max_length=14)),
                (
                    "team",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=120),
                        default=list,
                        size=None,
                    ),
                ),
                ("team_unnamed", models.PositiveSmallIntegerField(default=0)),
                (
                    "questions_asked",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "questions_answered",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "quality_score",
                    models.DecimalField(
                        blank=True,
                        db_index=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "quality_points",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                ("quality_max", models.PositiveSmallIntegerField(default=0)),
                (
                    "evaluated_rules",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=4),
                        default=list,
                        size=None,
                    ),
                ),
                ("not_scored_reason", models.CharField(blank=True, max_length=80)),
                ("score_band", models.CharField(blank=True, max_length=8)),
                (
                    "flags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=4),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "flag_count",
                    models.PositiveSmallIntegerField(db_index=True, default=0),
                ),
                ("urgency", models.PositiveSmallIntegerField(db_index=True, default=0)),
                ("urgency_band", models.CharField(blank=True, max_length=6)),
                ("urgency_parts", models.JSONField(default=dict)),
                ("action_points", models.PositiveSmallIntegerField(default=0)),
                ("action_points_open", models.PositiveSmallIntegerField(default=0)),
                ("action_points_overdue", models.PositiveSmallIntegerField(default=0)),
                (
                    "action_points_high_open",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("search", models.TextField(blank=True)),
                ("issues", models.JSONField(default=dict)),
                ("rules_version", models.PositiveIntegerField(default=0)),
                ("refreshed_at", models.DateTimeField()),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="locations.location",
                    ),
                ),
                (
                    "governorate",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="locations.location",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="locations.location",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fmm_visits",
                        to="etools.partnerorganization",
                    ),
                ),
                (
                    "pd",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fmm_visits",
                        to="etools.pca",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="datamart.monitoringsite",
                    ),
                ),
            ],
            options={
                "verbose_name": "visit",
                "verbose_name_plural": "visits",
                "ordering": ("-urgency", "-end_date"),
            },
        ),
        migrations.CreateModel(
            name="VisitActionPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matched_by", models.CharField(max_length=16)),
                (
                    "action_point",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="datamart.actionpoint",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_point_links",
                        to="fmm.visit",
                    ),
                ),
            ],
            options={
                "verbose_name": "action point of a visit",
                "verbose_name_plural": "action points of visits",
            },
        ),
        migrations.CreateModel(
            name="VisitEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datamart_id", models.BigIntegerField(db_index=True)),
                ("entity", models.CharField(blank=True, max_length=255)),
                ("entity_type_raw", models.CharField(blank=True, max_length=100)),
                ("kind", models.CharField(max_length=12)),
                ("pd_match", models.CharField(blank=True, max_length=8)),
                ("cp_output", models.CharField(blank=True, max_length=300)),
                ("rating", models.CharField(max_length=16)),
                ("rating_raw", models.CharField(blank=True, max_length=50)),
                ("hact_q1", models.CharField(blank=True, max_length=16)),
                ("hact_q1_from", models.CharField(blank=True, max_length=8)),
                ("narrative_words", models.PositiveIntegerField(default=0)),
                ("narrative_hash", models.CharField(blank=True, max_length=40)),
                ("narrative_placeholder", models.BooleanField(default=False)),
                (
                    "finding",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="datamart.monitoringfinding",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="etools.partnerorganization",
                    ),
                ),
                (
                    "pd",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="etools.pca",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_rows",
                        to="fmm.visit",
                    ),
                ),
            ],
            options={
                "verbose_name": "monitored entity",
                "verbose_name_plural": "monitored entities",
                "ordering": ("visit", "datamart_id"),
            },
        ),
        migrations.CreateModel(
            name="QuestionAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_id", models.BigIntegerField(db_index=True)),
                (
                    "visit_key",
                    models.CharField(blank=True, db_index=True, max_length=40),
                ),
                ("question_key", models.CharField(max_length=64)),
                ("question_text", models.CharField(blank=True, max_length=500)),
                ("question_order", models.IntegerField(blank=True, null=True)),
                ("is_hact", models.BooleanField(null=True)),
                ("role", models.CharField(blank=True, db_index=True, max_length=6)),
                ("applies_to", models.CharField(blank=True, max_length=8)),
                ("answer_code", models.CharField(blank=True, max_length=12)),
                ("answered", models.BooleanField(default=False)),
                ("placeholder", models.BooleanField(default=False)),
                ("answer_words", models.PositiveIntegerField(default=0)),
                ("summary_words", models.PositiveIntegerField(default=0)),
                ("rating", models.CharField(blank=True, max_length=16)),
                ("method", models.CharField(blank=True, max_length=100)),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="etools.partnerorganization",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="fmm.visit",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="answers",
                        to="fmm.visitentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "checklist answer",
                "verbose_name_plural": "checklist answers",
                "ordering": ("visit", "question_order", "question_key"),
            },
        ),
        migrations.CreateModel(
            name="VisitReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visit_key", models.SlugField(max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reviewed", "Reviewed"),
                            ("follow_up", "Needs follow-up"),
                            ("data_issue", "Data issue"),
                        ],
                        max_length=12,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "visit review",
                "verbose_name_plural": "visit reviews",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="visit",
            index=models.Index(
                fields=["end_date", "status_group"], name="fmm_visit_end_dat_d0c4c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visit",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["section_names"], name="fmm_visit_section_c89f52_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="visit",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["partner_ids"], name="fmm_visit_partner_5429e5_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="visit",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["pd_ids"], name="fmm_visit_pd_ids_f00fd9_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="visit",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["flags"], name="fmm_visit_flags_3391a2_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="visit",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["offices"], name="fmm_visit_offices_3ed0cb_gin"
            ),
        ),
        migrations.AddConstraint(
            model_name="visitactionpoint",
            constraint=models.UniqueConstraint(
                fields=("visit", "action_point"), name="fmm_visit_ap"
            ),
        ),
    ]
