# Generated by Django 5.2.17 on 2026-10-05 12:39

import django.core.validators
import django.db.models.deletion
import neurodb.fmm.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fmm", "0002_visits"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RuleSetting",
            fields=[
                (
                    "code",
                    models.CharField(max_length=4, primary_key=True, serialize=False),
                ),
                ("label", models.CharField(max_length=60)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "points",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(50)]
                    ),
                ),
                (
                    "threshold",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                ("params", models.JSONField(blank=True, default=dict)),
                ("description", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "quality rule",
                "verbose_name_plural": "quality rules",
                "ordering": ("code",),
            },
        ),
        migrations.CreateModel(
            name="RuleSetVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(unique=True)),
                ("snapshot", models.JSONField()),
                ("note", models.CharField(max_length=200)),
                ("created_by_name", models.CharField(max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "restored_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="fmm.rulesetversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "rules version",
                "verbose_name_plural": "rule versions",
                "ordering": ("-number",),
            },
        ),
        migrations.CreateModel(
            name="ScoreSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_evaluated_points", models.PositiveSmallIntegerField(default=30)),
                ("band_high", models.PositiveSmallIntegerField(default=80)),
                ("band_medium", models.PositiveSmallIntegerField(default=50)),
                ("high_flag_count", models.PositiveSmallIntegerField(default=3)),
                ("urgency_red", models.PositiveSmallIntegerField(default=70)),
                ("urgency_amber", models.PositiveSmallIntegerField(default=40)),
                (
                    "urgency_weights",
                    models.JSONField(default=neurodb.fmm.models.default_urgency_weights),
                ),
                ("follow_up_days", models.PositiveSmallIntegerField(default=14)),
                ("report_late_days", models.PositiveSmallIntegerField(default=30)),
                (
                    "question_patterns",
                    models.JSONField(default=neurodb.fmm.models.default_question_patterns),
                ),
                (
                    "role_flag_answers",
                    models.JSONField(default=neurodb.fmm.models.default_role_flag_answers),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "score settings",
                "verbose_name_plural": "score settings",
            },
        ),
        migrations.CreateModel(
            name="VisitRuleResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rule", models.CharField(max_length=4)),
                ("status", models.CharField(db_index=True, max_length=4)),
                (
                    "points",
                    models.DecimalField(decimal_places=1, default=0, max_digits=4),
                ),
                ("max_points", models.PositiveSmallIntegerField(default=0)),
                ("detail_key", models.CharField(blank=True, max_length=40)),
                ("detail", models.CharField(blank=True, max_length=300)),
                ("measure", models.FloatField(blank=True, null=True)),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule_results",
                        to="fmm.visit",
                    ),
                ),
            ],
            options={
                "verbose_name": "rule result",
                "verbose_name_plural": "rule results",
                "ordering": ("visit", "rule"),
                "indexes": [models.Index(fields=["rule", "status"], name="fmm_visitru_rule_5dbb9c_idx")],
                "constraints": [models.UniqueConstraint(fields=("visit", "rule"), name="fmm_visit_rule")],
            },
        ),
    ]
