# Generated by Django 5.2.17 on 2026-10-05 17:37

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fmm", "0004_rule_defaults"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paused_until", models.DateTimeField(blank=True, null=True)),
                ("reason", models.CharField(blank=True, max_length=200)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI pause",
                "verbose_name_plural": "AI pause",
            },
        ),
        migrations.CreateModel(
            name="PromptProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(max_length=20, unique=True)),
                ("label", models.CharField(max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "prompt profile",
                "verbose_name_plural": "prompt profiles",
            },
        ),
        migrations.CreateModel(
            name="ModelCapability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=64)),
                ("effort", models.CharField(max_length=8)),
                ("parameter", models.CharField(max_length=16)),
                ("accepted", models.BooleanField(null=True)),
                ("checked_at", models.DateTimeField()),
                ("detail", models.CharField(blank=True, max_length=300)),
            ],
            options={
                "verbose_name": "sampling check",
                "verbose_name_plural": "sampling checks",
                "ordering": ("model", "effort", "parameter"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("model", "effort", "parameter"),
                        name="fmm_model_capability",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PromptVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("retired", "Retired"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("insights_enabled", models.BooleanField(default=True)),
                (
                    "instructions",
                    models.TextField(
                        validators=[
                            django.core.validators.MinLengthValidator(200),
                            django.core.validators.MaxLengthValidator(8000),
                        ]
                    ),
                ),
                (
                    "max_output_tokens",
                    models.PositiveIntegerField(
                        default=4000,
                        validators=[
                            django.core.validators.MinValueValidator(1000),
                            django.core.validators.MaxValueValidator(32000),
                        ],
                    ),
                ),
                (
                    "narratives_sampled",
                    models.PositiveSmallIntegerField(
                        default=20,
                        help_text="narr: the most texts (narratives, question answers and search snippets) the AI may read per brief, and per chat answer across all of its look-ups. Each is cleaned of names, e-mail addresses, phone numbers and links first. 0 sends no text at all.",
                        validators=[django.core.validators.MaxValueValidator(50)],
                    ),
                ),
                (
                    "comparison_visits",
                    models.PositiveSmallIntegerField(
                        default=15,
                        help_text="comp: how many visits the AI sees in full, as a card (dates, partner, programme document, place, sections, rating with its date, HACT Q1, quality, flags, urgency, action point counts; never a narrative). In the chat, the most visit cards one look-up returns. Every other visit reaches the AI as counts only; the previous period is sent as key figures only.",
                        validators=[django.core.validators.MaxValueValidator(40)],
                    ),
                ),
                (
                    "insights_per_user_per_day",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[django.core.validators.MaxValueValidator(50)],
                    ),
                ),
                ("chat_enabled", models.BooleanField(default=True)),
                (
                    "chat_instructions",
                    models.TextField(
                        validators=[
                            django.core.validators.MinLengthValidator(100),
                            django.core.validators.MaxLengthValidator(6000),
                        ]
                    ),
                ),
                (
                    "chat_max_output_tokens",
                    models.PositiveIntegerField(
                        default=6000,
                        validators=[
                            django.core.validators.MinValueValidator(1000),
                            django.core.validators.MaxValueValidator(32000),
                        ],
                    ),
                ),
                (
                    "chat_per_user_per_day",
                    models.PositiveSmallIntegerField(
                        default=20,
                        validators=[django.core.validators.MaxValueValidator(200)],
                    ),
                ),
                (
                    "chat_max_rounds",
                    models.PositiveSmallIntegerField(
                        default=4,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(8),
                        ],
                    ),
                ),
                (
                    "chat_time_limit",
                    models.PositiveSmallIntegerField(
                        default=120,
                        validators=[
                            django.core.validators.MinValueValidator(30),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                ("model", models.CharField(blank=True, max_length=64)),
                ("effort", models.CharField(default="low", max_length=8)),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("2")),
                        ],
                    ),
                ),
                (
                    "top_p",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                    ),
                ),
                ("note", models.CharField(max_length=300)),
                ("content_hash", models.CharField(max_length=64)),
                ("created_by_name", models.CharField(max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published_by_name", models.CharField(blank=True, max_length=150)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "based_on",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="fmm.promptversion",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="fmm.promptprofile",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "restored_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="fmm.promptversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "prompt version",
                "verbose_name_plural": "prompt versions",
                "ordering": ("profile", "-number"),
            },
        ),
        migrations.AddField(
            model_name="promptprofile",
            name="published",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="fmm.promptversion",
            ),
        ),
        migrations.CreateModel(
            name="Insight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope_hash", models.CharField(db_index=True, max_length=64)),
                ("scope", models.JSONField()),
                ("scope_label", models.CharField(max_length=300)),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("nightly", "Nightly"),
                            ("user", "Regenerate"),
                            ("test", "Test run"),
                        ],
                        max_length=8,
                    ),
                ),
                ("rules_version", models.PositiveIntegerField()),
                ("input_hash", models.CharField(db_index=True, max_length=64)),
                ("data_as_of", models.DateTimeField(null=True)),
                ("called", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Writing"),
                            ("ok", "Written"),
                            ("partial", "Partly written"),
                            ("fallback", "Written by NeuroDB"),
                            ("failed", "Failed"),
                            ("limited", "Limit reached"),
                            ("skipped", "Not written"),
                        ],
                        max_length=8,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=200)),
                ("sections", models.JSONField(default=dict)),
                ("actions", models.JSONField(default=list)),
                ("dropped", models.JSONField(default=dict)),
                (
                    "cited_keys",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=40),
                        default=list,
                        size=None,
                    ),
                ),
                ("sent", models.JSONField(default=dict)),
                ("sent_payload", models.JSONField(blank=True, null=True)),
                ("model", models.CharField(blank=True, max_length=64)),
                ("effort", models.CharField(blank=True, max_length=8)),
                ("max_output_tokens", models.PositiveIntegerField(default=0)),
                ("sampling", models.JSONField(default=dict)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("cached_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="insights",
                        to="fmm.promptversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI brief",
                "verbose_name_plural": "AI briefs",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddConstraint(
            model_name="promptversion",
            constraint=models.UniqueConstraint(
                fields=("profile", "number"), name="fmm_prompt_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="promptversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "published")),
                fields=("profile",),
                name="fmm_one_published_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="insight",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "running")),
                fields=("scope_hash", "version"),
                name="fmm_one_running_insight",
            ),
        ),
    ]
