# Generated by Django 5.2.17 on 2026-10-05 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fmm", "0006_prompt_defaults"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conversation", models.UUIDField(db_index=True)),
                ("scope_hash", models.CharField(max_length=64)),
                ("scope", models.JSONField(default=dict)),
                ("question", models.TextField()),
                ("answer", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "Being answered"),
                            ("answered", "Answered"),
                            ("refused", "Declined"),
                            ("failed", "Failed"),
                            ("limited", "Limit reached"),
                        ],
                        max_length=12,
                    ),
                ),
                ("checks", models.JSONField(default=dict)),
                ("tools", models.JSONField(default=list)),
                ("texts_sent", models.PositiveSmallIntegerField(default=0)),
                ("model", models.CharField(blank=True, max_length=64)),
                ("sampling", models.JSONField(default=dict)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("cache_read_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="fmm.promptversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "chat question",
                "verbose_name_plural": "chat questions",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="fmm_chatque_user_id_5c464c_idx",
                    ),
                    models.Index(
                        fields=["user", "conversation", "created_at"],
                        name="fmm_chatque_user_id_528f8e_idx",
                    ),
                ],
            },
        ),
    ]
