# Generated by Django 5.2.17 on 2026-10-06 10:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fmm", "0007_chat"),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="modality",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name="visit",
            name="programme_areas",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="visitentity",
            name="row_answers",
            field=models.JSONField(default=dict),
        ),
    ]
