# Generated by Django 5.2.17 on 2026-10-06 10:32

import django.core.validators
import neurodb.fmm.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fmm", "0009_fms_scoring"),
    ]

    operations = [
        migrations.AddField(
            model_name="promptversion",
            name="chat_examples",
            field=models.JSONField(
                blank=True,
                default=neurodb.fmm.models.default_chat_examples,
                help_text="The starter questions Chat with Data offers, one per line (at most 8).",
            ),
        ),
        migrations.AddField(
            model_name="promptversion",
            name="sections",
            field=models.JSONField(
                default=neurodb.fmm.models.default_insight_sections,
                help_text="The parts of the brief, in order: each with its key (what the AI writes under; never shown), its label (the heading on the page), its format (paragraph or bullets) and its limit: the most sentences or bullets it may hold. The key action_points holds the priority action points (priority, section, partner, action, responsible party, timeframe).",
            ),
        ),
        migrations.AlterField(
            model_name="promptversion",
            name="comparison_visits",
            field=models.PositiveSmallIntegerField(
                default=15,
                help_text="comp (compliance depth): how many of the most frequent quality flags the AI receives with each brief, each with its rule, its number of visits and a few example visits. Higher gives more nuanced findings and a longer prompt.",
                validators=[django.core.validators.MaxValueValidator(40)],
                verbose_name="compliance depth",
            ),
        ),
        migrations.AlterField(
            model_name="promptversion",
            name="narratives_sampled",
            field=models.PositiveSmallIntegerField(
                default=20,
                help_text="narr: the most monitors' narratives the AI may read per brief, each with its Q1, Q2 and Q3 answers; and per chat answer, the most texts (narratives, question answers and search snippets) across all of its look-ups. Each is cleaned of names, e-mail addresses, phone numbers and links first. 0 sends no text at all.",
                validators=[django.core.validators.MaxValueValidator(50)],
            ),
        ),
    ]
