"""Release 2, stage B: FMS's rule model. A quality rule gets a type, a score category, a group, a deduction
and a flag template (its points and threshold go); the score settings get the score categories and the
AI checks' settings (the fewest evaluated points go: FMS scores every visit); a visit gets the columns
derived at the build, its provisional score and its deductions per category; a checklist answer its
category and Likert value; a prompt version the AI checks' instructions; and two tables: the field
offices' staff lists (R19) and the AI checks' answers. The rules themselves are seeded by 0013."""

# Generated by Django 5.2.17 on 2026-10-06 13:06

import django.core.validators
import django.db.models.deletion
import neurodb.fmm.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fmm", "0011_lebanon_prompt_v2"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rulesetting",
            name="points",
        ),
        migrations.RemoveField(
            model_name="rulesetting",
            name="threshold",
        ),
        migrations.RemoveField(
            model_name="scoresetting",
            name="min_evaluated_points",
        ),
        migrations.AddField(
            model_name="promptversion",
            name="rule_prompts",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='The instructions of the AI checks, one per prompt key a narrative quality rule names (for example "evidence_sufficiency"): what the check looks for and when it passes. NeuroDB adds its fixed rules and the answer format (passed or not, and one or two sentences why).',
            ),
        ),
        migrations.AddField(
            model_name="questionanswer",
            name="category",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="questionanswer",
            name="likert",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="questionanswer",
            name="scale",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rulesetting",
            name="category",
            field=models.SlugField(default="completeness", max_length=40),
        ),
        migrations.AddField(
            model_name="rulesetting",
            name="deduction",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="rulesetting",
            name="flag_template",
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name="rulesetting",
            name="group",
            field=models.CharField(
                choices=[("core", "Core"), ("additional", "Additional")],
                default="additional",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="rulesetting",
            name="hact_spec",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="rulesetting",
            name="type",
            field=models.CharField(
                choices=[
                    ("completeness", "Completeness (fields present)"),
                    ("deterministic", "Deterministic (scoring bands)"),
                    ("narrative", "AI check"),
                    ("reference_check", "Reference check"),
                ],
                default="completeness",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="scoresetting",
            name="ai_checks",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="scoresetting",
            name="ai_max_output_tokens",
            field=models.PositiveIntegerField(
                default=2000,
                validators=[
                    django.core.validators.MinValueValidator(500),
                    django.core.validators.MaxValueValidator(16000),
                ],
            ),
        ),
        migrations.AddField(
            model_name="scoresetting",
            name="ai_model",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="scoresetting",
            name="ai_temperature",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.30"),
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("2")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="scoresetting",
            name="ai_text_chars",
            field=models.PositiveSmallIntegerField(
                default=1500,
                validators=[
                    django.core.validators.MinValueValidator(200),
                    django.core.validators.MaxValueValidator(6000),
                ],
            ),
        ),
        migrations.AddField(
            model_name="scoresetting",
            name="categories",
            field=models.JSONField(default=neurodb.fmm.models.default_categories),
        ),
        migrations.AddField(
            model_name="visit",
            name="action_points_assigned",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="visit",
            name="ai_pending",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="visit",
            name="attachments_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="category_deductions",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="visit",
            name="fmq_answered_categories",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="fmq_answered_pct",
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="method_count",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="provisional_score",
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="red_flag_count",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rulesetting",
            name="label",
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name="visitruleresult",
            name="detail",
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name="visitruleresult",
            name="max_points",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name="visitruleresult",
            name="status",
            field=models.CharField(db_index=True, max_length=8),
        ),
        migrations.CreateModel(
            name="FieldOfficeStaff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("office", models.CharField(max_length=200, unique=True)),
                (
                    "emails",
                    models.TextField(blank=True, help_text="one e-mail address per line"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "field office staff list",
                "verbose_name_plural": "field office staff lists",
                "ordering": ("office",),
            },
        ),
        migrations.CreateModel(
            name="VisitAICheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visit_key", models.CharField(max_length=40)),
                ("rule", models.CharField(max_length=4)),
                ("input_hash", models.CharField(max_length=64)),
                ("prompt_hash", models.CharField(max_length=64)),
                ("model", models.CharField(blank=True, max_length=64)),
                ("passed", models.BooleanField()),
                ("detail", models.CharField(blank=True, max_length=400)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("checked_at", models.DateTimeField(db_index=True)),
            ],
            options={
                "verbose_name": "AI check",
                "verbose_name_plural": "AI checks",
                "ordering": ("visit_key", "rule"),
                "constraints": [
                    models.UniqueConstraint(fields=("visit_key", "rule"), name="fmm_visit_ai_check")
                ],
            },
        ),
    ]
