# Generated by Django 5.2.17 on 2026-10-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fmm", "0016_powerbi_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="powerbikey",
            name="hour_started",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="powerbikey",
            name="hour_uses",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
