# Generated by Django 5.2.17 on 2026-09-23 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssistantQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conversation",
                    models.UUIDField(
                        blank=True,
                        help_text="groups a question with its follow-ups",
                        null=True,
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("answered", "Answered"),
                            ("refused", "Declined by the model"),
                            ("failed", "Failed"),
                            ("limited", "Over the hourly limit"),
                        ],
                        db_index=True,
                        default="answered",
                        max_length=10,
                    ),
                ),
                (
                    "tools",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="data lookups made, in order",
                    ),
                ),
                ("model", models.CharField(blank=True, max_length=64)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("cache_read_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI question",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="assistant_a_user_id_a4b41f_idx",
                    ),
                    models.Index(
                        fields=["user", "conversation", "created_at"],
                        name="assistant_a_user_id_3c9740_idx",
                    ),
                ],
            },
        ),
    ]
