# Generated by Django 5.2.17 on 2026-10-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField(help_text="local date of the calls")),
                (
                    "feature",
                    models.CharField(
                        help_text="ask, review, digest, knowledge, periodic, cpd or watch",
                        max_length=20,
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True,
                        help_text="the model the calls asked for",
                        max_length=64,
                    ),
                ),
                ("calls", models.PositiveIntegerField(default=0)),
                (
                    "input_tokens",
                    models.PositiveBigIntegerField(
                        default=0, help_text="prompt tokens not read from the cache"
                    ),
                ),
                (
                    "cached_tokens",
                    models.PositiveBigIntegerField(
                        default=0, help_text="prompt tokens read from the cache"
                    ),
                ),
                (
                    "output_tokens",
                    models.PositiveBigIntegerField(
                        default=0, help_text="includes the reasoning tokens"
                    ),
                ),
            ],
            options={
                "verbose_name": "AI use",
                "verbose_name_plural": "AI use",
                "ordering": ("-day", "feature", "model"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("day", "feature", "model"),
                        name="assistant_aiusage_one_per_day",
                    )
                ],
            },
        ),
    ]
