# Generated by Django 5.2.17 on 2026-09-26 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="running",
                        max_length=16,
                    ),
                ),
                (
                    "triggered_by",
                    models.CharField(
                        blank=True,
                        help_text="the job, a command or the username",
                        max_length=150,
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True, help_text="the narrative, 4 to 6 sentences"
                    ),
                ),
                (
                    "narrated_by",
                    models.CharField(
                        blank=True,
                        help_text="the model that wrote it, or template",
                        max_length=100,
                    ),
                ),
                ("checks_run", models.PositiveIntegerField(default=0)),
                ("stats", models.JSONField(blank=True, default=dict)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
                ("model_input_tokens", models.PositiveIntegerField(default=0)),
                ("model_output_tokens", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "daily review",
                "verbose_name_plural": "daily reviews",
                "ordering": ("-date",),
            },
        ),
        migrations.CreateModel(
            name="ReviewFinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="stable across days, e.g. reports_overdue:LEB/PD1",
                        max_length=300,
                    ),
                ),
                (
                    "check_id",
                    models.CharField(
                        db_index=True, max_length=40, verbose_name="check"
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("warning", "Warning"),
                            ("info", "To note"),
                            ("good", "Good news"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        blank=True,
                        help_text="eTools section name; empty = country",
                        max_length=128,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("detail", models.TextField(blank=True)),
                (
                    "evidence",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"read": ..., "records": [...], "numbers": {...}}',
                    ),
                ),
                (
                    "children",
                    models.IntegerField(
                        blank=True,
                        help_text="children behind target, when known",
                        null=True,
                    ),
                ),
                ("url", models.CharField(blank=True, max_length=500)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("still_open", "Still open"),
                            ("resolved", "Resolved"),
                        ],
                        default="new",
                        max_length=16,
                    ),
                ),
                ("rank", models.PositiveIntegerField(default=0)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="review.dailyreview",
                    ),
                ),
            ],
            options={
                "verbose_name": "review finding",
                "verbose_name_plural": "review findings",
                "ordering": ("rank", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("review", "key"), name="review_finding_key_per_review"
                    )
                ],
            },
        ),
    ]
