# Generated by Django 5.2.17 on 2026-09-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FindingAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="the finding's key, stable across days",
                        max_length=300,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="the finding's title when assigned",
                        max_length=300,
                    ),
                ),
                ("section", models.CharField(blank=True, max_length=128)),
                (
                    "owner",
                    models.CharField(
                        blank=True,
                        help_text="a role or a team, e.g. Chief of Education, not a person",
                        max_length=120,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("raised", "Raised"),
                            ("acknowledged", "Acknowledged"),
                            ("assigned", "Assigned"),
                            ("closed", "Closed"),
                        ],
                        default="acknowledged",
                        max_length=16,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.CharField(blank=True, max_length=150)),
            ],
            options={
                "verbose_name": "finding assignment",
                "verbose_name_plural": "finding assignments",
                "ordering": ("due_date", "id"),
            },
        ),
    ]
