# Generated by Django 5.2.17 on 2026-09-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0002_finding_assignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreview",
            name="decided_by",
            field=models.CharField(
                blank=True,
                help_text="the model that chose the decisions, or rules",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="dailyreview",
            name="decisions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="what management should decide, chosen and written by the AI from the findings",
            ),
        ),
    ]
