# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-05-01 14:44
from __future__ import unicode_literals

#import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationtype',
            options={'ordering': ['name'], 'verbose_name': 'Location Type'},
        ),
        migrations.RemoveField(
            model_name='location',
            name='description',
        ),
        migrations.AddField(
            model_name='location',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        # migrations.AddField(
        #     model_name='location',
        #     name='geom',
        #     field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='Geo Point'),
        # ),
        migrations.AddField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='location',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        # migrations.AddField(
        #     model_name='location',
        #     name='point',
        #     field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Point'),
        # ),
        migrations.AddField(
            model_name='locationtype',
            name='admin_level',
            field=models.PositiveSmallIntegerField(null=True, unique=True, verbose_name='Admin Level'),
        ),
        migrations.AddField(
            model_name='locationtype',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='locationtype',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=254, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='p_code',
            field=models.CharField(blank=True, default=b'', max_length=32, verbose_name='P Code'),
        ),
        migrations.AlterField(
            model_name='location',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='locations.Location', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='locationtype',
            name='name',
            field=models.CharField(max_length=254, unique=True, verbose_name='Name'),
        ),
    ]
