# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-05-01 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20190501_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.LocationType', verbose_name='Location Type'),
        ),
    ]
