# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-31 18:54
from __future__ import unicode_literals

# import django.contrib.gis.db.models.fields
from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_remove_location_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='locations.Location', verbose_name='Parent'),
        ),
    ]
