# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-06-06 19:19
from __future__ import unicode_literals

# import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_auto_20200531_1854'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='location',
        #     name='geom',
        #     field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='Geo Point'),
        # ),
        # migrations.AddField(
        #     model_name='location',
        #     name='point',
        #     field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Point'),
        # ),
    ]
