# Generated by Django 3.2.12 on 2022-04-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_auto_20220310_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationsMasterList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality_pcode', models.CharField(blank=True, max_length=100, null=True)),
                ('locality_name_arabic', models.CharField(blank=True, max_length=100, null=True)),
                ('locality_name_english', models.CharField(blank=True, max_length=100, null=True)),
                ('cas_name_english', models.CharField(blank=True, max_length=100, null=True)),
                ('cas_name_arabic', models.CharField(blank=True, max_length=100, null=True)),
                ('cas_code', models.CharField(blank=True, max_length=100, null=True)),
                ('governorate', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.CharField(blank=True, max_length=100, null=True)),
                ('longitude', models.CharField(blank=True, max_length=100, null=True)),
                ('cad_code', models.CharField(blank=True, max_length=100, null=True)),
                ('municipality_id', models.CharField(blank=True, max_length=100, null=True)),
                ('municipality_name_english', models.CharField(blank=True, max_length=100, null=True)),
                ('municipality_name_arabic', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='cas_code',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Cas Code'),
        ),
    ]
