# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-10 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=254)),
                ('location_type', models.CharField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'activities',
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='AttributeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=254)),
                ('multiple_allowed', models.BooleanField()),
                ('mandatory', models.BooleanField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activityinfo.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_id', models.PositiveIntegerField(unique=True, verbose_name=b'ActivityInfo ID')),
                ('name', models.CharField(max_length=254)),
                ('username', models.CharField(max_length=254)),
                ('password', models.CharField(max_length=254)),
                ('description', models.CharField(max_length=254, null=True)),
                ('country_name', models.CharField(max_length=254, null=True)),
                ('ai_country_id', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=254)),
                ('units', models.CharField(max_length=254)),
                ('category', models.CharField(max_length=254, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activityinfo.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=254)),
                ('full_name', models.CharField(max_length=254, null=True)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activityinfo.Database')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='attribute',
            name='attribute_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activityinfo.AttributeGroup'),
        ),
        migrations.AddField(
            model_name='activity',
            name='database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activityinfo.Database'),
        ),
    ]
