# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-26 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='units',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
