# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-24 11:33
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0002_auto_20180326_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('end_date', models.CharField(blank=True, max_length=250, null=True)),
                ('form', models.CharField(blank=True, max_length=250, null=True)),
                ('form_category', models.CharField(blank=True, max_length=250, null=True)),
                ('indicator_category', models.CharField(blank=True, max_length=250, null=True)),
                ('indicator_id', models.CharField(blank=True, max_length=250, null=True)),
                ('indicator_name', models.CharField(blank=True, max_length=250, null=True)),
                ('indicator_units', models.CharField(blank=True, max_length=250, null=True)),
                ('indicator_value', models.CharField(blank=True, max_length=250, null=True)),
                ('location_adminlevel_cadastral_area', models.CharField(blank=True, max_length=250, null=True)),
                ('location_adminlevel_cadastral_area_code', models.CharField(blank=True, max_length=250, null=True)),
                ('location_adminlevel_caza', models.CharField(blank=True, max_length=250, null=True)),
                ('location_adminlevel_caza_code', models.CharField(blank=True, max_length=250, null=True)),
                ('location_adminlevel_governorate', models.CharField(blank=True, max_length=250, null=True)),
                ('location_adminlevel_governorate_code', models.CharField(blank=True, max_length=250, null=True)),
                ('location_alternate_name', models.CharField(blank=True, max_length=250, null=True)),
                ('location_latitude', models.CharField(blank=True, max_length=250, null=True)),
                ('location_longitude', models.CharField(blank=True, max_length=250, null=True)),
                ('location_name', models.CharField(blank=True, max_length=250, null=True)),
                ('partner_description', models.CharField(blank=True, max_length=250, null=True)),
                ('partner_id', models.CharField(blank=True, max_length=250, null=True)),
                ('partner_label', models.CharField(blank=True, max_length=250, null=True)),
                ('project_description', models.CharField(blank=True, max_length=250, null=True)),
                ('project_label', models.CharField(blank=True, max_length=250, null=True)),
                ('lcrp_appeal', models.CharField(blank=True, max_length=250, null=True)),
                ('funded_by', models.CharField(blank=True, max_length=250, null=True)),
                ('report_id', models.CharField(blank=True, max_length=250, null=True)),
                ('site_id', models.CharField(blank=True, max_length=250, null=True)),
                ('start_date', models.CharField(blank=True, max_length=250, null=True)),
                ('outreach_platform', models.CharField(blank=True, max_length=250, null=True)),
                ('database_id', models.CharField(blank=True, max_length=250, null=True)),
                ('database', models.CharField(blank=True, max_length=250, null=True)),
                ('month', models.CharField(blank=True, max_length=250, null=True)),
                ('year', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
