# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-24 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180724_1210'),
        ('activityinfo', '0004_activityreport_governorate'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Section'),
        ),
    ]
