# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-24 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0005_database_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityreport',
            name='month_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
