# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-10-27 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0006_activityreport_month_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='awp_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='cumulative_results',
            field=models.PositiveIntegerField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='indicator',
            name='reporting_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='target',
            field=models.PositiveIntegerField(default=0, max_length=20),
        ),
    ]
