# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-10-27 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0007_auto_20181027_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='dashboard_link',
            field=models.URLField(max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='cumulative_results',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='target',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
