# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-10-30 13:24
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0008_auto_20181027_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='mapping_extraction1',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='database',
            name='mapping_extraction2',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='database',
            name='mapping_extraction3',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
