# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-11-15 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0011_indicatorcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityreport',
            name='day',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
