# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-19 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0012_activityreport_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityreport',
            name='indicator_awp_code',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
