# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-12-07 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0013_activityreport_indicator_awp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityreport',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
