# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-12-07 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0014_auto_20181207_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityreport',
            name='master_indicator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activityreport',
            name='master_indicator_sub',
            field=models.BooleanField(default=False),
        ),
    ]
