# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-12-08 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0017_database_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='year',
            field=models.CharField(blank=True, choices=[(b'2017', b'2017'), (b'2018', b'2018'), (b'2019', b'2019'), (b'2020', b'2020'), (b'2021', b'2021'), (b'2022', b'2022'), (b'2023', b'2023'), (b'2024', b'2024'), (b'2025', b'2025'), (b'2026', b'2026'), (b'2027', b'2027'), (b'2028', b'2028'), (b'2029', b'2029'), (b'2030', b'2030')], max_length=250, null=True),
        ),
    ]
