# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-12-08 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0019_auto_20181208_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='indicator_details',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='indicator_info',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='indicator_master',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
