# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-12-10 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0020_auto_20181208_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='sub_indicators',
            field=models.ManyToManyField(blank=True, null=True, related_name='_indicator_sub_indicators_+', to='activityinfo.Indicator'),
        ),
    ]
