# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-12-10 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0022_auto_20181210_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicator',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='activityreport',
            name='indicator_sub_value',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='target_sub_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
