# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-12-11 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0023_auto_20181210_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='summation_sub_indicators',
            field=models.ManyToManyField(related_name='_indicator_summation_sub_indicators_+', to='activityinfo.Indicator'),
        ),
    ]
