# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-12-11 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0024_indicator_summation_sub_indicators'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityreport',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
