# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-12-11 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0027_auto_20181211_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='category',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
