# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-12-12 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0028_auto_20181211_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityreport',
            name='ai_indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activityinfo.Indicator'),
        ),
    ]
