# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-12-13 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0029_activityreport_ai_indicator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityreport',
            name='indicator_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
