# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-12-18 21:42
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0031_auto_20181216_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='values_partners_gov',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
