# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-12-19 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0032_indicator_values_partners_gov'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='status_color',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
