# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-02 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0034_activityreport_pending'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('current', models.BooleanField(default=False)),
            ],
        ),
    ]
