# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-02 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0035_reportingyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='reporting_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activityinfo.ReportingYear'),
        ),
    ]
