# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-02 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0036_database_reporting_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='description',
            field=models.CharField(max_length=1500, null=True),
        ),
    ]
