# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-02 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0037_auto_20190102_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='description',
            field=models.CharField(default='', blank=True, max_length=1500, null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indicator',
            name='awp_code',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
