# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-02 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0038_auto_20190102_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='name',
            field=models.CharField(max_length=1500),
        ),
    ]
