# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-02 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0039_auto_20190102_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='tag_age',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='tag_disability',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='tag_gender',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='tag_nationality',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
