# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-05 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0041_auto_20190102_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('type', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
