# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-05 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0043_auto_20190105_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatortag',
            name='tag_field',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
