# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-11 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0046_indicator_none_ai_indicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='denominator_indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='activityinfo.Indicator'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='measurement_type',
            field=models.CharField(blank=True, choices=[(b'numeric', b'Numeric'), (b'percentage', b'Percentage'), (b'weighting', b'Weighting')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='numerator_indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='activityinfo.Indicator'),
        ),
    ]
