# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-16 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0047_auto_20190111_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='label',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
