# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-17 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0050_indicator_funded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='denominator_summation',
            field=models.ManyToManyField(blank=True, related_name='_indicator_denominator_summation_+', to='activityinfo.Indicator'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='numerator_summation',
            field=models.ManyToManyField(blank=True, related_name='_indicator_numerator_summation_+', to='activityinfo.Indicator'),
        ),
    ]
