# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-19 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0051_auto_20190117_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='mapped_db',
            field=models.BooleanField(default=True),
        ),
    ]
