# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-19 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0052_database_mapped_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='indicatorcategory',
            name='name',
            field=models.CharField(max_length=1500),
        ),
    ]
