# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-31 18:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activityinfo', '0053_auto_20190119_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='focal_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='database',
            name='label',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
