# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-04 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0054_auto_20190131_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='individual_indicator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='indicator',
            name='sequence',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
