# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-06 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0057_auto_20190204_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='explication',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
