# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-06 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0058_indicator_explication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='explication',
            field=models.TextField(blank=True, null=True),
        ),
    ]
