# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-08 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0059_auto_20190206_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='is_funded_by_unicef',
            field=models.BooleanField(default=False),
        ),
    ]
