# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-08 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0060_database_is_funded_by_unicef'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityreport',
            name='indicator_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
