# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-09 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0061_auto_20190208_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='calculated_indicator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='indicator',
            name='calculated_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
