# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-25 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0063_indicator_cumulative_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='hpm_indicator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='indicator',
            name='separator_indicator',
            field=models.BooleanField(default=False),
        ),
    ]
