# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-25 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0064_auto_20190225_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityReportLive',
            fields=[
                ('activityreport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activityinfo.ActivityReport')),
            ],
            options={
                'ordering': ['id'],
            },
            bases=('activityinfo.activityreport',),
        ),
    ]
