# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-02 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0066_auto_20190225_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='target_sector',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
