# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-03 11:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0067_indicator_target_sector'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicator',
            options={'ordering': ['name']},
        ),
    ]
