# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-03 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0068_auto_20190303_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityreport',
            name='partner_ai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='activityinfo.Partner'),
        ),
    ]
