# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-03 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0070_partner_partner_etools'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='number',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
