# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-04 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0071_partner_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='denominator_multiplication',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='measurement_type',
            field=models.CharField(blank=True, choices=[(b'numeric', b'Numeric'), (b'percentage', b'Percentage'), (b'percentage_x', b'Percentage multiple X'), (b'weighting', b'Weighting')], max_length=250, null=True),
        ),
    ]
