# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-12 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0073_auto_20190311_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='master_indicator_sub_sub',
            field=models.BooleanField(default=False, verbose_name=b'Master indicator level 3'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='master_indicator',
            field=models.BooleanField(default=False, verbose_name=b'Master indicator level 1'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='master_indicator_sub',
            field=models.BooleanField(default=False, verbose_name=b'Master indicator level 2'),
        ),
    ]
