# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-26 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0077_auto_20190319_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='none_ai_database',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='activityinfo.Database'),
        ),
    ]
