# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-26 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0078_activity_none_ai_database'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='ai_indicator',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
