# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-26 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0081_indicator_values_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatortag',
            name='label',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
