# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-07 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0082_indicatortag_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='main_master_indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='activityinfo.Indicator'),
        ),
    ]
