# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-19 21:09
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0083_indicator_main_master_indicator'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLevelEntities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=650)),
                ('bounds', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminLevels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=650)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=650)),
                ('admin_entities', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('longitude', models.CharField(max_length=250)),
                ('latitude', models.CharField(max_length=250)),
                ('entities', models.ManyToManyField(blank=True, related_name='entity_locations', to='activityinfo.AdminLevelEntities')),
            ],
        ),
        migrations.CreateModel(
            name='LocationTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=650)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activityinfo.LocationTypes')),
            ],
        ),
        migrations.AddField(
            model_name='locations',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activityinfo.LocationTypes'),
        ),
        migrations.AddField(
            model_name='adminlevelentities',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activityinfo.AdminLevels'),
        ),
        migrations.AddField(
            model_name='adminlevelentities',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activityinfo.AdminLevelEntities'),
        ),
    ]
