# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-20 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0084_auto_20190519_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlevelentities',
            name='code',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='locations',
            name='code',
            field=models.CharField(max_length=250),
        ),
    ]
