# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-21 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0085_auto_20190520_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatortag',
            name='sequence',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
