# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-24 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0086_indicatortag_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityreport',
            name='location_cadastral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='activityinfo.Locations'),
        ),
        migrations.AddField(
            model_name='activityreport',
            name='location_caza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='activityinfo.Locations'),
        ),
        migrations.AddField(
            model_name='activityreport',
            name='location_governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='activityinfo.Locations'),
        ),
    ]
