# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-24 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0088_auto_20190524_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='database',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activityinfo.Database'),
        ),
    ]
