# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-24 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0089_sites_database'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sites',
            name='activity_name',
        ),
    ]
