# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-24 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0090_remove_sites_activity_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sites',
            name='latitude',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sites',
            name='longitude',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sites',
            name='name',
            field=models.CharField(blank=True, max_length=650, null=True),
        ),
        migrations.AlterField(
            model_name='sites',
            name='partner_name',
            field=models.CharField(blank=True, max_length=650, null=True),
        ),
    ]
