# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-27 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0091_auto_20190524_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='is_sector',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='indicator',
            name='is_sector',
            field=models.BooleanField(default=False),
        ),
    ]
