# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-28 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etools', '0049_auto_20190522_1352'),
        ('activityinfo', '0095_indicator_is_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='programme_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='etools.PCA'),
        ),
    ]
