# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-11 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etools', '0052_auto_20190611_1050'),
        ('activityinfo', '0097_auto_20190603_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='programme_documents',
            field=models.ManyToManyField(blank=True, related_name='_activity_programme_documents_+', to='etools.PCA'),
        ),
    ]
