# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-20 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0098_activity_programme_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityreport',
            name='ai_indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_indicators', to='activityinfo.Indicator'),
        ),
    ]
