# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-24 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0099_auto_20190620_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='support_disability',
            field=models.BooleanField(default=False),
        ),
    ]
