# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-04 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0102_activity_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='db_id',
            field=models.CharField(blank=True, max_length=254, null=True, unique=True, verbose_name=b'ActivityInfo ID'),
        ),
    ]
