# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-06 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0104_activity_ai_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='ai_form_id',
            field=models.CharField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='ai_category_id',
            field=models.CharField(max_length=254, null=True, unique=True),
        ),
    ]
