# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-06 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0105_auto_20200206_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='ai_category_id',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='location_type',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
