# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-06 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0106_auto_20200206_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='ai_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
