# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-19 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0107_auto_20200206_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['name'], 'verbose_name_plural': 'activities'},
        ),
        migrations.AddField(
            model_name='activityreport',
            name='project_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityreport',
            name='project_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityreport',
            name='site_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
