# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-09 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0108_auto_20200219_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.PositiveIntegerField(default=0)),
                ('ai_indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activityinfo.Indicator')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activityinfo.Partner')),
            ],
        ),
    ]
