# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-10 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0109_indicatorpartner'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='year',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
