# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-10 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0111_auto_20200310_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='ai_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
