# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-10 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0112_auto_20200310_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='database',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activityinfo.Database'),
        ),
    ]
