# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-11 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0113_auto_20200310_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportingyear',
            name='database_id',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='reportingyear',
            name='form_id',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
