# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-11 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0115_auto_20200311_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='display',
            field=models.BooleanField(default=False),
        ),
    ]
