# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-16 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0116_auto_20200311_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveactivityreport',
            name='project_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liveactivityreport',
            name='project_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liveactivityreport',
            name='site_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
