# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-18 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0117_auto_20200316_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='hpm_label',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
