# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-19 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0118_database_hpm_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='hpm_sequence',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
