# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-19 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0119_database_hpm_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='awp_sector_code',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name=b'RWP_Sector'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='target_hpm',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
