# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-25 23:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0122_indicator_is_cumulative'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicator',
            old_name='is_Cumulative',
            new_name='is_cumulative',
        ),
    ]
