# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-27 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0123_auto_20200326_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='hpm_comment',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
