# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-27 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0124_indicator_hpm_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='hpm_comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
