# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-27 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0125_auto_20200327_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='has_hpm_note',
            field=models.BooleanField(default=True),
        ),
    ]
