# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-12 11:59
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0126_indicator_has_hpm_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='qualitative_target',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='result',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='result_status',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='has_hpm_note',
            field=models.BooleanField(default=False),
        ),
    ]
