# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-14 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0127_auto_20200412_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='sector_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
