# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-14 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0128_database_sector_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='database',
            old_name='sector_name',
            new_name='sector_label',
        ),
    ]
