# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-14 22:20
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0129_auto_20200414_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='comment',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='hpm_additional_cumulative',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
