# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-16 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0130_auto_20200415_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='tag_focus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='activityinfo.IndicatorTag'),
        ),
    ]
