# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-19 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etools', '0052_auto_20190611_1050'),
        ('activityinfo', '0131_indicator_tag_focus'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityreport',
            name='programme_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='etools.PCA'),
        ),
    ]
