# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-22 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0132_activityreport_programme_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportingyear',
            name='year',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
