# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-25 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0133_reportingyear_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='database',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='reportingyear',
            options={'ordering': ['name']},
        ),
    ]
