# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-25 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0134_auto_20200424_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='support_COVID',
            field=models.BooleanField(default=False),
        ),
    ]
