# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-27 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0135_indicator_support_covid'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='hpm_global_indicator',
            field=models.BooleanField(default=False),
        ),
    ]
