# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-27 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0134_auto_20200425_2041'),
        ('activityinfo', '0136_indicator_hpm_global_indicator'),
    ]

    operations = [
    ]
