# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-28 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0137_merge_20200428_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicator',
            old_name='result',
            new_name='results',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='cumulative_results',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='hpm_comment',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='result_status',
        ),
        migrations.AddField(
            model_name='indicator',
            name='qualitative_result',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
