# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-29 00:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0138_auto_20200428_1658'),
        ('activityinfo', '0137_merge_20200427_2038'),
    ]

    operations = [
    ]
