# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-06 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0139_merge_20200429_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityreport',
            name='reporting_section',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
