# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-15 13:13
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0141_liveactivityreport_reporting_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='values_sections',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='values_sections_gov',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='values_sections_partners',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='values_sections_partners_gov',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
