# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-22 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0143_auto_20200516_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='have_covid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='database',
            name='have_governorates',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='database',
            name='have_offices',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='database',
            name='have_partners',
            field=models.BooleanField(default=False),
        ),
    ]
