# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-20 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0143_auto_20200516_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='related_indicator',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
