# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-22 07:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0144_auto_20200522_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='configs',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AddField(
            model_name='database',
            name='have_internal_reporting',
            field=models.BooleanField(default=False),
        ),
    ]
