# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-21 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0144_indicator_related_indicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityreport',
            name='support_covid',
            field=models.BooleanField(default=False),
        ),
    ]
