# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-22 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0145_auto_20200522_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='have_covid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='have_governorates',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='have_internal_reporting',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='have_partners',
            field=models.BooleanField(default=True),
        ),
    ]
