# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-23 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0145_activityreport_support_covid'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='is_current_extraction',
            field=models.BooleanField(default=False),
        ),
    ]
