# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-24 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0146_auto_20200522_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='second_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='activityinfo.Activity'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='activityinfo.Activity'),
        ),
    ]
