# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-24 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0146_database_is_current_extraction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='related_indicator',
        ),
    ]
