# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-24 15:42
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0148_remove_activityreport_support_covid'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityreport',
            name='support_covid',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liveactivityreport',
            name='support_covid',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
