# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-25 05:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0147_auto_20200524_1115'),
        ('activityinfo', '0149_auto_20200524_1842'),
    ]

    operations = [
    ]
