# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-26 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0153_auto_20200526_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='support_covid',
            field=models.BooleanField(default=False),
        ),
    ]
