# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-29 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0155_database_have_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='third_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='activityinfo.Activity'),
        ),
    ]
