# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-28 06:58
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0155_database_have_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='values_crisis_cumulative_live',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='values_crisis_gov_live',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='values_crisis_live',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='values_crisis_partners_gov_live',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='values_crisis_partners_live',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
    ]
