# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-29 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0156_auto_20200528_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='is_imported',
            field=models.BooleanField(default=False),
        ),
    ]
