# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-29 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0156_indicator_third_activity'),
        ('activityinfo', '0157_indicator_is_imported'),
    ]

    operations = [
    ]
