# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-29 17:30
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0158_merge_20200529_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='targets',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
