# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-30 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0158_merge_20200529_1948'),
        ('activityinfo', '0159_indicator_targets'),
    ]

    operations = [
    ]
