# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-31 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0160_merge_20200530_1605'),
        ('activityinfo', '0160_auto_20200529_2140'),
    ]

    operations = [
    ]
