# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-06-03 08:36
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0161_merge_20200531_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='values_tags_weekly',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
    ]
