# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-06-10 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0162_indicator_values_tags_weekly'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='is_imported_by_calculation',
            field=models.BooleanField(default=False),
        ),
    ]
