# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-06-15 11:03
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0163_indicator_is_imported_by_calculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='highest_vales',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
    ]
