# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-06-15 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0164_indicator_highest_vales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicator',
            old_name='highest_vales',
            new_name='highest_values',
        ),
    ]
