# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-06-15 16:23
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0165_auto_20200615_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='highest_values_live',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
    ]
