# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-01-04 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0166_indicator_highest_values_live'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='ai_id',
            field=models.PositiveIntegerField(unique=True, verbose_name=b'ID'),
        ),
        migrations.AlterField(
            model_name='database',
            name='db_id',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name=b'ActivityInfo ID'),
        ),
    ]
