# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-01-04 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0167_auto_20210104_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='ai_form_id',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_indicators', to='activityinfo.Activity'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='second_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_activity_indicators', to='activityinfo.Activity'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='third_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_activity_indicators', to='activityinfo.Activity'),
        ),
    ]
