# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-02-07 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0168_auto_20210104_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='parent_id',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name=b'ActivityInfo Parent ID'),
        ),
    ]
