# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-02-10 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0169_database_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='is_additional_indicators',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='indicator',
            name='is_lcrp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='indicator',
            name='is_standalone_HAC_2',
            field=models.BooleanField(default=False),
        ),
    ]
