# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-03-12 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0171_database_last_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='last_update_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
