# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-03-12 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0172_auto_20210312_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='hpm_hac_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='indicator',
            name='hpm_hac_2_additional_cumulative',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='indicator',
            name='hpm_hac_2_note',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='hpm_hac_2_target',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='indicator',
            name='is_academic_year',
            field=models.BooleanField(default=False),
        ),
    ]
