# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-06-03 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0176_pagebuilder'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='last_live_update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='database',
            name='last_monthly_update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
