# Generated by Django 3.2.12 on 2022-03-10 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etools', '0057_auto_20220309_1103'),
        ('users', '0011_auto_20220309_1103'),
        ('activityinfo', '0177_auto_20210603_0717'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='database',
        #     name='last_weekly_update_date',
        #     field=models.DateTimeField(blank=True, null=True),
        # ),
        migrations.AlterField(
            model_name='activity',
            name='database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activityinfo.database'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='none_ai_database',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='activityinfo.database'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='programme_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='etools.pca'),
        ),
        migrations.AlterField(
            model_name='activityreport',
            name='ai_indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_indicators', to='activityinfo.indicator', verbose_name='Indicator'),
        ),
        migrations.AlterField(
            model_name='activityreport',
            name='indicator_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='activityreport',
            name='location_cadastral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='activityinfo.adminlevelentities'),
        ),
        migrations.AlterField(
            model_name='activityreport',
            name='location_caza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='activityinfo.adminlevelentities'),
        ),
        migrations.AlterField(
            model_name='activityreport',
            name='location_governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='activityinfo.adminlevels'),
        ),
        migrations.AlterField(
            model_name='activityreport',
            name='location_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='activityreport',
            name='partner_ai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='activityinfo.partner'),
        ),
        migrations.AlterField(
            model_name='activityreport',
            name='partner_label',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Partner'),
        ),
        migrations.AlterField(
            model_name='activityreport',
            name='programme_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='etools.pca'),
        ),
        migrations.AlterField(
            model_name='activityreport',
            name='project_label',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='adminlevelentities',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activityinfo.adminlevels'),
        ),
        migrations.AlterField(
            model_name='adminlevelentities',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activityinfo.adminlevelentities'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='attribute_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activityinfo.attributegroup'),
        ),
        migrations.AlterField(
            model_name='attributegroup',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activityinfo.activity'),
        ),
        migrations.AlterField(
            model_name='database',
            name='ai_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='database',
            name='db_id',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='ActivityInfo ID'),
        ),
        migrations.AlterField(
            model_name='database',
            name='focal_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='database',
            name='focal_point_sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='database',
            name='parent_id',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='ActivityInfo Parent ID'),
        ),
        migrations.AlterField(
            model_name='database',
            name='reporting_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activityinfo.reportingyear'),
        ),
        migrations.AlterField(
            model_name='database',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.section'),
        ),
        migrations.AlterField(
            model_name='database',
            name='year',
            field=models.CharField(blank=True, choices=[('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_indicators', to='activityinfo.activity'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='awp_code',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='RWP'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='awp_sector_code',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='RWP_Sector'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='denominator_indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='activityinfo.indicator'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='hpm_additional_cumulative',
            field=models.PositiveIntegerField(default=0, verbose_name='HPM Cumulative'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='hpm_hac_2_additional_cumulative',
            field=models.PositiveIntegerField(default=0, verbose_name='HPM HAC 2 Cumulative'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='hpm_hac_2_label',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='HPM HAC 2 Label'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='is_standalone_HAC_2',
            field=models.BooleanField(default=False, verbose_name='Is Standalone HAC 2 HPM'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='main_master_indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='activityinfo.indicator'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='master_indicator',
            field=models.BooleanField(default=False, verbose_name='Master indicator level 1'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='master_indicator_sub',
            field=models.BooleanField(default=False, verbose_name='Master indicator level 2'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='master_indicator_sub_sub',
            field=models.BooleanField(default=False, verbose_name='Master indicator level 3'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='measurement_type',
            field=models.CharField(blank=True, choices=[('numeric', 'Numeric'), ('percentage', 'Percentage'), ('percentage_x', 'Percentage multiple X'), ('weighting', 'Weighting')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='numerator_indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='activityinfo.indicator'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='etools.pca'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='ram_result',
            field=models.PositiveIntegerField(default=0, verbose_name='RAM Result'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='second_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_activity_indicators', to='activityinfo.activity'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='tag_age',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='activityinfo.indicatortag'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='tag_disability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='activityinfo.indicatortag'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='tag_focus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='activityinfo.indicatortag'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='tag_gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='activityinfo.indicatortag'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='tag_nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='activityinfo.indicatortag'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='tag_programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='activityinfo.indicatortag'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='third_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_activity_indicators', to='activityinfo.activity'),
        ),
        migrations.AlterField(
            model_name='indicatorpartner',
            name='ai_indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activityinfo.indicator'),
        ),
        migrations.AlterField(
            model_name='indicatorpartner',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activityinfo.partner'),
        ),
        migrations.AlterField(
            model_name='liveactivityreport',
            name='ai_indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activityinfo.indicator'),
        ),
        migrations.AlterField(
            model_name='liveactivityreport',
            name='partner_ai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='activityinfo.partner'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activityinfo.locationtypes'),
        ),
        migrations.AlterField(
            model_name='locationtypes',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activityinfo.locationtypes'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='database',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activityinfo.database'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_etools',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='etools.partnerorganization'),
        ),
        migrations.AlterField(
            model_name='sites',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activityinfo.activity'),
        ),
        migrations.AlterField(
            model_name='sites',
            name='database',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activityinfo.database'),
        ),
        migrations.AlterField(
            model_name='sites',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activityinfo.locations'),
        ),
        migrations.AlterField(
            model_name='sites',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activityinfo.partner'),
        ),
    ]
