# Generated by Django 3.2.12 on 2022-03-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0178'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='database',
        #     name='last_weekly_update_date',
        #     field=models.DateTimeField(blank=True, null=True),
        # ),
    ]
