# Generated by Django 3.2.12 on 2022-03-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0179'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlevelentities',
            name='bounds',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='configs',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='mapping_extraction1',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='mapping_extraction2',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='mapping_extraction3',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='comment',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='cumulative_values',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='cumulative_values_hpm',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='cumulative_values_live',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='cumulative_values_sector',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='highest_values',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='highest_values_live',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='results',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='targets',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='values',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='values_crisis_cumulative_live',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='values_crisis_gov_live',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='values_crisis_live',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='values_crisis_partners_gov_live',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='values_crisis_partners_live',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='values_cumulative_weekly',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='values_gov',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='values_gov_live',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='values_gov_weekly',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='values_hpm',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='values_live',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='values_partners',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='values_partners_gov',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='values_partners_gov_live',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='values_partners_gov_weekly',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='values_partners_live',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='values_partners_sector',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='values_partners_sites_sector',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='values_partners_weekly',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='values_sections',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='values_sections_gov',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='values_sections_gov_live',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='values_sections_live',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='values_sections_partners',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='values_sections_partners_gov',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='values_sections_partners_gov_live',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='values_sections_partners_live',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='values_sector',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='values_sites_sector',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='values_tags',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='values_tags_sector',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='values_tags_weekly',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='values_weekly',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='locations',
            name='admin_entities',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
