# Generated by Django 3.2.12 on 2022-03-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0181'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityreport',
            name='database',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='activityreport',
            name='form',
            field=models.CharField(blank=True, db_index=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='activityreport',
            name='form_category',
            field=models.CharField(blank=True, db_index=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='activityreport',
            name='funded_by',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='activityreport',
            name='governorate',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='activityreport',
            name='indicator_awp_code',
            field=models.CharField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='activityreport',
            name='indicator_category',
            field=models.CharField(blank=True, db_index=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='activityreport',
            name='indicator_id',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='activityreport',
            name='indicator_name',
            field=models.CharField(blank=True, db_index=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='activityreport',
            name='location_adminlevel_cadastral_area',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='activityreport',
            name='location_adminlevel_cadastral_area_code',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='activityreport',
            name='location_adminlevel_caza',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='activityreport',
            name='location_adminlevel_caza_code',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='activityreport',
            name='location_adminlevel_governorate',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='activityreport',
            name='location_adminlevel_governorate_code',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='activityreport',
            name='master_indicator',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='activityreport',
            name='master_indicator_sub',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='activityreport',
            name='month',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='activityreport',
            name='month_name',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='activityreport',
            name='partner_id',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='activityreport',
            name='partner_label',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True, verbose_name='Partner'),
        ),
        migrations.AlterField(
            model_name='activityreport',
            name='project_label',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True, verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='activityreport',
            name='report_id',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='activityreport',
            name='reporting_section',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='activityreport',
            name='site_id',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='activityreport',
            name='start_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
