# Generated by Django 3.2.12 on 2022-03-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityinfo', '0182_auto_20220323_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityreport',
            name='database_id',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
    ]
