# Generated by Django 5.2.17 on 2026-10-06 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HelpQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conversation",
                    models.UUIDField(
                        blank=True,
                        help_text="groups a question with its follow-ups",
                        null=True,
                    ),
                ),
                (
                    "page",
                    models.CharField(
                        blank=True,
                        help_text="the address the question was asked from",
                        max_length=200,
                    ),
                ),
                ("page_title", models.CharField(blank=True, max_length=150)),
                (
                    "question",
                    models.TextField(
                        help_text="as sent: names, e-mail addresses and phone numbers removed"
                    ),
                ),
                ("answer", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "Being answered"),
                            ("answered", "Answered"),
                            ("refused", "Declined"),
                            ("failed", "Failed"),
                            ("limited", "Over a limit"),
                        ],
                        db_index=True,
                        default="in_progress",
                        max_length=12,
                    ),
                ),
                (
                    "refused",
                    models.BooleanField(
                        default=False, help_text="declined: does not count in the quota"
                    ),
                ),
                ("refusal_reason", models.CharField(blank=True, max_length=20)),
                (
                    "tools",
                    models.JSONField(
                        blank=True, default=list, help_text="look-ups made, in order"
                    ),
                ),
                ("model", models.CharField(blank=True, max_length=64)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("cache_read_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "help question",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="help_helpqu_user_id_b1b631_idx",
                    ),
                    models.Index(
                        fields=["user", "conversation", "created_at"],
                        name="help_helpqu_user_id_e4029c_idx",
                    ),
                ],
            },
        ),
    ]
