# Generated by Django 5.2.17 on 2026-09-22 19:08

import django.contrib.postgres.fields
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActionPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "author_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "assigned_by_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "assigned_to_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices="[('open', 'Open'), ('completed', 'Completed')]",
                        default="open",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                ("status_date", models.DateTimeField(blank=True, null=True)),
                (
                    "category_name",
                    models.CharField(blank=True, max_length=1500, null=True),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="Due Date"),
                ),
                (
                    "high_priority",
                    models.BooleanField(default=False, verbose_name="High Priority"),
                ),
                ("date_of_completion", models.DateTimeField(blank=True, null=True)),
                (
                    "related_module",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "reference_number",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("comments", models.TextField(blank=True, null=True)),
            ],
            options={"managed": settings.LEGACY_TABLES_MANAGED, 
                "verbose_name": "Action Point",
                "verbose_name_plural": "Action Points",
                "db_table": "etools_actionpoint",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Agreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "etl_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="eTools ID"
                    ),
                ),
                (
                    "partner_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "agreement_type",
                    models.CharField(
                        choices=[
                            ("PCA", "Programme Cooperation Agreement"),
                            ("SSFA", "Small Scale Funding Agreement"),
                            ("MOU", "Memorandum of Understanding"),
                            ("IC", "Institutional Contract"),
                            ("AWP", "Work Plan"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "agreement_number",
                    models.CharField(
                        blank=True, max_length=45, verbose_name="Reference Number"
                    ),
                ),
                ("start", models.DateField(blank=True, null=True)),
                ("end", models.DateField(blank=True, null=True)),
                ("signed_by_unicef_date", models.DateField(blank=True, null=True)),
                ("signed_by_partner_date", models.DateField(blank=True, null=True)),
            ],
            options={"managed": settings.LEGACY_TABLES_MANAGED, 
                "verbose_name": "agreement",
                "verbose_name_plural": "agreements",
                "db_table": "etools_agreement",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices="[('apd', 'Action Points'), ('t2f', 'Trip Management'), ('tpm', 'Third Party Monitoring'), ('audit', 'Financial Assurance')]",
                        max_length=10,
                        verbose_name="Module",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
            ],
            options={"managed": settings.LEGACY_TABLES_MANAGED, 
                "verbose_name": "Action point category",
                "verbose_name_plural": "Action point categories",
                "db_table": "etools_category",
                "ordering": ("module", "order"),
            },
        ),
        migrations.CreateModel(
            name="DonorFunding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("donor", models.CharField(blank=True, max_length=255, null=True)),
                ("donor_code", models.CharField(blank=True, max_length=255, null=True)),
                ("grant", models.CharField(blank=True, max_length=255, null=True)),
                ("year", models.CharField(blank=True, max_length=255, null=True)),
                ("total_contribution", models.FloatField(blank=True, null=True)),
                ("programmable", models.FloatField(blank=True, null=True)),
                ("total", models.FloatField(blank=True, null=True)),
                ("comment", models.CharField(blank=True, max_length=1500, null=True)),
            ],
            options={"managed": settings.LEGACY_TABLES_MANAGED, 
                "verbose_name": "donor funding",
                "verbose_name_plural": "donor fundings",
                "db_table": "etools_donorfunding",
            },
        ),
        migrations.CreateModel(
            name="Engagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("unique_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "displayed_name",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices="[('partner_contacted', 'IP Contacted'), ('report_submitted', 'Report Submitted'), ('final', 'Final Report'), ('cancelled', 'Cancelled')]",
                        default="partner_contacted",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                ("agreement", models.JSONField(blank=True, null=True)),
                ("po_item", models.JSONField(blank=True, null=True)),
                (
                    "partner_contacted_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date IP was contacted"
                    ),
                ),
                (
                    "engagement_type",
                    models.CharField(
                        choices="[('audit', 'Audit'), ('ma', 'Micro Assessment'), ('sc', 'Spot Check'), ('sa', 'Special Audit')]",
                        max_length=10,
                        verbose_name="Engagement Type",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Period Start Date"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Period End Date"
                    ),
                ),
                (
                    "total_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Total value of selected FACE form(s)",
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Exchange Rate",
                    ),
                ),
                (
                    "engagement_attachments",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "report_attachments",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "date_of_field_visit",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of Field Visit"
                    ),
                ),
                (
                    "date_of_draft_report_to_ip",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Date Draft Report Issued to IP",
                    ),
                ),
                (
                    "date_of_comments_by_ip",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Date Comments Received from IP",
                    ),
                ),
                (
                    "date_of_draft_report_to_unicef",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Date Draft Report Issued to UNICEF",
                    ),
                ),
                (
                    "date_of_comments_by_unicef",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Date Comments Received from UNICEF",
                    ),
                ),
                (
                    "date_of_report_submit",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date Report Submitted"
                    ),
                ),
                (
                    "date_of_final_report",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date Report Finalized"
                    ),
                ),
                (
                    "date_of_cancel",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date Report Cancelled"
                    ),
                ),
                (
                    "amount_refunded",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Amount Refunded",
                    ),
                ),
                (
                    "additional_supporting_documentation_provided",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Additional Supporting Documentation Provided",
                    ),
                ),
                (
                    "justification_provided_and_accepted",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Justification Provided and Accepted",
                    ),
                ),
                (
                    "write_off_required",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Impairment",
                    ),
                ),
                (
                    "explanation_for_additional_information",
                    models.TextField(
                        blank=True,
                        verbose_name="Provide explanation for additional information received from the IP or add attachments",
                    ),
                ),
                (
                    "joint_audit",
                    models.BooleanField(
                        blank=True, default=False, verbose_name="Joint Audit"
                    ),
                ),
                (
                    "shared_ip_with",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("DPKO", "DPKO"),
                                ("ECA", "ECA"),
                                ("ECLAC", "ECLAC"),
                                ("ESCWA", "ESCWA"),
                                ("FAO", "FAO"),
                                ("ILO", "ILO"),
                                ("IOM", "IOM"),
                                ("OHCHR", "OHCHR"),
                                ("UN", "UN"),
                                ("UN Women", "UN Women"),
                                ("UNAIDS", "UNAIDS"),
                                ("UNDP", "UNDP"),
                                ("UNESCO", "UNESCO"),
                                ("UNFPA", "UNFPA"),
                                ("UN - Habitat", "UN - Habitat"),
                                ("UNHCR", "UNHCR"),
                                ("UNODC", "UNODC"),
                                ("UNOPS", "UNOPS"),
                                ("UNRWA", "UNRWA"),
                                ("UNSC", "UNSC"),
                                ("UNU", "UNU"),
                                ("WB", "WB"),
                                ("WFP", "WFP"),
                                ("WHO", "WHO"),
                            ],
                            max_length=20,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Shared Audit with",
                    ),
                ),
                (
                    "staff_members",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=2500),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "cancel_comment",
                    models.TextField(blank=True, verbose_name="Cancel Comment"),
                ),
                (
                    "authorized_officers",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=2500),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "total_amount_tested",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Total Amount Tested",
                    ),
                ),
                (
                    "total_amount_of_ineligible_expenditure",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Total Amount of Ineligible Expenditure",
                    ),
                ),
                (
                    "internal_controls",
                    models.TextField(blank=True, verbose_name="Internal Controls"),
                ),
                (
                    "final_report",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "audited_expenditure",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Audited Expenditure $",
                    ),
                ),
                (
                    "financial_findings",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Financial Findings $",
                    ),
                ),
                (
                    "audit_opinion",
                    models.CharField(
                        blank=True,
                        choices="[('unqualified', 'Unqualified'), ('qualified', 'Qualified'), ('disclaimer_opinion', 'Disclaimer opinion'), ('adverse_opinion', 'Adverse opinion')]",
                        default="",
                        max_length=20,
                        verbose_name="Audit Opinion",
                    ),
                ),
                ("description", models.TextField()),
                ("finding", models.TextField(blank=True)),
                (
                    "pending_unsupported_amount",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "findings",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=10000),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("findings_sets", models.JSONField(blank=True, null=True)),
            ],
            options={"managed": settings.LEGACY_TABLES_MANAGED, 
                "verbose_name": "Engagement",
                "verbose_name_plural": "Engagements",
                "db_table": "etools_engagement",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="PartnerOrganization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "etl_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="eTools ID"
                    ),
                ),
                (
                    "partner_type",
                    models.CharField(
                        choices=[
                            ("Bilateral / Multilateral", "Bilateral / Multilateral"),
                            (
                                "Civil Society Organization",
                                "Civil Society Organization",
                            ),
                            ("Government", "Government"),
                            ("UN Agency", "UN Agency"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "shared_with",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True,
                            choices=[
                                ("DPKO", "DPKO"),
                                ("ECA", "ECA"),
                                ("ECLAC", "ECLAC"),
                                ("ESCWA", "ESCWA"),
                                ("FAO", "FAO"),
                                ("ILO", "ILO"),
                                ("IOM", "IOM"),
                                ("OHCHR", "OHCHR"),
                                ("UN", "UN"),
                                ("UN Women", "UN Women"),
                                ("UNAIDS", "UNAIDS"),
                                ("UNDP", "UNDP"),
                                ("UNESCO", "UNESCO"),
                                ("UNFPA", "UNFPA"),
                                ("UN - Habitat", "UN - Habitat"),
                                ("UNHCR", "UNHCR"),
                                ("UNODC", "UNODC"),
                                ("UNOPS", "UNOPS"),
                                ("UNRWA", "UNRWA"),
                                ("UNSC", "UNSC"),
                                ("UNU", "UNU"),
                                ("WB", "WB"),
                                ("WFP", "WFP"),
                                ("WHO", "WHO"),
                            ],
                            max_length=20,
                        ),
                        blank=True,
                        null=True,
                        size=None,
                        verbose_name="Shared Partner",
                    ),
                ),
                (
                    "cso_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("International", "International"),
                            ("National", "National"),
                            (
                                "Community Based Organisation",
                                "Community Based Organisation",
                            ),
                            ("Academic Institution", "Academic Institution"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="CSO Type",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Please make sure this matches the name you enter in VISION",
                        max_length=255,
                        verbose_name="Full Name",
                    ),
                ),
                ("short_name", models.CharField(blank=True, max_length=50)),
                ("description", models.CharField(blank=True, max_length=256)),
                (
                    "shared_partner",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("No", "No"),
                            ("with UNDP", "with UNDP"),
                            ("with UNFPA", "with UNFPA"),
                            ("with UNDP & UNFPA", "with UNDP & UNFPA"),
                        ],
                        default="No",
                        help_text="Partner shared with UNDP or UNFPA?",
                        max_length=50,
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "vendor_number",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("alternate_id", models.IntegerField(blank=True, null=True)),
                (
                    "alternate_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "rating",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Risk Rating"
                    ),
                ),
                ("deleted_flag", models.BooleanField(default=False)),
                ("blocked", models.BooleanField(default=False)),
                ("hidden", models.BooleanField(default=False)),
                ("comments", models.TextField(blank=True, null=True)),
                ("staff_members", models.JSONField(blank=True, null=True)),
                ("assessments", models.JSONField(blank=True, null=True)),
                ("planned_engagement", models.JSONField(blank=True, null=True)),
                ("hact_values", models.JSONField(blank=True, null=True)),
                ("hact_min_requirements", models.JSONField(blank=True, null=True)),
                ("planned_visits", models.JSONField(blank=True, null=True)),
                ("core_values_assessments", models.JSONField(blank=True, null=True)),
                ("flags", models.JSONField(blank=True, null=True)),
                (
                    "type_of_assessment",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("last_assessment_date", models.DateField(blank=True, null=True)),
                (
                    "core_values_assessment_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "total_ct_cp",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "total_ct_cy",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("net_ct_cy", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "reported_cy",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "total_ct_ytd",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
            ],
            options={"managed": settings.LEGACY_TABLES_MANAGED, 
                "verbose_name": "partner organization",
                "verbose_name_plural": "partner organizations",
                "db_table": "etools_partnerorganization",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="PartnerStaffMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("first_name", models.CharField(max_length=64)),
                ("last_name", models.CharField(max_length=64)),
                ("email", models.CharField(blank=True, max_length=128)),
                ("phone", models.CharField(max_length=64)),
                ("active", models.BooleanField(default=True)),
            ],
            options={"managed": settings.LEGACY_TABLES_MANAGED, 
                "verbose_name": "partner staff member",
                "verbose_name_plural": "partner staff members",
                "db_table": "etools_partnerstaffmember",
            },
        ),
        migrations.CreateModel(
            name="PCA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "etl_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="eTools ID"
                    ),
                ),
                (
                    "partner_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "document_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PD", "Programme Document"),
                            ("SHPD", "Simplified Humanitarian Programme Document"),
                            ("AWP", "Cash Transfers to Government"),
                            ("SSFA", "SSFA TOR"),
                            ("IC", "IC TOR"),
                        ],
                        default="PD",
                        max_length=255,
                        null=True,
                        verbose_name="Document type",
                    ),
                ),
                (
                    "country_programme",
                    models.CharField(
                        blank=True,
                        help_text="Which result structure does this partnership report under?",
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        max_length=45,
                        null=True,
                        verbose_name="Reference Number",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                (
                    "project_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Bulk Procurement", "Bulk Procurement"),
                            ("Construction Project", "Construction Project"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        default="in_process",
                        help_text="In Process = In discussion with partner, Active = Currently ongoing, Implemented = completed, Cancelled = cancelled or not approved",
                        max_length=32,
                    ),
                ),
                (
                    "start",
                    models.DateField(
                        blank=True,
                        help_text="The date the Intervention will start",
                        null=True,
                        verbose_name="Partnership start date",
                    ),
                ),
                (
                    "end",
                    models.DateField(
                        blank=True,
                        help_text="The date the Intervention will end",
                        null=True,
                        verbose_name="Partnership end date",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="The date the Intervention will end",
                        null=True,
                        verbose_name="Partnership end date",
                    ),
                ),
                (
                    "initiation_date",
                    models.DateField(
                        blank=True,
                        help_text="The date the partner submitted complete partnership documents to Unicef",
                        null=True,
                        verbose_name="Submission Date",
                    ),
                ),
                (
                    "submission_date",
                    models.DateField(
                        blank=True,
                        help_text="The date the documents were submitted to the PRC",
                        null=True,
                        verbose_name="Submission Date to PRC",
                    ),
                ),
                (
                    "review_date",
                    models.DateField(
                        blank=True,
                        help_text="The date the PRC reviewed the partnership",
                        null=True,
                        verbose_name="Review date by PRC",
                    ),
                ),
                ("signed_by_unicef_date", models.DateField(blank=True, null=True)),
                ("signed_by_partner_date", models.DateField(blank=True, null=True)),
                ("fr_number", models.CharField(blank=True, max_length=50, null=True)),
                ("planned_visits", models.IntegerField(default=0)),
                ("sectors", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "offices_names",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "offices_set",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("current", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "total_budget",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "fr_currency",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "frs_total_intervention_amt",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "frs_latest_end_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "frs_total_frs_amt",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "fr_currencies_are_consistent",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "unicef_cash",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "multi_curr_flag",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "actual_amount",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "frs_total_outstanding_amt",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "budget_currency",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "frs_earliest_start_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "cso_contribution",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "all_currencies_are_consistent",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "total_unicef_budget",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "grants",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "unicef_focal_points",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "section_names",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "sections",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "donors",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "donor_codes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "flagged_sections",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "location_p_codes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "offices",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "cp_outputs",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "planned_budget",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "amendments",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "result_links",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "location_names",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "planned_visits_list",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("frs_details", models.JSONField(blank=True, default=dict, null=True)),
                ("donors_set", models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={"managed": settings.LEGACY_TABLES_MANAGED, 
                "verbose_name": "Intervention",
                "verbose_name_plural": "Interventions",
                "db_table": "etools_pca",
                "ordering": ("-partner_name",),
            },
        ),
        migrations.CreateModel(
            name="Travel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed At"
                    ),
                ),
                (
                    "canceled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Canceled At"
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Submitted At"
                    ),
                ),
                (
                    "first_submission_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="First Submission Date"
                    ),
                ),
                (
                    "rejected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Rejected At"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approved At"
                    ),
                ),
                (
                    "rejection_note",
                    models.TextField(
                        blank=True, default="", verbose_name="Rejection Note"
                    ),
                ),
                (
                    "cancellation_note",
                    models.TextField(
                        blank=True, default="", verbose_name="Cancellation Note"
                    ),
                ),
                (
                    "certification_note",
                    models.TextField(
                        blank=True, default="", verbose_name="Certification Note"
                    ),
                ),
                (
                    "report_note",
                    models.TextField(
                        blank=True, default="", verbose_name="Report Note"
                    ),
                ),
                (
                    "misc_expenses",
                    models.TextField(
                        blank=True, default="", verbose_name="Misc Expenses"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="planned", max_length=500, verbose_name="Status"
                    ),
                ),
                (
                    "traveler_name",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "supervisor_name",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="Start Date"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="End Date"),
                ),
                (
                    "purpose",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="Purpose"
                    ),
                ),
                (
                    "additional_note",
                    models.TextField(
                        blank=True, default="", verbose_name="Additional Note"
                    ),
                ),
                (
                    "international_travel",
                    models.BooleanField(
                        default=False, verbose_name="International Travel"
                    ),
                ),
                (
                    "ta_required",
                    models.BooleanField(default=True, verbose_name="TA Required"),
                ),
                (
                    "reference_number",
                    models.CharField(max_length=12, verbose_name="Reference Number"),
                ),
                ("hidden", models.BooleanField(default=False, verbose_name="Hidden")),
                (
                    "mode_of_travel",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("Plane", "Plane"),
                                ("Bus", "Bus"),
                                ("Car", "Car"),
                                ("Boat", "Boat"),
                                ("Rail", "Rail"),
                            ],
                            max_length=5,
                        ),
                        blank=True,
                        null=True,
                        size=None,
                        verbose_name="Mode of Travel",
                    ),
                ),
                (
                    "estimated_travel_cost",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=20,
                        verbose_name="Estimated Travel Cost",
                    ),
                ),
                (
                    "is_driver",
                    models.BooleanField(default=False, verbose_name="Is Driver"),
                ),
                (
                    "preserved_expenses_local",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        default=None,
                        max_digits=20,
                        null=True,
                        verbose_name="Preserved Expenses (Local)",
                    ),
                ),
                (
                    "preserved_expenses_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        default=None,
                        max_digits=20,
                        null=True,
                        verbose_name="Preserved Expenses (USD)",
                    ),
                ),
                (
                    "approved_cost_traveler",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        default=None,
                        max_digits=20,
                        null=True,
                        verbose_name="Approved Cost Traveler",
                    ),
                ),
                (
                    "approved_cost_travel_agencies",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        default=None,
                        max_digits=20,
                        null=True,
                        verbose_name="Approved Cost Travel Agencies",
                    ),
                ),
                (
                    "itinerary_set",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=10000),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "activities_set",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=10000),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "attachments_set",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=10000),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("attachments_sets", models.JSONField(blank=True, null=True)),
                ("have_hact", models.IntegerField(blank=True, null=True)),
                (
                    "travel_type",
                    models.CharField(
                        blank=True,
                        default="Programmatic Visit",
                        max_length=64,
                        verbose_name="Travel Type",
                    ),
                ),
            ],
            options={"managed": settings.LEGACY_TABLES_MANAGED, 
                "verbose_name": "travel",
                "verbose_name_plural": "travels",
                "db_table": "etools_travel",
            },
        ),
        migrations.CreateModel(
            name="TravelActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "travel_type",
                    models.CharField(
                        blank=True,
                        default="Programmatic Visit",
                        max_length=64,
                        verbose_name="Travel Type",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="Date")),
                ("is_primary_traveler", models.BooleanField(default=False)),
            ],
            options={"managed": settings.LEGACY_TABLES_MANAGED, 
                "verbose_name": "travel activity",
                "verbose_name_plural": "Travel Activities",
                "db_table": "etools_travelactivity",
            },
        ),
    ]
