# Generated by Django 5.2.17 on 2026-09-24 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etools", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        max_length=250, unique=True, verbose_name="ActivityInfo partner"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("manual", "Set by hand"),
                            ("name", "Same name"),
                            ("pd", "Programme document number"),
                            ("", "Not linked"),
                        ],
                        default="",
                        max_length=10,
                        verbose_name="Linked by",
                    ),
                ),
                (
                    "records",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Activity records"
                    ),
                ),
                (
                    "first_month",
                    models.CharField(
                        blank=True,
                        help_text="YYYY-MM of the first record",
                        max_length=7,
                    ),
                ),
                (
                    "last_month",
                    models.CharField(
                        blank=True, help_text="YYYY-MM of the last record", max_length=7
                    ),
                ),
                (
                    "database_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="ActivityInfo databases reported in",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activityinfo_links",
                        to="etools.partnerorganization",
                        verbose_name="eTools partner",
                    ),
                ),
            ],
            options={
                "verbose_name": "ActivityInfo partner link",
                "verbose_name_plural": "ActivityInfo partner links",
                "ordering": ("label",),
            },
        ),
    ]
