# Generated by Django 5.2.17 on 2026-09-30 08:45

import django.core.validators
import django.db.models.deletion
import neurodb.cpd.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("etools", "0003_partnerlink"),
        ("pivoting", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountryProgramme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Lebanon Country Programme 2026-2028",
                        max_length=200,
                    ),
                ),
                ("start_year", models.PositiveSmallIntegerField()),
                (
                    "end_year",
                    models.PositiveSmallIntegerField(
                        help_text="the last year of the cycle (2, 3 or 5 years)"
                    ),
                ),
                (
                    "etools_name",
                    models.CharField(
                        blank=True,
                        help_text="the country programme as eTools writes it on programme documents, to find the interventions",
                        max_length=200,
                        verbose_name="country programme in eTools",
                    ),
                ),
                (
                    "current",
                    models.BooleanField(
                        default=False, help_text="the cycle the dashboard opens on"
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                (
                    "updated_by",
                    models.CharField(blank=True, editable=False, max_length=150),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "country programme cycle",
                "ordering": ("-start_year", "name"),
            },
        ),
        migrations.CreateModel(
            name="CPDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("cpd", "Country programme document (CPD)"),
                            ("rrf", "Results and resources framework"),
                            ("annex", "Annex or programme strategy note"),
                            ("review", "Review or evaluation"),
                            ("other", "Other material"),
                        ],
                        default="cpd",
                        max_length=16,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="PDF, Word, Excel or PowerPoint, 50 MB at most",
                        max_length=300,
                        upload_to=neurodb.cpd.models.document_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ("pdf", "docx", "doc", "xlsx", "xls", "pptx", "ppt")
                            ),
                            neurodb.cpd.models.max_size,
                        ],
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=500)),
                (
                    "uploaded_by",
                    models.CharField(blank=True, editable=False, max_length=150),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "programme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="cpd.countryprogramme",
                    ),
                ),
            ],
            options={
                "verbose_name": "CPD document",
                "ordering": ("programme", "kind", "title"),
            },
        ),
        migrations.CreateModel(
            name="FrameworkProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Reading the document"),
                            ("ready", "Ready to review"),
                            ("applied", "Applied"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=10,
                    ),
                ),
                ("items", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True)),
                ("requested_by", models.CharField(blank=True, max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="cpd.cpdocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI-suggested framework",
                "verbose_name_plural": "AI-suggested frameworks",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Indicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=30)),
                ("title", models.TextField()),
                (
                    "unit",
                    models.CharField(
                        choices=[("number", "Number"), ("percent", "Percentage")],
                        default="number",
                        max_length=10,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("increase", "Increase"), ("decrease", "Decrease")],
                        default="increase",
                        max_length=10,
                    ),
                ),
                (
                    "accumulate",
                    models.CharField(
                        choices=[
                            ("latest", "Latest year's value (a level, e.g. a rate)"),
                            ("sum", "Sum over the cycle (e.g. children reached)"),
                        ],
                        default="latest",
                        help_text="how the yearly values make the cycle's value",
                        max_length=10,
                    ),
                ),
                ("baseline", models.FloatField(blank=True, null=True)),
                (
                    "baseline_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "target",
                    models.FloatField(
                        blank=True, help_text="end-of-cycle target", null=True
                    ),
                ),
                ("means_of_verification", models.TextField(blank=True)),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("manual", "Entered in the admin"),
                            ("imported", "Imported from Excel"),
                            ("ai_suggested", "AI-suggested"),
                        ],
                        default="manual",
                        max_length=16,
                    ),
                ),
                (
                    "programme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicators",
                        to="cpd.countryprogramme",
                    ),
                ),
            ],
            options={
                "ordering": ("programme", "code", "id"),
            },
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("etools", "eTools PD indicator (partner reporting)"),
                            ("activityinfo", "ActivityInfo master indicator"),
                            ("youth", "Compiler youth indicator"),
                            ("education", "Compiler Makani / Dirasa enrolment"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        help_text="the CPD year this source counts for"
                    ),
                ),
                ("etools_key", models.CharField(blank=True, max_length=32)),
                ("youth_level", models.CharField(blank=True, max_length=8)),
                ("youth_id", models.PositiveIntegerField(blank=True, null=True)),
                ("education_programme", models.CharField(blank=True, max_length=16)),
                (
                    "source_period",
                    models.CharField(
                        blank=True,
                        help_text="Compiler's year or round of the figures (youth, education)",
                        max_length=64,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="what the source is, as shown on the dashboard",
                        max_length=500,
                    ),
                ),
                (
                    "confirmed",
                    models.BooleanField(
                        default=True,
                        help_text="suggested links count only once confirmed",
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(blank=True, editable=False, max_length=150),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="cpd.indicator",
                    ),
                ),
                (
                    "master",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="pivoting.masterindicator",
                    ),
                ),
                (
                    "pd",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="etools.pca",
                    ),
                ),
            ],
            options={
                "ordering": ("indicator", "year", "kind"),
            },
        ),
        migrations.CreateModel(
            name="Outcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(help_text="e.g. 1", max_length=20)),
                ("title", models.TextField()),
                (
                    "sections",
                    models.CharField(
                        blank=True,
                        help_text="the eTools sections in charge",
                        max_length=300,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("manual", "Entered in the admin"),
                            ("imported", "Imported from Excel"),
                            ("ai_suggested", "AI-suggested"),
                        ],
                        default="manual",
                        max_length=16,
                    ),
                ),
                (
                    "programme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outcomes",
                        to="cpd.countryprogramme",
                    ),
                ),
            ],
            options={
                "ordering": ("programme", "code"),
            },
        ),
        migrations.AddField(
            model_name="indicator",
            name="outcome",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="indicators",
                to="cpd.outcome",
            ),
        ),
        migrations.CreateModel(
            name="Output",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(help_text="e.g. 1.1", max_length=20)),
                ("title", models.TextField()),
                (
                    "etools_output",
                    models.CharField(
                        blank=True,
                        help_text="the output as eTools names it on programme documents (blank: matched by its code)",
                        max_length=300,
                        verbose_name="eTools CP output",
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("manual", "Entered in the admin"),
                            ("imported", "Imported from Excel"),
                            ("ai_suggested", "AI-suggested"),
                        ],
                        default="manual",
                        max_length=16,
                    ),
                ),
                (
                    "outcome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outputs",
                        to="cpd.outcome",
                    ),
                ),
            ],
            options={
                "ordering": ("outcome", "code"),
            },
        ),
        migrations.AddField(
            model_name="indicator",
            name="output",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="indicators",
                to="cpd.output",
            ),
        ),
        migrations.CreateModel(
            name="Value",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                ("value", models.FloatField()),
                (
                    "source",
                    models.CharField(
                        help_text="e.g. MICS 2027, MEHE data, annual report",
                        max_length=250,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=500)),
                (
                    "updated_by",
                    models.CharField(blank=True, editable=False, max_length=150),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="cpd.indicator",
                    ),
                ),
            ],
            options={
                "ordering": ("indicator", "year"),
            },
        ),
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                ("value", models.FloatField()),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="cpd.indicator",
                    ),
                ),
            ],
            options={
                "ordering": ("indicator", "year"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("indicator", "year"), name="cpd_milestone_year"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="outcome",
            constraint=models.UniqueConstraint(
                fields=("programme", "code"), name="cpd_outcome_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="value",
            constraint=models.UniqueConstraint(
                fields=("indicator", "year"), name="cpd_value_year"
            ),
        ),
    ]
