# Generated by Django 5.2.17 on 2026-09-30 09:06

import django.core.validators
import neurodb.cpd.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpd", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cpdocument",
            name="file",
            field=models.FileField(
                help_text="PDF, Word, text, Excel or PowerPoint, 50 MB at most",
                max_length=300,
                upload_to=neurodb.cpd.models.document_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        (
                            "pdf",
                            "docx",
                            "doc",
                            "txt",
                            "md",
                            "xlsx",
                            "xls",
                            "pptx",
                            "ppt",
                        )
                    ),
                    neurodb.cpd.models.max_size,
                ],
            ),
        ),
    ]
